-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE "yak_dashboard" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "name" citext NOT NULL CHECK (length("name") <= 200),
  "description" citext CHECK (length("description") <= 2000),
  "current_version_id" bigint,
  "current_version_no" integer DEFAULT 0 NOT NULL,
  "published_version_id" bigint,
  "published_version_no" integer DEFAULT 0 NOT NULL,
  "published_time" timestamp(6) without time zone,
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dashboard_idx_yak_dashboard_current_version" ON "yak_dashboard" ("current_version_id");

CREATE INDEX "yak_dashboard_idx_yak_dashboard_project_update" ON "yak_dashboard" ("project_id", "update_time", "id");

CREATE INDEX "yak_dashboard_idx_yak_dashboard_published_version" ON "yak_dashboard" ("published_version_id");

CREATE INDEX "yak_dashboard_idx_yak_dashboard_update" ON "yak_dashboard" ("update_time");

CREATE TABLE "yak_dashboard_version" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "dashboard_id" bigint NOT NULL,
  "version_no" integer NOT NULL,
  "name_snapshot" citext NOT NULL CHECK (length("name_snapshot") <= 200),
  "description_snapshot" citext CHECK (length("description_snapshot") <= 2000),
  "active_dataset_id" bigint,
  "theme_json" jsonb,
  "create_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_dashboard_version_uk_yak_dashboard_version_no" ON "yak_dashboard_version" ("dashboard_id", "version_no");

CREATE TABLE "yak_dashboard_widget" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "dashboard_version_id" bigint NOT NULL,
  "widget_key" citext NOT NULL CHECK (length("widget_key") <= 64),
  "analysis_id" bigint,
  "title" citext CHECK (length("title") <= 200),
  "inline_analysis_json" jsonb,
  "grid_x" integer NOT NULL,
  "grid_y" integer NOT NULL,
  "grid_w" integer NOT NULL,
  "grid_h" integer NOT NULL,
  "min_w" integer,
  "min_h" integer,
  "sort_order" integer DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dashboard_widget_idx_yak_dashboard_widget_analysis" ON "yak_dashboard_widget" ("analysis_id");

CREATE UNIQUE INDEX "yak_dashboard_widget_uk_yak_dashboard_widget_key" ON "yak_dashboard_widget" ("dashboard_version_id", "widget_key");

CREATE TABLE "yak_dashboard_filter" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "dashboard_version_id" bigint NOT NULL,
  "filter_key" citext NOT NULL CHECK (length("filter_key") <= 64),
  "name" citext NOT NULL CHECK (length("name") <= 200),
  "operator" citext NOT NULL CHECK (length("operator") <= 32),
  "default_value_json" jsonb,
  "sort_order" integer DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_dashboard_filter_uk_yak_dashboard_filter_key" ON "yak_dashboard_filter" ("dashboard_version_id", "filter_key");

CREATE TABLE "yak_dashboard_filter_binding" (
  "dashboard_version_id" bigint NOT NULL,
  "filter_key" citext NOT NULL CHECK (length("filter_key") <= 64),
  "widget_key" citext NOT NULL CHECK (length("widget_key") <= 64),
  "field_id" citext NOT NULL CHECK (length("field_id") <= 64),
  "sort_order" integer DEFAULT 0 NOT NULL,
  PRIMARY KEY ("dashboard_version_id", "filter_key", "widget_key")
);

CREATE INDEX "yak_dashboard_filter_binding_idx_yak_dashboard_filter__cba37706" ON "yak_dashboard_filter_binding" ("dashboard_version_id", "widget_key");

CREATE TABLE "yak_dashboard_interaction" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "dashboard_version_id" bigint NOT NULL,
  "interaction_key" citext NOT NULL CHECK (length("interaction_key") <= 64),
  "event_type" citext NOT NULL CHECK (length("event_type") <= 32),
  "source_widget_key" citext NOT NULL CHECK (length("source_widget_key") <= 64),
  "source_field_id" citext NOT NULL CHECK (length("source_field_id") <= 64),
  "target_filter_key" citext NOT NULL CHECK (length("target_filter_key") <= 64),
  "sort_order" integer DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dashboard_interaction_idx_yak_dashboard_interaction_filter" ON "yak_dashboard_interaction" ("dashboard_version_id", "target_filter_key");

CREATE INDEX "yak_dashboard_interaction_idx_yak_dashboard_interaction_source" ON "yak_dashboard_interaction" ("dashboard_version_id", "source_widget_key");

CREATE UNIQUE INDEX "yak_dashboard_interaction_uk_yak_dashboard_interaction_key" ON "yak_dashboard_interaction" ("dashboard_version_id", "interaction_key");
