-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_ops_data_service_api" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "name" citext NOT NULL CHECK (length("name") <= 128),
  "path" citext NOT NULL CHECK (length("path") <= 255),
  "data_source_id" bigint NOT NULL,
  "sql_text" text NOT NULL,
  "max_rows" integer DEFAULT 1000 NOT NULL,
  "timeout_seconds" integer DEFAULT 30 NOT NULL,
  "pagination_enabled" smallint DEFAULT 0 NOT NULL,
  "enabled" smallint DEFAULT 0 NOT NULL,
  "auth_mode" citext DEFAULT 'NONE' NOT NULL CHECK (length("auth_mode") <= 32),
  "cache_enabled" smallint DEFAULT 0 NOT NULL,
  "cache_ttl_seconds" integer DEFAULT 60 NOT NULL,
  "cache_max_entries" integer DEFAULT 200 NOT NULL,
  "circuit_breaker_enabled" smallint DEFAULT 0 NOT NULL,
  "circuit_failure_threshold" integer DEFAULT 5 NOT NULL,
  "circuit_recovery_seconds" integer DEFAULT 30 NOT NULL,
  "runtime_generation" bigint DEFAULT 1 NOT NULL,
  "description" citext CHECK (length("description") <= 500),
  "source_type" citext CHECK (length("source_type") <= 64),
  "source_ref" citext CHECK (length("source_ref") <= 128),
  "source_revision_id" bigint,
  "source_revision_no" integer,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_ops_data_service_api_idx_yak_ops_data_service_auth_mode" ON "yak_ops_data_service_api" ("auth_mode");

CREATE INDEX "yak_ops_data_service_api_idx_yak_ops_data_service_ds" ON "yak_ops_data_service_api" ("data_source_id");

CREATE INDEX "yak_ops_data_service_api_idx_yak_ops_data_service_enabled" ON "yak_ops_data_service_api" ("enabled");

CREATE INDEX "yak_ops_data_service_api_idx_yak_ops_data_service_proj_f8be17dc" ON "yak_ops_data_service_api" ("project_id", "enabled");

CREATE INDEX "yak_ops_data_service_api_idx_yak_ops_data_service_proj_2207b096" ON "yak_ops_data_service_api" ("project_id", "update_time", "id");

CREATE INDEX "yak_ops_data_service_api_idx_yak_ops_data_service_sour_58f80d56" ON "yak_ops_data_service_api" ("source_revision_id");

CREATE INDEX "yak_ops_data_service_api_idx_yak_ops_data_service_update_time" ON "yak_ops_data_service_api" ("update_time");

CREATE UNIQUE INDEX "yak_ops_data_service_api_uk_yak_ops_data_service_path" ON "yak_ops_data_service_api" ("path");

CREATE UNIQUE INDEX "yak_ops_data_service_api_uk_yak_ops_data_service_source" ON "yak_ops_data_service_api" ("source_type", "source_ref");

CREATE TRIGGER "yak_ops_data_service_api_touch" BEFORE UPDATE ON "yak_ops_data_service_api" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_ops_data_service_api_key" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "api_id" bigint,
  "consumer_id" bigint,
  "name" citext NOT NULL CHECK (length("name") <= 128),
  "key_prefix" citext NOT NULL CHECK (length("key_prefix") <= 24),
  "key_hash" citext NOT NULL CHECK (length("key_hash") <= 64),
  "enabled" smallint DEFAULT 1 NOT NULL,
  "rate_limit_per_minute" integer DEFAULT 60 NOT NULL,
  "expires_at" timestamp(3) without time zone,
  "last_used_at" timestamp(3) without time zone,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_ops_data_service_api_key_idx_yak_ops_data_service_key_api" ON "yak_ops_data_service_api_key" ("api_id");

CREATE INDEX "yak_ops_data_service_api_key_idx_yak_ops_data_service__9365f39f" ON "yak_ops_data_service_api_key" ("consumer_id", "enabled");

CREATE INDEX "yak_ops_data_service_api_key_idx_yak_ops_data_service__d0c72b30" ON "yak_ops_data_service_api_key" ("api_id", "enabled");

CREATE INDEX "yak_ops_data_service_api_key_idx_yak_ops_data_service__77dbad17" ON "yak_ops_data_service_api_key" ("expires_at");

CREATE UNIQUE INDEX "yak_ops_data_service_api_key_uk_yak_ops_data_service_key_hash" ON "yak_ops_data_service_api_key" ("key_hash");

CREATE TRIGGER "yak_ops_data_service_api_key_touch" BEFORE UPDATE ON "yak_ops_data_service_api_key" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_ops_data_service_documentation" (
  "api_id" bigint NOT NULL,
  "sql_hash" citext CHECK (length("sql_hash") <= 64),
  "parameter_schema_json" text,
  "response_schema_json" text,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("api_id")
);

CREATE TRIGGER "yak_ops_data_service_documentation_touch" BEFORE UPDATE ON "yak_ops_data_service_documentation" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_ops_data_service_call_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "api_id" bigint NOT NULL,
  "service_name" citext NOT NULL CHECK (length("service_name") <= 128),
  "service_path" citext NOT NULL CHECK (length("service_path") <= 255),
  "caller_type" citext DEFAULT 'LEGACY' NOT NULL CHECK (length("caller_type") <= 32),
  "api_key_id" bigint,
  "consumer_id" bigint,
  "api_key_name" citext CHECK (length("api_key_name") <= 128),
  "api_key_prefix" citext CHECK (length("api_key_prefix") <= 24),
  "source_revision_id" bigint,
  "source_revision_no" integer,
  "params_json" text,
  "success" smallint DEFAULT 0 NOT NULL,
  "duration_ms" bigint DEFAULT 0 NOT NULL,
  "row_count" integer DEFAULT 0 NOT NULL,
  "error_message" citext CHECK (length("error_message") <= 1000),
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_ops_data_service_call_log_idx_data_service_call_lo_779dfe4d" ON "yak_ops_data_service_call_log" ("project_id", "api_id", "source_revision_id", "create_time");

CREATE INDEX "yak_ops_data_service_call_log_idx_data_service_call_lo_27a940cd" ON "yak_ops_data_service_call_log" ("project_id", "consumer_id", "create_time");

CREATE INDEX "yak_ops_data_service_call_log_idx_yak_ops_data_service_log_api" ON "yak_ops_data_service_call_log" ("api_id");

CREATE INDEX "yak_ops_data_service_call_log_idx_yak_ops_data_service_cf557ec9" ON "yak_ops_data_service_call_log" ("api_id", "create_time", "id");

CREATE INDEX "yak_ops_data_service_call_log_idx_yak_ops_data_service_log_key" ON "yak_ops_data_service_call_log" ("api_key_id");

CREATE INDEX "yak_ops_data_service_call_log_idx_yak_ops_data_service_fbef9b1d" ON "yak_ops_data_service_call_log" ("project_id", "api_id", "create_time", "id");

CREATE INDEX "yak_ops_data_service_call_log_idx_yak_ops_data_service_24d0b195" ON "yak_ops_data_service_call_log" ("project_id", "create_time", "id");

CREATE INDEX "yak_ops_data_service_call_log_idx_yak_ops_data_service_693f1a41" ON "yak_ops_data_service_call_log" ("success");

CREATE INDEX "yak_ops_data_service_call_log_idx_yak_ops_data_service_0fc2fe94" ON "yak_ops_data_service_call_log" ("success", "create_time", "id");

CREATE INDEX "yak_ops_data_service_call_log_idx_yak_ops_data_service_log_time" ON "yak_ops_data_service_call_log" ("create_time");

CREATE INDEX "yak_ops_data_service_call_log_idx_yak_ops_data_service_da25bda6" ON "yak_ops_data_service_call_log" ("create_time", "api_id");

CREATE TABLE "yak_ops_data_service_rate_window" (
  "api_key_id" bigint NOT NULL,
  "window_minute" bigint NOT NULL,
  "request_count" integer DEFAULT 0 NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("api_key_id", "window_minute")
);

CREATE INDEX "yak_ops_data_service_rate_window_idx_yak_ops_data_serv_be652f37" ON "yak_ops_data_service_rate_window" ("window_minute");

CREATE TRIGGER "yak_ops_data_service_rate_window_touch" BEFORE UPDATE ON "yak_ops_data_service_rate_window" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_ops_data_service_call_log_hourly" (
  "project_id" bigint NOT NULL,
  "api_id" bigint NOT NULL,
  "bucket_hour" timestamp(0) without time zone NOT NULL,
  "service_name" citext NOT NULL CHECK (length("service_name") <= 256),
  "service_path" citext NOT NULL CHECK (length("service_path") <= 512),
  "total_calls" bigint DEFAULT 0 NOT NULL,
  "success_calls" bigint DEFAULT 0 NOT NULL,
  "failure_calls" bigint DEFAULT 0 NOT NULL,
  "total_duration_ms" bigint DEFAULT 0 NOT NULL,
  "total_rows" bigint DEFAULT 0 NOT NULL,
  "first_call_at" timestamp(3) without time zone,
  "last_call_at" timestamp(3) without time zone,
  "last_success_at" timestamp(3) without time zone,
  "last_failure_at" timestamp(3) without time zone,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("project_id", "api_id", "bucket_hour")
);

CREATE INDEX "yak_ops_data_service_call_log_hourly_idx_yak_ops_data__fee92587" ON "yak_ops_data_service_call_log_hourly" ("project_id", "api_id", "bucket_hour");

CREATE INDEX "yak_ops_data_service_call_log_hourly_idx_yak_ops_data__ee9f5a51" ON "yak_ops_data_service_call_log_hourly" ("project_id", "bucket_hour");

CREATE TRIGGER "yak_ops_data_service_call_log_hourly_touch" BEFORE UPDATE ON "yak_ops_data_service_call_log_hourly" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_ops_data_service_ip_access_policy" (
  "api_id" bigint NOT NULL,
  "mode" citext DEFAULT 'NONE' NOT NULL CHECK (length("mode") <= 16),
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("api_id")
);

CREATE TRIGGER "yak_ops_data_service_ip_access_policy_touch" BEFORE UPDATE ON "yak_ops_data_service_ip_access_policy" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_ops_data_service_ip_access_rule" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "api_id" bigint NOT NULL,
  "rule_type" citext NOT NULL CHECK (length("rule_type") <= 16),
  "network_cidr" citext NOT NULL CHECK (length("network_cidr") <= 80),
  "description" citext CHECK (length("description") <= 255),
  "enabled" smallint DEFAULT 1 NOT NULL,
  "expires_at" timestamp(3) without time zone,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_ops_data_service_ip_access_rule_idx_yak_ops_data_s_8565db74" ON "yak_ops_data_service_ip_access_rule" ("api_id", "rule_type", "enabled", "expires_at");

CREATE UNIQUE INDEX "yak_ops_data_service_ip_access_rule_uk_yak_ops_data_se_c8f6f08c" ON "yak_ops_data_service_ip_access_rule" ("api_id", "rule_type", "network_cidr");

CREATE TRIGGER "yak_ops_data_service_ip_access_rule_touch" BEFORE UPDATE ON "yak_ops_data_service_ip_access_rule" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_ops_data_service_consumer" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "name" citext NOT NULL CHECK (length("name") <= 128),
  "description" citext CHECK (length("description") <= 500),
  "access_scope" citext DEFAULT 'SELECTED' NOT NULL CHECK (length("access_scope") <= 16),
  "enabled" smallint DEFAULT 1 NOT NULL,
  "default_rate_limit_per_minute" integer DEFAULT 60 NOT NULL,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_ops_data_service_consumer_idx_yak_ops_data_service_ddcb0c8d" ON "yak_ops_data_service_consumer" ("project_id", "update_time", "id");

CREATE INDEX "yak_ops_data_service_consumer_idx_yak_ops_data_service_77bfa82a" ON "yak_ops_data_service_consumer" ("project_id", "access_scope", "enabled");

CREATE UNIQUE INDEX "yak_ops_data_service_consumer_uk_yak_ops_data_service__84831744" ON "yak_ops_data_service_consumer" ("project_id", "name");

CREATE TRIGGER "yak_ops_data_service_consumer_touch" BEFORE UPDATE ON "yak_ops_data_service_consumer" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_ops_data_service_consumer_api_grant" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "consumer_id" bigint NOT NULL,
  "api_id" bigint NOT NULL,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_ops_data_service_consumer_api_grant_idx_yak_ops_da_1d1f88cf" ON "yak_ops_data_service_consumer_api_grant" ("api_id", "consumer_id");

CREATE UNIQUE INDEX "yak_ops_data_service_consumer_api_grant_uk_yak_ops_dat_6f43fb17" ON "yak_ops_data_service_consumer_api_grant" ("consumer_id", "api_id");

CREATE TABLE "yak_ops_data_service_consumer_ip_access_policy" (
  "consumer_id" bigint NOT NULL,
  "mode" citext DEFAULT 'NONE' NOT NULL CHECK (length("mode") <= 16),
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("consumer_id")
);

CREATE TRIGGER "yak_ops_data_service_consumer_ip_access_policy_touch" BEFORE UPDATE ON "yak_ops_data_service_consumer_ip_access_policy" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_ops_data_service_consumer_ip_access_rule" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "consumer_id" bigint NOT NULL,
  "rule_type" citext NOT NULL CHECK (length("rule_type") <= 16),
  "network_cidr" citext NOT NULL CHECK (length("network_cidr") <= 80),
  "description" citext CHECK (length("description") <= 255),
  "enabled" smallint DEFAULT 1 NOT NULL,
  "expires_at" timestamp(3) without time zone,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_ops_data_service_consumer_ip_access_rule_idx_yak_o_cd81e36c" ON "yak_ops_data_service_consumer_ip_access_rule" ("consumer_id", "rule_type", "enabled", "expires_at");

CREATE UNIQUE INDEX "yak_ops_data_service_consumer_ip_access_rule_uk_yak_op_251bbde2" ON "yak_ops_data_service_consumer_ip_access_rule" ("consumer_id", "rule_type", "network_cidr");

CREATE TRIGGER "yak_ops_data_service_consumer_ip_access_rule_touch" BEFORE UPDATE ON "yak_ops_data_service_consumer_ip_access_rule" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');
