-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_iso_timestamp(value text) RETURNS timestamp
LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT make_timestamp(substring(value from 1 for 4)::integer,
    substring(value from 6 for 2)::integer, substring(value from 9 for 2)::integer,
    substring(value from 12 for 2)::integer, substring(value from 15 for 2)::integer,
    substring(value from 18)::double precision)
$$;

CREATE TABLE "yak_metadata_asset" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint,
  "project_scope_id" bigint GENERATED ALWAYS AS (COALESCE(project_id, 0)) STORED,
  "asset_key" citext NOT NULL CHECK (length("asset_key") <= 512),
  "asset_type" citext NOT NULL CHECK (length("asset_type") <= 32),
  "name" citext NOT NULL CHECK (length("name") <= 200),
  "source_type" citext DEFAULT '' NOT NULL CHECK (length("source_type") <= 64),
  "source_id" citext DEFAULT '' NOT NULL CHECK (length("source_id") <= 200),
  "parent_asset_id" bigint,
  "data_source_id" citext CHECK (length("data_source_id") <= 64),
  "database_name" citext CHECK (length("database_name") <= 256),
  "schema_name" citext CHECK (length("schema_name") <= 256),
  "table_name" citext CHECK (length("table_name") <= 256),
  "column_name" citext CHECK (length("column_name") <= 256),
  "properties" jsonb,
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  "type_id" bigint,
  "display_name" citext CHECK (length("display_name") <= 256),
  "fully_qualified_name" citext CHECK (length("fully_qualified_name") <= 768),
  "fqn_hash" citext CHECK (length("fqn_hash") <= 32),
  "summary" citext CHECK (length("summary") <= 2048),
  "owner_user" citext CHECK (length("owner_user") <= 64),
  "domain_ids" citext CHECK (length("domain_ids") <= 512),
  "tier_label" citext CHECK (length("tier_label") <= 32),
  "layer_code" citext CHECK (length("layer_code") <= 32),
  "entity_status" citext CHECK (length("entity_status") <= 24),
  "provider_type" citext CHECK (length("provider_type") <= 16),
  "collect_job_id" bigint,
  "content_hash" citext CHECK (length("content_hash") <= 32),
  "source_hash" citext CHECK (length("source_hash") <= 32),
  "source_updated_at" timestamp(6) without time zone,
  "first_seen_at" timestamp(6) without time zone,
  "last_collect_at" timestamp(6) without time zone,
  "last_change_at" timestamp(6) without time zone,
  "gone_at" timestamp(6) without time zone,
  "catalog_version" integer DEFAULT 1 NOT NULL,
  "updated_by" citext DEFAULT 'system' NOT NULL CHECK (length("updated_by") <= 64),
  "md_attributes" jsonb,
  "s_str_1" citext GENERATED ALWAYS AS (("md_attributes"::jsonb ->> 's_str_1')::citext) STORED CHECK (length("s_str_1") <= 256),
  "s_str_2" citext GENERATED ALWAYS AS (("md_attributes"::jsonb ->> 's_str_2')::citext) STORED CHECK (length("s_str_2") <= 256),
  "s_str_3" citext GENERATED ALWAYS AS (("md_attributes"::jsonb ->> 's_str_3')::citext) STORED CHECK (length("s_str_3") <= 256),
  "s_num_1" bigint GENERATED ALWAYS AS (("md_attributes"::jsonb ->> 's_num_1')::bigint) STORED,
  "s_num_2" bigint GENERATED ALWAYS AS (("md_attributes"::jsonb ->> 's_num_2')::bigint) STORED,
  "s_bool_1" smallint GENERATED ALWAYS AS (CASE ("md_attributes"::jsonb ->> 's_bool_1') WHEN 'true' THEN 1 WHEN 'false' THEN 0 ELSE ("md_attributes"::jsonb ->> 's_bool_1')::smallint END) STORED,
  "s_date_1" timestamp(6) without time zone GENERATED ALWAYS AS (yak_iso_timestamp(("md_attributes"::jsonb ->> 's_date_1'))) STORED,
  PRIMARY KEY ("id")
);

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX yak_metadata_asset_name_search ON yak_metadata_asset USING gin ((name::text) gin_trgm_ops);
CREATE INDEX yak_metadata_asset_display_name_search ON yak_metadata_asset USING gin ((display_name::text) gin_trgm_ops);
CREATE INDEX yak_metadata_asset_summary_search ON yak_metadata_asset USING gin (summary gin_trgm_ops);

CREATE INDEX "yak_metadata_asset_idx_yak_md_asset_collect" ON "yak_metadata_asset" ("project_id", "provider_type", "last_collect_at");

CREATE INDEX "yak_metadata_asset_idx_yak_md_asset_domain" ON "yak_metadata_asset" ("project_id", left("domain_ids", 64));

CREATE INDEX "yak_metadata_asset_idx_yak_md_asset_fqn" ON "yak_metadata_asset" ("fqn_hash");

CREATE INDEX "yak_metadata_asset_idx_yak_md_asset_slot_num" ON "yak_metadata_asset" ("s_num_1");

CREATE INDEX "yak_metadata_asset_idx_yak_md_asset_slot_str" ON "yak_metadata_asset" ("s_str_1");

CREATE INDEX "yak_metadata_asset_idx_yak_md_asset_status" ON "yak_metadata_asset" ("project_id", "entity_status");

CREATE INDEX "yak_metadata_asset_idx_yak_md_asset_type" ON "yak_metadata_asset" ("project_id", "type_id", "gone_at");

CREATE INDEX "yak_metadata_asset_idx_yak_metadata_asset_datasource" ON "yak_metadata_asset" ("data_source_id");

CREATE INDEX "yak_metadata_asset_idx_yak_metadata_asset_parent" ON "yak_metadata_asset" ("parent_asset_id");

CREATE INDEX "yak_metadata_asset_idx_yak_metadata_asset_project_source" ON "yak_metadata_asset" ("project_id", "source_type", "source_id");

CREATE INDEX "yak_metadata_asset_idx_yak_metadata_asset_project_type" ON "yak_metadata_asset" ("project_id", "asset_type", "update_time");

CREATE INDEX "yak_metadata_asset_idx_yak_metadata_asset_source" ON "yak_metadata_asset" ("source_type", "source_id");

CREATE INDEX "yak_metadata_asset_idx_yak_metadata_asset_type" ON "yak_metadata_asset" ("asset_type");

CREATE UNIQUE INDEX "yak_metadata_asset_uk_yak_metadata_asset_project_key" ON "yak_metadata_asset" ("project_scope_id", "asset_key");

CREATE TABLE "yak_metadata_relation" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint,
  "source_asset_id" bigint NOT NULL,
  "target_asset_id" bigint NOT NULL,
  "relation_type" citext NOT NULL CHECK (length("relation_type") <= 32),
  "source_type" citext DEFAULT '' NOT NULL CHECK (length("source_type") <= 64),
  "source_id" citext DEFAULT '' NOT NULL CHECK (length("source_id") <= 200),
  "expression" text,
  "confidence" decimal(5,4) DEFAULT 1.0000 NOT NULL,
  "version" citext DEFAULT '' NOT NULL CHECK (length("version") <= 128),
  "observed_at" timestamp(6) without time zone NOT NULL,
  "properties" jsonb,
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_metadata_relation_idx_yak_metadata_relation_evidence" ON "yak_metadata_relation" ("source_type", "source_id");

CREATE INDEX "yak_metadata_relation_idx_yak_metadata_relation_projec_ad5cc44c" ON "yak_metadata_relation" ("project_id", "source_type", "source_id");

CREATE INDEX "yak_metadata_relation_idx_yak_metadata_relation_project_source" ON "yak_metadata_relation" ("project_id", "source_asset_id", "relation_type");

CREATE INDEX "yak_metadata_relation_idx_yak_metadata_relation_project_target" ON "yak_metadata_relation" ("project_id", "target_asset_id", "relation_type");

CREATE INDEX "yak_metadata_relation_idx_yak_metadata_relation_source" ON "yak_metadata_relation" ("source_asset_id", "relation_type");

CREATE INDEX "yak_metadata_relation_idx_yak_metadata_relation_target" ON "yak_metadata_relation" ("target_asset_id", "relation_type");

CREATE UNIQUE INDEX "yak_metadata_relation_uk_yak_metadata_relation_identity" ON "yak_metadata_relation" ("source_asset_id", "target_asset_id", "relation_type", "source_type", "source_id", "version");
