-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_quality_template_folder" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "parent_id" bigint,
  "folder_name" citext NOT NULL CHECK (length("folder_name") <= 100),
  "sort_order" integer DEFAULT 0 NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  "created_by" citext DEFAULT 'system' NOT NULL CHECK (length("created_by") <= 128),
  "updated_by" citext DEFAULT 'system' NOT NULL CHECK (length("updated_by") <= 128),
  "created_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "updated_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_quality_template_folder_idx_yak_quality_template_f_90765773" ON "yak_quality_template_folder" ("folder_name", "deleted");

CREATE INDEX "yak_quality_template_folder_idx_yak_quality_template_f_dd8a42bb" ON "yak_quality_template_folder" ("parent_id", "deleted", "sort_order");

CREATE TRIGGER "yak_quality_template_folder_touch" BEFORE UPDATE ON "yak_quality_template_folder" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('updated_at');

CREATE TABLE "yak_quality_rule_template" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "template_code" citext NOT NULL CHECK (length("template_code") <= 64),
  "template_name" citext NOT NULL CHECK (length("template_name") <= 100),
  "description" citext CHECK (length("description") <= 500),
  "rule_type" citext NOT NULL CHECK (length("rule_type") <= 40),
  "rule_scope" citext NOT NULL CHECK (length("rule_scope") <= 20),
  "quality_dimension" citext NOT NULL CHECK (length("quality_dimension") <= 40),
  "parameter_schema_json" text NOT NULL,
  "builtin" smallint DEFAULT 1 NOT NULL,
  "enabled" smallint DEFAULT 1 NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "folder_id" bigint,
  "template_sql" text,
  "set_flag" citext CHECK (length("set_flag") <= 1000),
  "check_type" citext DEFAULT 'NUMERIC' NOT NULL CHECK (length("check_type") <= 32),
  "check_method" citext DEFAULT 'FIXED_VALUE' NOT NULL CHECK (length("check_method") <= 64),
  "created_by" citext DEFAULT 'system' NOT NULL CHECK (length("created_by") <= 128),
  "deleted" smallint DEFAULT 0 NOT NULL,
  "created_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "updated_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_quality_rule_template_idx_yak_quality_template_dimension" ON "yak_quality_rule_template" ("quality_dimension", "enabled");

CREATE INDEX "yak_quality_rule_template_idx_yak_quality_template_folder" ON "yak_quality_rule_template" ("folder_id", "builtin", "deleted", "enabled");

CREATE INDEX "yak_quality_rule_template_idx_yak_quality_template_source" ON "yak_quality_rule_template" ("builtin", "deleted", "enabled", "sort_order");

CREATE UNIQUE INDEX "yak_quality_rule_template_uk_yak_quality_template_code" ON "yak_quality_rule_template" ("template_code");

CREATE TRIGGER "yak_quality_rule_template_touch" BEFORE UPDATE ON "yak_quality_rule_template" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('updated_at');

INSERT INTO "yak_quality_rule_template" ("id", "template_code", "template_name", "description", "rule_type", "rule_scope", "quality_dimension", "parameter_schema_json", "builtin", "enabled", "sort_order", "folder_id", "template_sql", "set_flag", "check_type", "check_method", "created_by", "deleted") VALUES ('1', 'TABLE_ROW_COUNT', '表行数', '统计目标数据范围的总行数，并与阈值进行比较。', 'TABLE_ROW_COUNT', 'TABLE', '完整性', '{"fields":["operator","threshold"],"defaultOperator":"GT","defaultThreshold":0}', '1', '1', '10', NULL, NULL, NULL, 'NUMERIC', 'FIXED_VALUE', 'system', '0');

INSERT INTO "yak_quality_rule_template" ("id", "template_code", "template_name", "description", "rule_type", "rule_scope", "quality_dimension", "parameter_schema_json", "builtin", "enabled", "sort_order", "folder_id", "template_sql", "set_flag", "check_type", "check_method", "created_by", "deleted") VALUES ('2', 'COLUMN_NOT_NULL', '字段非空', '统计字段非空率，空表按 100% 处理。', 'COLUMN_NOT_NULL', 'COLUMN', '完整性', '{"fields":["columnName","operator","threshold"],"defaultOperator":"GTE","defaultThreshold":100}', '1', '1', '20', NULL, NULL, NULL, 'NUMERIC', 'FIXED_VALUE', 'system', '0');

INSERT INTO "yak_quality_rule_template" ("id", "template_code", "template_name", "description", "rule_type", "rule_scope", "quality_dimension", "parameter_schema_json", "builtin", "enabled", "sort_order", "folder_id", "template_sql", "set_flag", "check_type", "check_method", "created_by", "deleted") VALUES ('3', 'COLUMN_UNIQUE', '字段唯一', '统计字段非空值中的唯一率。', 'COLUMN_UNIQUE', 'COLUMN', '唯一性', '{"fields":["columnName","operator","threshold"],"defaultOperator":"GTE","defaultThreshold":100}', '1', '1', '30', NULL, NULL, NULL, 'NUMERIC', 'FIXED_VALUE', 'system', '0');

INSERT INTO "yak_quality_rule_template" ("id", "template_code", "template_name", "description", "rule_type", "rule_scope", "quality_dimension", "parameter_schema_json", "builtin", "enabled", "sort_order", "folder_id", "template_sql", "set_flag", "check_type", "check_method", "created_by", "deleted") VALUES ('4', 'COLUMN_RANGE', '字段数值范围', '检查字段值是否都位于指定的最小值和最大值之间。', 'COLUMN_RANGE', 'COLUMN', '有效性', '{"fields":["columnName","threshold","thresholdEnd"],"thresholdLabel":"最小值","thresholdEndLabel":"最大值"}', '1', '1', '40', NULL, NULL, NULL, 'NUMERIC', 'FIXED_VALUE', 'system', '0');

INSERT INTO "yak_quality_rule_template" ("id", "template_code", "template_name", "description", "rule_type", "rule_scope", "quality_dimension", "parameter_schema_json", "builtin", "enabled", "sort_order", "folder_id", "template_sql", "set_flag", "check_type", "check_method", "created_by", "deleted") VALUES ('5', 'COLUMN_ENUM', '字段枚举值', '检查字段非空值是否都包含在允许的枚举集合内。', 'COLUMN_ENUM', 'COLUMN', '准确性', '{"fields":["columnName","enumValues"]}', '1', '1', '50', NULL, NULL, NULL, 'NUMERIC', 'FIXED_VALUE', 'system', '0');

INSERT INTO "yak_quality_rule_template" ("id", "template_code", "template_name", "description", "rule_type", "rule_scope", "quality_dimension", "parameter_schema_json", "builtin", "enabled", "sort_order", "folder_id", "template_sql", "set_flag", "check_type", "check_method", "created_by", "deleted") VALUES ('6', 'CUSTOM_SQL', '自定义 SQL', '执行只读 SELECT，并使用首行首列作为质量指标。支持 ${table}、${column} 和 ${where}。', 'CUSTOM_SQL', 'TABLE', '自定义', '{"fields":["customSql","operator","threshold"],"defaultOperator":"EQ","defaultThreshold":0}', '1', '1', '60', NULL, NULL, NULL, 'NUMERIC', 'FIXED_VALUE', 'system', '0');

SELECT setval(pg_get_serial_sequence('yak_quality_rule_template', 'id'), (SELECT MAX("id") FROM "yak_quality_rule_template"));

CREATE TABLE "yak_quality_table_asset" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "data_source_id" bigint NOT NULL,
  "data_source_name" citext NOT NULL CHECK (length("data_source_name") <= 128),
  "database_name" citext DEFAULT '' NOT NULL CHECK (length("database_name") <= 128),
  "schema_name" citext DEFAULT '' NOT NULL CHECK (length("schema_name") <= 128),
  "table_name" citext NOT NULL CHECK (length("table_name") <= 256),
  "table_type" citext CHECK (length("table_type") <= 40),
  "remarks" citext CHECK (length("remarks") <= 1000),
  "registered_by" citext DEFAULT 'system' NOT NULL CHECK (length("registered_by") <= 128),
  "registered_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  "created_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "updated_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_quality_table_asset_idx_yak_quality_table_asset_query" ON "yak_quality_table_asset" ("project_id", "data_source_id", "database_name", "deleted", "table_name");

CREATE UNIQUE INDEX "yak_quality_table_asset_uk_yak_quality_table_asset_target" ON "yak_quality_table_asset" ("project_id", "data_source_id", "database_name", "schema_name", "table_name");

CREATE TRIGGER "yak_quality_table_asset_touch" BEFORE UPDATE ON "yak_quality_table_asset" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('updated_at');

CREATE TABLE "yak_quality_monitor" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "monitor_name" citext NOT NULL CHECK (length("monitor_name") <= 100),
  "description" citext CHECK (length("description") <= 500),
  "data_source_id" bigint NOT NULL,
  "data_source_name" citext NOT NULL CHECK (length("data_source_name") <= 128),
  "database_name" citext CHECK (length("database_name") <= 128),
  "schema_name" citext CHECK (length("schema_name") <= 128),
  "table_name" citext NOT NULL CHECK (length("table_name") <= 256),
  "where_clause" text,
  "owner" citext NOT NULL CHECK (length("owner") <= 128),
  "enabled" smallint DEFAULT 1 NOT NULL,
  "last_result" citext DEFAULT 'NOT_RUN' NOT NULL CHECK (length("last_result") <= 20),
  "last_execution_no" citext CHECK (length("last_execution_no") <= 64),
  "last_run_time" timestamp(3) without time zone,
  "deleted" smallint DEFAULT 0 NOT NULL,
  "created_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "updated_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_quality_monitor_idx_yak_quality_monitor_result" ON "yak_quality_monitor" ("project_id", "last_result", "deleted");

CREATE INDEX "yak_quality_monitor_idx_yak_quality_monitor_target" ON "yak_quality_monitor" ("project_id", "data_source_id", "database_name", "schema_name", "table_name", "deleted");

CREATE INDEX "yak_quality_monitor_idx_yak_quality_monitor_updated" ON "yak_quality_monitor" ("project_id", "updated_at", "id");

CREATE TRIGGER "yak_quality_monitor_touch" BEFORE UPDATE ON "yak_quality_monitor" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('updated_at');

CREATE TABLE "yak_quality_monitor_setting" (
  "monitor_id" bigint NOT NULL,
  "run_mode" citext DEFAULT 'MANUAL' NOT NULL CHECK (length("run_mode") <= 20),
  "schedule_frequency" citext CHECK (length("schedule_frequency") <= 20),
  "schedule_time" time,
  "schedule_weekday" citext CHECK (length("schedule_weekday") <= 3),
  "cron_expression" citext CHECK (length("cron_expression") <= 128),
  "next_run_time" timestamp(3) without time zone,
  "rule_failure_action" citext DEFAULT 'CONTINUE' NOT NULL CHECK (length("rule_failure_action") <= 20),
  "notify_enabled" smallint DEFAULT 0 NOT NULL,
  "notify_channel" citext DEFAULT 'MESSAGE' CHECK (length("notify_channel") <= 20),
  "notify_target" citext CHECK (length("notify_target") <= 1000),
  "alert_level" citext DEFAULT 'WARNING' NOT NULL CHECK (length("alert_level") <= 20),
  "created_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "updated_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("monitor_id")
);

CREATE INDEX "yak_quality_monitor_setting_idx_yak_quality_setting_due" ON "yak_quality_monitor_setting" ("run_mode", "next_run_time");

CREATE TRIGGER "yak_quality_monitor_setting_touch" BEFORE UPDATE ON "yak_quality_monitor_setting" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('updated_at');

CREATE TABLE "yak_quality_rule" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "monitor_id" bigint NOT NULL,
  "template_id" bigint NOT NULL,
  "template_code" citext NOT NULL CHECK (length("template_code") <= 64),
  "rule_name" citext NOT NULL CHECK (length("rule_name") <= 100),
  "rule_type" citext NOT NULL CHECK (length("rule_type") <= 40),
  "rule_scope" citext NOT NULL CHECK (length("rule_scope") <= 20),
  "quality_dimension" citext NOT NULL CHECK (length("quality_dimension") <= 40),
  "column_name" citext CHECK (length("column_name") <= 256),
  "comparison_operator" citext NOT NULL CHECK (length("comparison_operator") <= 20),
  "threshold_value" decimal(30,10),
  "threshold_end" decimal(30,10),
  "enum_values_json" text,
  "custom_sql" text,
  "enabled" smallint DEFAULT 1 NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  "created_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "updated_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_quality_rule_idx_yak_quality_rule_monitor" ON "yak_quality_rule" ("monitor_id", "deleted", "sort_order");

CREATE INDEX "yak_quality_rule_idx_yak_quality_rule_template" ON "yak_quality_rule" ("template_id", "deleted");

CREATE TRIGGER "yak_quality_rule_touch" BEFORE UPDATE ON "yak_quality_rule" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('updated_at');

CREATE TABLE "yak_quality_execution" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "execution_no" citext NOT NULL CHECK (length("execution_no") <= 64),
  "idempotency_key" citext CHECK (length("idempotency_key") <= 255),
  "monitor_id" bigint NOT NULL,
  "monitor_name" citext NOT NULL CHECK (length("monitor_name") <= 100),
  "data_source_id" bigint NOT NULL,
  "data_source_name" citext NOT NULL CHECK (length("data_source_name") <= 128),
  "database_name" citext CHECK (length("database_name") <= 128),
  "schema_name" citext CHECK (length("schema_name") <= 128),
  "table_name" citext NOT NULL CHECK (length("table_name") <= 256),
  "object_name" citext NOT NULL CHECK (length("object_name") <= 768),
  "trigger_type" citext DEFAULT 'MANUAL' NOT NULL CHECK (length("trigger_type") <= 20),
  "execution_status" citext DEFAULT 'WAITING' NOT NULL CHECK (length("execution_status") <= 20),
  "check_result" citext DEFAULT 'RUNNING' NOT NULL CHECK (length("check_result") <= 20),
  "total_rules" integer DEFAULT 0 NOT NULL,
  "passed_rules" integer DEFAULT 0 NOT NULL,
  "failed_rules" integer DEFAULT 0 NOT NULL,
  "error_rules" integer DEFAULT 0 NOT NULL,
  "operator_name" citext NOT NULL CHECK (length("operator_name") <= 128),
  "queued_at" timestamp(3) without time zone NOT NULL,
  "started_at" timestamp(3) without time zone,
  "finished_at" timestamp(3) without time zone,
  "duration_ms" bigint,
  "error_message" citext CHECK (length("error_message") <= 1000),
  "created_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "updated_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_quality_execution_idx_yak_quality_execution_monitor" ON "yak_quality_execution" ("project_id", "monitor_id", "created_at");

CREATE INDEX "yak_quality_execution_idx_yak_quality_execution_queued" ON "yak_quality_execution" ("project_id", "queued_at", "id");

CREATE INDEX "yak_quality_execution_idx_yak_quality_execution_result" ON "yak_quality_execution" ("project_id", "check_result", "created_at");

CREATE INDEX "yak_quality_execution_idx_yak_quality_execution_status" ON "yak_quality_execution" ("project_id", "execution_status", "created_at");

CREATE UNIQUE INDEX "yak_quality_execution_uk_yak_quality_execution_idempotency" ON "yak_quality_execution" ("project_id", "idempotency_key");

CREATE UNIQUE INDEX "yak_quality_execution_uk_yak_quality_execution_no" ON "yak_quality_execution" ("execution_no");

CREATE TRIGGER "yak_quality_execution_touch" BEFORE UPDATE ON "yak_quality_execution" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('updated_at');

CREATE TABLE "yak_quality_rule_execution" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "execution_id" bigint NOT NULL,
  "rule_id" bigint NOT NULL,
  "rule_name" citext NOT NULL CHECK (length("rule_name") <= 100),
  "template_code" citext NOT NULL CHECK (length("template_code") <= 64),
  "rule_type" citext NOT NULL CHECK (length("rule_type") <= 40),
  "column_name" citext CHECK (length("column_name") <= 256),
  "check_result" citext NOT NULL CHECK (length("check_result") <= 20),
  "metric_value" citext CHECK (length("metric_value") <= 256),
  "expected_value" citext CHECK (length("expected_value") <= 500),
  "executed_sql" text,
  "error_message" citext CHECK (length("error_message") <= 1000),
  "duration_ms" bigint,
  "created_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_quality_rule_execution_idx_yak_quality_rule_execut_45d7ddd3" ON "yak_quality_rule_execution" ("execution_id", "id");

CREATE INDEX "yak_quality_rule_execution_idx_yak_quality_rule_execution_rule" ON "yak_quality_rule_execution" ("rule_id", "created_at");

CREATE TABLE "yak_quality_alert_event" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "monitor_id" bigint NOT NULL,
  "execution_no" citext NOT NULL CHECK (length("execution_no") <= 64),
  "check_result" citext NOT NULL CHECK (length("check_result") <= 20),
  "alert_level" citext NOT NULL CHECK (length("alert_level") <= 20),
  "notify_channel" citext NOT NULL CHECK (length("notify_channel") <= 20),
  "notify_target" citext CHECK (length("notify_target") <= 1000),
  "delivery_status" citext DEFAULT 'RECORDED' NOT NULL CHECK (length("delivery_status") <= 20),
  "alert_message" citext NOT NULL CHECK (length("alert_message") <= 1000),
  "error_message" citext CHECK (length("error_message") <= 1000),
  "created_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "delivered_at" timestamp(3) without time zone,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_quality_alert_event_idx_yak_quality_alert_execution" ON "yak_quality_alert_event" ("execution_no");

CREATE INDEX "yak_quality_alert_event_idx_yak_quality_alert_monitor" ON "yak_quality_alert_event" ("monitor_id", "created_at");

CREATE INDEX "yak_quality_alert_event_idx_yak_quality_alert_status" ON "yak_quality_alert_event" ("delivery_status", "created_at");

CREATE TABLE "yak_quality_monitor_revision" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "monitor_id" bigint NOT NULL,
  "revision_no" integer NOT NULL,
  "monitor_name" citext NOT NULL CHECK (length("monitor_name") <= 100),
  "definition_json" text NOT NULL,
  "checksum" citext NOT NULL CHECK (length("checksum") <= 64),
  "created_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_quality_monitor_revision_idx_yak_quality_monitor_r_80252cc6" ON "yak_quality_monitor_revision" ("project_id", "monitor_id", "checksum");

CREATE INDEX "yak_quality_monitor_revision_idx_yak_quality_monitor_r_7decc27e" ON "yak_quality_monitor_revision" ("project_id", "monitor_id", "revision_no");

CREATE UNIQUE INDEX "yak_quality_monitor_revision_uk_yak_quality_monitor_revision_no" ON "yak_quality_monitor_revision" ("project_id", "monitor_id", "revision_no");
