-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_agent_session" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "session_id" citext NOT NULL CHECK (length("session_id") <= 64),
  "user_id" bigint NOT NULL,
  "project_id" bigint DEFAULT 0 NOT NULL,
  "title" citext CHECK (length("title") <= 200),
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_agent_session_idx_agent_session_project" ON "yak_agent_session" ("project_id", "update_time");

CREATE INDEX "yak_agent_session_idx_agent_session_user" ON "yak_agent_session" ("user_id", "update_time");

CREATE UNIQUE INDEX "yak_agent_session_uk_agent_session_id" ON "yak_agent_session" ("session_id");

CREATE TRIGGER "yak_agent_session_touch" BEFORE UPDATE ON "yak_agent_session" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_agent_report" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "session_id" citext NOT NULL CHECK (length("session_id") <= 64),
  "user_id" bigint NOT NULL,
  "project_id" bigint DEFAULT 0 NOT NULL,
  "title" citext NOT NULL CHECK (length("title") <= 500),
  "content" text NOT NULL,
  "is_deleted" smallint DEFAULT 0 NOT NULL,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_agent_report_idx_agent_report_project" ON "yak_agent_report" ("project_id", "is_deleted", "id");

CREATE INDEX "yak_agent_report_idx_agent_report_session" ON "yak_agent_report" ("session_id");

CREATE INDEX "yak_agent_report_idx_agent_report_user" ON "yak_agent_report" ("user_id", "is_deleted", "id");

CREATE TRIGGER "yak_agent_report_touch" BEFORE UPDATE ON "yak_agent_report" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_agent_query_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint DEFAULT 0 NOT NULL,
  "user_id" bigint DEFAULT 0 NOT NULL,
  "session_id" citext NOT NULL CHECK (length("session_id") <= 64),
  "dataset_id" bigint NOT NULL,
  "query_id" citext CHECK (length("query_id") <= 64),
  "request_json" text,
  "status" citext NOT NULL CHECK (length("status") <= 20),
  "error_message" citext CHECK (length("error_message") <= 1000),
  "returned_rows" integer,
  "truncated" smallint,
  "elapsed_millis" bigint,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_agent_query_log_idx_agent_query_log_dataset" ON "yak_agent_query_log" ("dataset_id", "id");

CREATE INDEX "yak_agent_query_log_idx_agent_query_log_project" ON "yak_agent_query_log" ("project_id", "user_id", "id");

CREATE INDEX "yak_agent_query_log_idx_agent_query_log_session" ON "yak_agent_query_log" ("session_id", "id");

CREATE TABLE "yak_agent_step" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "session_id" citext NOT NULL CHECK (length("session_id") <= 64),
  "turn_id" citext CHECK (length("turn_id") <= 64),
  "parent_step_id" bigint,
  "kind" citext NOT NULL CHECK (length("kind") <= 24),
  "name" citext NOT NULL CHECK (length("name") <= 128),
  "tool_call_id" citext CHECK (length("tool_call_id") <= 64),
  "status" citext NOT NULL CHECK (length("status") <= 16),
  "request_json" text,
  "response_json" text,
  "error_code" citext CHECK (length("error_code") <= 48),
  "error_message" citext CHECK (length("error_message") <= 1000),
  "stats_json" jsonb,
  "started_at" timestamp(3) without time zone,
  "ended_at" timestamp(3) without time zone,
  "attempt" integer,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_agent_step_idx_agent_step_kind_status" ON "yak_agent_step" ("kind", "status", "id");

CREATE INDEX "yak_agent_step_idx_agent_step_session" ON "yak_agent_step" ("session_id", "id");

CREATE INDEX "yak_agent_step_idx_agent_step_tool_call" ON "yak_agent_step" ("tool_call_id");

CREATE INDEX "yak_agent_step_idx_agent_step_turn" ON "yak_agent_step" ("turn_id", "id");

CREATE INDEX "yak_agent_step_idx_agent_step_turn_kind" ON "yak_agent_step" ("turn_id", "kind", "id");

CREATE TABLE "yak_agent_message" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "session_id" citext NOT NULL CHECK (length("session_id") <= 64),
  "message_id" citext NOT NULL CHECK (length("message_id") <= 64),
  "parent_id" citext CHECK (length("parent_id") <= 64),
  "role" citext NOT NULL CHECK (length("role") <= 16),
  "content" text,
  "model_name" citext CHECK (length("model_name") <= 128),
  "total_tokens" bigint,
  "done" smallint DEFAULT 1 NOT NULL,
  "is_deleted" smallint DEFAULT 0 NOT NULL,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_agent_message_idx_agent_msg_parent" ON "yak_agent_message" ("session_id", "parent_id");

CREATE INDEX "yak_agent_message_idx_agent_msg_session_ct" ON "yak_agent_message" ("session_id", "create_time");

CREATE UNIQUE INDEX "yak_agent_message_uk_agent_msg" ON "yak_agent_message" ("session_id", "message_id");

CREATE TRIGGER "yak_agent_message_touch" BEFORE UPDATE ON "yak_agent_message" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_agent_turn" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "turn_id" citext NOT NULL CHECK (length("turn_id") <= 64),
  "session_id" citext NOT NULL CHECK (length("session_id") <= 64),
  "user_id" bigint NOT NULL,
  "kind" citext NOT NULL CHECK (length("kind") <= 16),
  "payload_json" text,
  "status" citext NOT NULL CHECK (length("status") <= 24),
  "error_code" citext CHECK (length("error_code") <= 48),
  "error_message" citext CHECK (length("error_message") <= 1000),
  "project_id" bigint DEFAULT 0 NOT NULL,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "start_time" timestamp(3) without time zone,
  "end_time" timestamp(3) without time zone,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_agent_turn_idx_agent_turn_project" ON "yak_agent_turn" ("project_id", "id");

CREATE INDEX "yak_agent_turn_idx_agent_turn_session" ON "yak_agent_turn" ("session_id", "id");

CREATE INDEX "yak_agent_turn_idx_agent_turn_status" ON "yak_agent_turn" ("status", "id");

CREATE UNIQUE INDEX "yak_agent_turn_uk_agent_turn_id" ON "yak_agent_turn" ("turn_id");

CREATE TABLE "yak_agent_turn_event" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "turn_id" citext NOT NULL CHECK (length("turn_id") <= 64),
  "event_type" citext NOT NULL CHECK (length("event_type") <= 32),
  "payload_json" text,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_agent_turn_event_idx_turn_event_cursor" ON "yak_agent_turn_event" ("turn_id", "id");

CREATE TABLE "yak_agent_memory" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "scope" citext NOT NULL CHECK (length("scope") <= 16),
  "scope_key" citext NOT NULL CHECK (length("scope_key") <= 64),
  "memory_type" citext NOT NULL CHECK (length("memory_type") <= 16),
  "layer" citext DEFAULT 'LEDGER' NOT NULL CHECK (length("layer") <= 8),
  "content" citext NOT NULL CHECK (length("content") <= 2000),
  "keywords" citext CHECK (length("keywords") <= 255),
  "confidence" decimal(3,2) DEFAULT 0.60 NOT NULL,
  "hit_count" integer DEFAULT 0 NOT NULL,
  "last_hit_at" timestamp(3) without time zone,
  "source_turn_id" citext CHECK (length("source_turn_id") <= 64),
  "source_session" citext CHECK (length("source_session") <= 64),
  "status" citext DEFAULT 'ACTIVE' NOT NULL CHECK (length("status") <= 16),
  "merged_into" bigint,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_agent_memory_idx_agent_memory_scope" ON "yak_agent_memory" ("scope", "scope_key", "status", "memory_type");

CREATE INDEX "yak_agent_memory_idx_agent_memory_turn" ON "yak_agent_memory" ("source_turn_id");

CREATE TRIGGER "yak_agent_memory_touch" BEFORE UPDATE ON "yak_agent_memory" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_config" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "config_key" citext NOT NULL CHECK (length("config_key") <= 128),
  "config_value" citext NOT NULL CHECK (length("config_value") <= 512),
  "description" citext CHECK (length("description") <= 255),
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_config_uk_config_key" ON "yak_config" ("config_key");

CREATE TRIGGER "yak_config_touch" BEFORE UPDATE ON "yak_config" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_agent_skill" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "skill_id" citext NOT NULL CHECK (length("skill_id") <= 64),
  "project_id" bigint DEFAULT 0 NOT NULL,
  "name" citext NOT NULL CHECK (length("name") <= 128),
  "description" citext NOT NULL CHECK (length("description") <= 512),
  "metadata_json" text,
  "content" text NOT NULL,
  "status" citext DEFAULT 'ENABLED' NOT NULL CHECK (length("status") <= 16),
  "version" integer DEFAULT 1 NOT NULL,
  "created_at" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updated_at" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_agent_skill_idx_agent_skill_project" ON "yak_agent_skill" ("project_id");

CREATE UNIQUE INDEX "yak_agent_skill_uk_skill_id" ON "yak_agent_skill" ("skill_id");

CREATE TRIGGER "yak_agent_skill_touch" BEFORE UPDATE ON "yak_agent_skill" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('updated_at');
