-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_metric" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "metric_code" citext NOT NULL CHECK (length("metric_code") <= 64),
  "metric_name" citext NOT NULL CHECK (length("metric_name") <= 128),
  "domain_id" bigint,
  "process_id" bigint,
  "metric_type" citext NOT NULL CHECK (length("metric_type") <= 16),
  "caliber_id" bigint,
  "cal_rule" citext CHECK (length("cal_rule") <= 1024),
  "measure_expr" citext CHECK (length("measure_expr") <= 512),
  "filter_expr" citext CHECK (length("filter_expr") <= 1024),
  "dim_model_ids" jsonb,
  "ref_metric_id" bigint,
  "dim_constraint" citext CHECK (length("dim_constraint") <= 1024),
  "qualifiers_json" jsonb,
  "model_id" bigint,
  "stat_dimensions" jsonb,
  "stat_period" citext DEFAULT 'DAY' NOT NULL CHECK (length("stat_period") <= 16),
  "unit_id" bigint,
  "business_desc" citext CHECK (length("business_desc") <= 512),
  "owner" citext CHECK (length("owner") <= 64),
  "status" citext DEFAULT 'ENABLED' NOT NULL CHECK (length("status") <= 16),
  "version" integer DEFAULT 1 NOT NULL,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "updated_by" citext CHECK (length("updated_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_metric_idx_yak_metric_domain" ON "yak_metric" ("project_id", "domain_id");

CREATE INDEX "yak_metric_idx_yak_metric_status" ON "yak_metric" ("project_id", "status");

CREATE INDEX "yak_metric_idx_yak_metric_type" ON "yak_metric" ("project_id", "metric_type");

CREATE UNIQUE INDEX "yak_metric_uk_yak_metric_code" ON "yak_metric" ("project_id", "metric_code");

CREATE TRIGGER "yak_metric_touch" BEFORE UPDATE ON "yak_metric" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_metric_tag" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "tag_code" citext NOT NULL CHECK (length("tag_code") <= 64),
  "tag_name" citext NOT NULL CHECK (length("tag_name") <= 128),
  "sort_order" integer DEFAULT 0 NOT NULL,
  "status" citext DEFAULT 'ENABLED' NOT NULL CHECK (length("status") <= 16),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "updated_by" citext CHECK (length("updated_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_metric_tag_uk_yak_metric_tag_code" ON "yak_metric_tag" ("project_id", "tag_code");

CREATE TRIGGER "yak_metric_tag_touch" BEFORE UPDATE ON "yak_metric_tag" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_metric_tag_rel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "metric_id" bigint NOT NULL,
  "tag_id" bigint NOT NULL,
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_metric_tag_rel_idx_yak_metric_tag_rel_tag" ON "yak_metric_tag_rel" ("project_id", "tag_id");

CREATE UNIQUE INDEX "yak_metric_tag_rel_uk_yak_metric_tag_rel" ON "yak_metric_tag_rel" ("project_id", "metric_id", "tag_id");

CREATE TABLE "yak_metric_version" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "metric_id" bigint NOT NULL,
  "version" integer NOT NULL,
  "snapshot" jsonb NOT NULL,
  "change_desc" citext CHECK (length("change_desc") <= 512),
  "changed_by" citext NOT NULL CHECK (length("changed_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_metric_version_idx_yak_metric_version_metric" ON "yak_metric_version" ("project_id", "metric_id");

CREATE UNIQUE INDEX "yak_metric_version_uk_yak_metric_version" ON "yak_metric_version" ("metric_id", "version");

CREATE TABLE "yak_metric_dependency" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "metric_id" bigint NOT NULL,
  "dependency_type" citext NOT NULL CHECK (length("dependency_type") <= 16),
  "dependency_id" bigint NOT NULL,
  "dependency_code" citext CHECK (length("dependency_code") <= 64),
  "dependency_version" integer,
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_metric_dependency_idx_yak_metric_dep_metric" ON "yak_metric_dependency" ("project_id", "metric_id");

CREATE INDEX "yak_metric_dependency_idx_yak_metric_dep_target" ON "yak_metric_dependency" ("dependency_type", "dependency_id");

CREATE TABLE "yak_metric_composition" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "metric_id" bigint NOT NULL,
  "sub_metric_id" bigint NOT NULL,
  "operator" citext NOT NULL CHECK (length("operator") <= 8),
  "expression" citext CHECK (length("expression") <= 512),
  "sort_order" integer DEFAULT 0 NOT NULL,
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_metric_composition_idx_yak_metric_comp_metric" ON "yak_metric_composition" ("project_id", "metric_id");

CREATE INDEX "yak_metric_composition_idx_yak_metric_comp_sub" ON "yak_metric_composition" ("project_id", "sub_metric_id");

CREATE TABLE "yak_metric_usage" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "metric_id" bigint NOT NULL,
  "metric_version" integer,
  "usage_type" citext NOT NULL CHECK (length("usage_type") <= 16),
  "usage_id" bigint NOT NULL,
  "usage_name" citext CHECK (length("usage_name") <= 128),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_metric_usage_idx_yak_metric_usage_consumer" ON "yak_metric_usage" ("usage_type", "usage_id");

CREATE INDEX "yak_metric_usage_idx_yak_metric_usage_metric" ON "yak_metric_usage" ("project_id", "metric_id");

CREATE TABLE "yak_metric_validation_evidence" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "metric_id" bigint NOT NULL,
  "metric_version_id" bigint NOT NULL,
  "metric_version" integer NOT NULL,
  "result" citext NOT NULL CHECK (length("result") <= 16),
  "provider_state" citext DEFAULT 'READY' NOT NULL CHECK (length("provider_state") <= 16),
  "issues_json" jsonb NOT NULL,
  "provider" citext NOT NULL CHECK (length("provider") <= 128),
  "snapshot_digest" citext NOT NULL CHECK (length("snapshot_digest") <= 64),
  "checked_by" citext NOT NULL CHECK (length("checked_by") <= 64),
  "checked_at" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_metric_validation_evidence_idx_metric_validation_ready" ON "yak_metric_validation_evidence" ("project_id", "metric_id", "metric_version", "result", "checked_at");

CREATE INDEX "yak_metric_validation_evidence_idx_metric_validation_subject" ON "yak_metric_validation_evidence" ("project_id", "metric_id", "metric_version", "checked_at");

CREATE INDEX "yak_metric_validation_evidence_idx_metric_validation_version_id" ON "yak_metric_validation_evidence" ("project_id", "metric_version_id");

CREATE TABLE "yak_metric_publication_event" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "metric_id" bigint NOT NULL,
  "metric_version_id" bigint NOT NULL,
  "metric_version" integer NOT NULL,
  "snapshot_digest" citext NOT NULL CHECK (length("snapshot_digest") <= 64),
  "event_type" citext NOT NULL CHECK (length("event_type") <= 16),
  "subject_publication_id" bigint,
  "readiness_json" jsonb,
  "acted_by" citext NOT NULL CHECK (length("acted_by") <= 64),
  "acted_at" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_metric_publication_event_idx_metric_publication_metric" ON "yak_metric_publication_event" ("project_id", "metric_id", "acted_at");

CREATE INDEX "yak_metric_publication_event_idx_metric_publication_subject" ON "yak_metric_publication_event" ("project_id", "subject_publication_id");

CREATE INDEX "yak_metric_publication_event_idx_metric_publication_version" ON "yak_metric_publication_event" ("project_id", "metric_version_id");

CREATE TABLE "yak_metric_active_publication" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "metric_id" bigint NOT NULL,
  "publication_event_id" bigint NOT NULL,
  "metric_version_id" bigint NOT NULL,
  "metric_version" integer NOT NULL,
  "snapshot_digest" citext NOT NULL CHECK (length("snapshot_digest") <= 64),
  "published_by" citext NOT NULL CHECK (length("published_by") <= 64),
  "published_at" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_metric_active_publication_idx_metric_active_public_5ba9af7d" ON "yak_metric_active_publication" ("project_id", "publication_event_id");

CREATE INDEX "yak_metric_active_publication_idx_metric_active_public_735a644e" ON "yak_metric_active_publication" ("project_id", "metric_version_id");

CREATE UNIQUE INDEX "yak_metric_active_publication_uk_metric_active_publication" ON "yak_metric_active_publication" ("project_id", "metric_id");

CREATE TRIGGER "yak_metric_active_publication_touch" BEFORE UPDATE ON "yak_metric_active_publication" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');
