-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_security_dept" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "dept_name" citext NOT NULL CHECK (length("dept_name") <= 64),
  "parent_id" bigint DEFAULT 0 NOT NULL,
  "leaf" smallint NOT NULL,
  "level" integer NOT NULL,
  "description" citext CHECK (length("description") <= 255),
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_dept_name" citext GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN dept_name ELSE NULL END) STORED CHECK (length("active_dept_name") <= 64),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_dept_idx_dept_app_delete" ON "yak_security_dept" ("app_name", "is_delete");

CREATE INDEX "yak_security_dept_idx_dept_app_parent" ON "yak_security_dept" ("app_name", "parent_id");

CREATE UNIQUE INDEX "yak_security_dept_uk_dept_app_name" ON "yak_security_dept" ("app_name", "active_dept_name");

CREATE TRIGGER "yak_security_dept_touch" BEFORE UPDATE ON "yak_security_dept" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_dept_name');

CREATE TABLE "yak_security_message" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" citext NOT NULL CHECK (length("title") <= 128),
  "summary" citext CHECK (length("summary") <= 255),
  "content" citext CHECK (length("content") <= 1024),
  "message_type" citext DEFAULT 'SYSTEM' NOT NULL CHECK (length("message_type") <= 32),
  "message_level" citext DEFAULT 'INFO' NOT NULL CHECK (length("message_level") <= 16),
  "message_scope" citext DEFAULT 'SYSTEM' NOT NULL CHECK (length("message_scope") <= 16),
  "project_id" bigint,
  "source_type" citext CHECK (length("source_type") <= 64),
  "source_id" citext CHECK (length("source_id") <= 128),
  "action_path" citext CHECK (length("action_path") <= 512),
  "read_tag" smallint DEFAULT 0 NOT NULL,
  "read_time" timestamp(0) without time zone,
  "oplog_id" bigint,
  "user_id" bigint NOT NULL,
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_message_idx_message_app_oplog" ON "yak_security_message" ("app_name", "oplog_id");

CREATE INDEX "yak_security_message_idx_message_app_source" ON "yak_security_message" ("app_name", "source_type", "source_id");

CREATE INDEX "yak_security_message_idx_message_app_user" ON "yak_security_message" ("app_name", "user_id", "is_delete");

CREATE INDEX "yak_security_message_idx_message_app_user_project" ON "yak_security_message" ("app_name", "user_id", "project_id", "create_time");

CREATE INDEX "yak_security_message_idx_message_app_user_read" ON "yak_security_message" ("app_name", "user_id", "read_tag", "create_time");

CREATE TRIGGER "yak_security_message_touch" BEFORE UPDATE ON "yak_security_message" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_security_oplog" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "operator_ip" citext NOT NULL CHECK (length("operator_ip") <= 45),
  "operator" citext CHECK (length("operator") <= 64),
  "operate_page" citext NOT NULL CHECK (length("operate_page") <= 64),
  "operate_type" citext NOT NULL CHECK (length("operate_type") <= 64),
  "target_type" citext NOT NULL CHECK (length("target_type") <= 64),
  "target" citext NOT NULL CHECK (length("target") <= 128),
  "operation_methods" citext NOT NULL CHECK (length("operation_methods") <= 64),
  "detail" text,
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_oplog_idx_oplog_app_delete" ON "yak_security_oplog" ("app_name", "is_delete");

CREATE INDEX "yak_security_oplog_idx_oplog_app_operator" ON "yak_security_oplog" ("app_name", "operator");

CREATE INDEX "yak_security_oplog_idx_oplog_app_time" ON "yak_security_oplog" ("app_name", "create_time");

CREATE TRIGGER "yak_security_oplog_touch" BEFORE UPDATE ON "yak_security_oplog" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_security_oplog_extra" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "info" citext CHECK (length("info") <= 128),
  "type" smallint NOT NULL,
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_oplog_extra_idx_oplog_extra_app_type" ON "yak_security_oplog_extra" ("app_name", "type", "is_delete");

CREATE TRIGGER "yak_security_oplog_extra_touch" BEFORE UPDATE ON "yak_security_oplog_extra" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_security_permission" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "permission_code" citext NOT NULL CHECK (length("permission_code") <= 128),
  "permission_name" citext NOT NULL CHECK (length("permission_name") <= 128),
  "parent_id" bigint DEFAULT 0 NOT NULL,
  "leaf" smallint NOT NULL,
  "level" integer NOT NULL,
  "description" citext CHECK (length("description") <= 255),
  "menu_code" citext CHECK (length("menu_code") <= 128),
  "active" smallint DEFAULT 1 NOT NULL,
  "declared" smallint DEFAULT 0 NOT NULL,
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_permission_code" citext GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN permission_code ELSE NULL END) STORED CHECK (length("active_permission_code") <= 128),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_permission_idx_permission_app_declared" ON "yak_security_permission" ("app_name", "declared", "active");

CREATE INDEX "yak_security_permission_idx_permission_app_delete" ON "yak_security_permission" ("app_name", "is_delete");

CREATE INDEX "yak_security_permission_idx_permission_app_menu" ON "yak_security_permission" ("app_name", "menu_code", "active", "is_delete");

CREATE INDEX "yak_security_permission_idx_permission_app_parent" ON "yak_security_permission" ("app_name", "parent_id");

CREATE UNIQUE INDEX "yak_security_permission_uk_permission_app_code" ON "yak_security_permission" ("app_name", "active_permission_code");

CREATE TRIGGER "yak_security_permission_touch" BEFORE UPDATE ON "yak_security_permission" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_permission_code');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('1', 'security', '系统管理', '0', '0', '1', 'Yak Security 系统管理权限', NULL, '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('2', 'security:root', '超级管理员', '1', '1', '2', '拥有当前应用全部权限', NULL, '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('3', 'security:user:read', '查看用户管理', '1', '1', '2', '查看用户管理页面及接口', 'system-users', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('4', 'security:user:create', '新增用户', '1', '1', '2', '创建系统用户', 'system-users', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('5', 'security:user:update', '编辑用户', '1', '1', '2', '修改系统用户资料', 'system-users', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('6', 'security:user:reset-password', '重置用户密码', '1', '1', '2', '管理员重置用户密码', 'system-users', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('7', 'security:user:delete', '删除用户', '1', '1', '2', '删除系统用户', 'system-users', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('8', 'security:role:read', '查看角色管理', '1', '1', '2', '查看角色管理页面及接口', 'system-roles', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('9', 'security:role:create', '新增角色', '1', '1', '2', '创建系统角色', 'system-roles', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('10', 'security:role:update', '编辑角色', '1', '1', '2', '修改角色资料和权限', 'system-roles', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('11', 'security:role:assign', '分配角色关系', '1', '1', '2', '为用户分配角色或为角色分配用户', 'system-roles', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('12', 'security:role:delete', '删除角色', '1', '1', '2', '删除系统角色', 'system-roles', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('13', 'security:permission:read', '查看权限管理', '1', '1', '2', '查看权限管理页面及接口', 'system-permissions', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('14', 'security:permission:import', '导入权限', '1', '1', '2', '导入手工权限目录', 'system-permissions', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('15', 'security:permission:delete', '删除权限', '1', '1', '2', '删除手工权限及角色关联', 'system-permissions', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('16', 'security:department:read', '查看部门管理', '1', '1', '2', '查看部门管理页面及接口', 'system-departments', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('17', 'security:project:read', '查看授权项目', '1', '1', '2', '查看 Yak Security 授权项目页面及接口', 'system-security-projects', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('18', 'security:resource-permission:read', '查看资源授权', '1', '1', '2', '查看资源授权页面及接口', 'system-resource-permissions', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('19', 'security:config:read', '查看系统配置', '1', '1', '2', '查看系统配置页面及接口', 'system-configs', '1', '0', '0', '${appName}');

INSERT INTO "yak_security_permission" ("id", "permission_code", "permission_name", "parent_id", "leaf", "level", "description", "menu_code", "active", "declared", "is_delete", "app_name") VALUES ('20', 'security:operation-log:read', '查看操作日志', '1', '1', '2', '查看操作日志页面及接口', 'system-operation-logs', '1', '0', '0', '${appName}');

SELECT setval(pg_get_serial_sequence('yak_security_permission', 'id'), (SELECT MAX("id") FROM "yak_security_permission"));

CREATE TABLE "yak_security_project" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_code" citext NOT NULL CHECK (length("project_code") <= 128),
  "project_name" citext NOT NULL CHECK (length("project_name") <= 128),
  "description" citext DEFAULT '' NOT NULL CHECK (length("description") <= 512),
  "dept_id" bigint NOT NULL,
  "running" smallint DEFAULT 1 NOT NULL,
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_project_code" citext GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN project_code ELSE NULL END) STORED CHECK (length("active_project_code") <= 128),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_project_idx_project_app_delete" ON "yak_security_project" ("app_name", "is_delete");

CREATE INDEX "yak_security_project_idx_project_app_dept" ON "yak_security_project" ("app_name", "dept_id");

CREATE UNIQUE INDEX "yak_security_project_uk_project_app_code" ON "yak_security_project" ("app_name", "active_project_code");

CREATE TRIGGER "yak_security_project_touch" BEFORE UPDATE ON "yak_security_project" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_project_code');

CREATE TABLE "yak_security_resource_type" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type_name" citext NOT NULL CHECK (length("type_name") <= 64),
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_type_name" citext GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN type_name ELSE NULL END) STORED CHECK (length("active_type_name") <= 64),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_resource_type_idx_resource_type_app_delete" ON "yak_security_resource_type" ("app_name", "is_delete");

CREATE UNIQUE INDEX "yak_security_resource_type_uk_resource_type_app_name" ON "yak_security_resource_type" ("app_name", "active_type_name");

CREATE TRIGGER "yak_security_resource_type_touch" BEFORE UPDATE ON "yak_security_resource_type" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_type_name');

INSERT INTO "yak_security_resource_type" ("id", "type_name", "is_delete", "app_name") VALUES ('1', 'PROJECT', '0', '${appName}');

INSERT INTO "yak_security_resource_type" ("id", "type_name", "is_delete", "app_name") VALUES ('2', 'SECURITY_RESOURCE', '0', '${appName}');

SELECT setval(pg_get_serial_sequence('yak_security_resource_type', 'id'), (SELECT MAX("id") FROM "yak_security_resource_type"));

CREATE TABLE "yak_security_role" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "role_code" citext NOT NULL CHECK (length("role_code") <= 128),
  "role_name" citext NOT NULL CHECK (length("role_name") <= 128),
  "description" citext CHECK (length("description") <= 255),
  "last_reviser" citext CHECK (length("last_reviser") <= 64),
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_role_code" citext GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN role_code ELSE NULL END) STORED CHECK (length("active_role_code") <= 128),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_role_idx_role_app_delete" ON "yak_security_role" ("app_name", "is_delete");

CREATE UNIQUE INDEX "yak_security_role_uk_role_app_code" ON "yak_security_role" ("app_name", "active_role_code");

CREATE TRIGGER "yak_security_role_touch" BEFORE UPDATE ON "yak_security_role" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_role_code');

CREATE TABLE "yak_security_user" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_name" citext NOT NULL CHECK (length("user_name") <= 64),
  "pw" citext NOT NULL CHECK (length("pw") <= 2048),
  "salt" citext DEFAULT '' NOT NULL CHECK (length("salt") <= 64),
  "real_name" citext DEFAULT '' NOT NULL CHECK (length("real_name") <= 128),
  "phone" citext DEFAULT '' NOT NULL CHECK (length("phone") <= 32),
  "email" citext DEFAULT '' NOT NULL CHECK (length("email") <= 128),
  "dept_id" bigint,
  "status" integer DEFAULT 1 NOT NULL,
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_user_name" citext GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN user_name ELSE NULL END) STORED CHECK (length("active_user_name") <= 64),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_user_idx_user_app_delete" ON "yak_security_user" ("app_name", "is_delete");

CREATE INDEX "yak_security_user_idx_user_app_dept" ON "yak_security_user" ("app_name", "dept_id");

CREATE INDEX "yak_security_user_idx_user_app_email" ON "yak_security_user" ("app_name", "email");

CREATE INDEX "yak_security_user_idx_user_app_phone" ON "yak_security_user" ("app_name", "phone");

CREATE UNIQUE INDEX "yak_security_user_uk_user_app_name" ON "yak_security_user" ("app_name", "active_user_name");

CREATE TRIGGER "yak_security_user_touch" BEFORE UPDATE ON "yak_security_user" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_user_name');

CREATE TABLE "yak_security_role_permission" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "role_id" bigint NOT NULL,
  "permission_id" bigint NOT NULL,
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_relation" smallint GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN 0 ELSE NULL END) STORED,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_role_permission_idx_role_permission_permission" ON "yak_security_role_permission" ("app_name", "permission_id", "is_delete");

CREATE INDEX "yak_security_role_permission_idx_role_permission_role" ON "yak_security_role_permission" ("app_name", "role_id", "is_delete");

CREATE UNIQUE INDEX "yak_security_role_permission_uk_role_permission_active" ON "yak_security_role_permission" ("app_name", "role_id", "permission_id", "active_relation");

CREATE TRIGGER "yak_security_role_permission_touch" BEFORE UPDATE ON "yak_security_role_permission" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_relation');

CREATE TABLE "yak_security_user_project" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" bigint NOT NULL,
  "user_type" smallint DEFAULT 0 NOT NULL,
  "project_id" bigint NOT NULL,
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_relation" smallint GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN 0 ELSE NULL END) STORED,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_user_project_idx_user_project_project" ON "yak_security_user_project" ("app_name", "project_id", "is_delete");

CREATE INDEX "yak_security_user_project_idx_user_project_user" ON "yak_security_user_project" ("app_name", "user_id", "is_delete");

CREATE UNIQUE INDEX "yak_security_user_project_uk_user_project_active" ON "yak_security_user_project" ("app_name", "user_id", "project_id", "active_relation");

CREATE TRIGGER "yak_security_user_project_touch" BEFORE UPDATE ON "yak_security_user_project" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_relation');

CREATE TABLE "yak_security_user_resource" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" bigint NOT NULL,
  "project_id" bigint NOT NULL,
  "resource_type_id" bigint NOT NULL,
  "resource_id" bigint NOT NULL,
  "control_level" smallint NOT NULL,
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_relation" smallint GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN 0 ELSE NULL END) STORED,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_user_resource_idx_user_resource_project" ON "yak_security_user_resource" ("app_name", "project_id", "is_delete");

CREATE INDEX "yak_security_user_resource_idx_user_resource_resource" ON "yak_security_user_resource" ("app_name", "resource_id", "is_delete");

CREATE INDEX "yak_security_user_resource_idx_user_resource_type" ON "yak_security_user_resource" ("app_name", "resource_type_id", "is_delete");

CREATE INDEX "yak_security_user_resource_idx_user_resource_user" ON "yak_security_user_resource" ("app_name", "user_id", "is_delete");

CREATE UNIQUE INDEX "yak_security_user_resource_uk_user_resource_active" ON "yak_security_user_resource" ("app_name", "user_id", "project_id", "resource_type_id", "resource_id", "active_relation");

CREATE TRIGGER "yak_security_user_resource_touch" BEFORE UPDATE ON "yak_security_user_resource" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_relation');

CREATE TABLE "yak_security_user_role" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" bigint NOT NULL,
  "role_id" bigint NOT NULL,
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_relation" smallint GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN 0 ELSE NULL END) STORED,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_user_role_idx_user_role_role" ON "yak_security_user_role" ("app_name", "role_id", "is_delete");

CREATE INDEX "yak_security_user_role_idx_user_role_user" ON "yak_security_user_role" ("app_name", "user_id", "is_delete");

CREATE UNIQUE INDEX "yak_security_user_role_uk_user_role_active" ON "yak_security_user_role" ("app_name", "user_id", "role_id", "active_relation");

CREATE TRIGGER "yak_security_user_role_touch" BEFORE UPDATE ON "yak_security_user_role" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_relation');

CREATE TABLE "yak_security_config" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "value_group" citext DEFAULT '' NOT NULL CHECK (length("value_group") <= 100),
  "value_name" citext DEFAULT '' NOT NULL CHECK (length("value_name") <= 100),
  "value" text,
  "edit" integer DEFAULT 1 NOT NULL,
  "status" integer DEFAULT 1 NOT NULL,
  "memo" citext DEFAULT '' NOT NULL CHECK (length("memo") <= 1000),
  "operator" citext CHECK (length("operator") <= 64),
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_config_name" citext GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN value_name ELSE NULL END) STORED CHECK (length("active_config_name") <= 100),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_config_idx_config_app_status" ON "yak_security_config" ("app_name", "status", "is_delete");

CREATE UNIQUE INDEX "yak_security_config_uk_config_app_group_name" ON "yak_security_config" ("app_name", "value_group", "active_config_name");

CREATE TRIGGER "yak_security_config_touch" BEFORE UPDATE ON "yak_security_config" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_config_name');

CREATE TABLE "yak_security_menu" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "menu_code" citext NOT NULL CHECK (length("menu_code") <= 128),
  "menu_name" citext NOT NULL CHECK (length("menu_name") <= 128),
  "parent_code" citext CHECK (length("parent_code") <= 128),
  "route_path" citext CHECK (length("route_path") <= 255),
  "icon_key" citext CHECK (length("icon_key") <= 64),
  "menu_type" smallint DEFAULT 2 NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "visible" smallint DEFAULT 1 NOT NULL,
  "active" smallint DEFAULT 1 NOT NULL,
  "required_permission_code" citext CHECK (length("required_permission_code") <= 128),
  "description" citext CHECK (length("description") <= 255),
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_menu_code" citext GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN menu_code ELSE NULL END) STORED CHECK (length("active_menu_code") <= 128),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_menu_idx_menu_app_parent" ON "yak_security_menu" ("app_name", "parent_code", "is_delete");

CREATE INDEX "yak_security_menu_idx_menu_app_permission" ON "yak_security_menu" ("app_name", "required_permission_code", "is_delete");

CREATE INDEX "yak_security_menu_idx_menu_app_status" ON "yak_security_menu" ("app_name", "active", "visible", "is_delete");

CREATE UNIQUE INDEX "yak_security_menu_uk_menu_app_code" ON "yak_security_menu" ("app_name", "active_menu_code");

CREATE TRIGGER "yak_security_menu_touch" BEFORE UPDATE ON "yak_security_menu" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_menu_code');

INSERT INTO "yak_security_menu" ("id", "menu_code", "menu_name", "parent_code", "route_path", "icon_key", "menu_type", "sort_order", "visible", "active", "required_permission_code", "description", "is_delete", "app_name") VALUES ('1', 'system', '系统管理', NULL, NULL, 'system', '1', '60', '1', '1', NULL, 'Yak Security 系统管理入口', '0', '${appName}');

INSERT INTO "yak_security_menu" ("id", "menu_code", "menu_name", "parent_code", "route_path", "icon_key", "menu_type", "sort_order", "visible", "active", "required_permission_code", "description", "is_delete", "app_name") VALUES ('2', 'system-users', '用户管理', 'system', '/system/users', 'system', '2', '10', '1', '1', 'security:user:read', '用户管理', '0', '${appName}');

INSERT INTO "yak_security_menu" ("id", "menu_code", "menu_name", "parent_code", "route_path", "icon_key", "menu_type", "sort_order", "visible", "active", "required_permission_code", "description", "is_delete", "app_name") VALUES ('3', 'system-roles', '角色管理', 'system', '/system/roles', 'system', '2', '20', '1', '1', 'security:role:read', '角色及授权管理', '0', '${appName}');

INSERT INTO "yak_security_menu" ("id", "menu_code", "menu_name", "parent_code", "route_path", "icon_key", "menu_type", "sort_order", "visible", "active", "required_permission_code", "description", "is_delete", "app_name") VALUES ('4', 'system-permissions', '权限管理', 'system', '/system/permissions', 'system', '2', '30', '1', '1', 'security:permission:read', '操作权限管理', '0', '${appName}');

INSERT INTO "yak_security_menu" ("id", "menu_code", "menu_name", "parent_code", "route_path", "icon_key", "menu_type", "sort_order", "visible", "active", "required_permission_code", "description", "is_delete", "app_name") VALUES ('5', 'system-departments', '部门管理', 'system', '/system/departments', 'system', '2', '40', '1', '1', 'security:department:read', '部门管理', '0', '${appName}');

INSERT INTO "yak_security_menu" ("id", "menu_code", "menu_name", "parent_code", "route_path", "icon_key", "menu_type", "sort_order", "visible", "active", "required_permission_code", "description", "is_delete", "app_name") VALUES ('6', 'system-security-projects', 'Security 授权项目', 'system', '/system/projects', 'system', '2', '50', '1', '1', 'security:project:read', '安全项目管理', '0', '${appName}');

INSERT INTO "yak_security_menu" ("id", "menu_code", "menu_name", "parent_code", "route_path", "icon_key", "menu_type", "sort_order", "visible", "active", "required_permission_code", "description", "is_delete", "app_name") VALUES ('7', 'system-resource-permissions', '资源授权', 'system', '/system/resource-permissions', 'system', '2', '60', '1', '1', 'security:resource-permission:read', '资源级授权管理', '0', '${appName}');

INSERT INTO "yak_security_menu" ("id", "menu_code", "menu_name", "parent_code", "route_path", "icon_key", "menu_type", "sort_order", "visible", "active", "required_permission_code", "description", "is_delete", "app_name") VALUES ('8', 'system-configs', '系统配置', 'system', '/system/configs', 'system', '2', '70', '1', '1', 'security:config:read', '系统配置管理', '0', '${appName}');

INSERT INTO "yak_security_menu" ("id", "menu_code", "menu_name", "parent_code", "route_path", "icon_key", "menu_type", "sort_order", "visible", "active", "required_permission_code", "description", "is_delete", "app_name") VALUES ('9', 'system-operation-logs', '操作日志', 'system', '/system/oplogs', 'system', '2', '80', '1', '1', 'security:operation-log:read', '操作日志查询', '0', '${appName}');

SELECT setval(pg_get_serial_sequence('yak_security_menu', 'id'), (SELECT MAX("id") FROM "yak_security_menu"));

CREATE TABLE "yak_security_role_menu" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "role_id" bigint NOT NULL,
  "menu_id" bigint NOT NULL,
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "is_delete" smallint DEFAULT 0 NOT NULL,
  "app_name" citext NOT NULL CHECK (length("app_name") <= 64),
  "active_relation" smallint GENERATED ALWAYS AS (CASE WHEN (is_delete = 0) THEN 0 ELSE NULL END) STORED,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_security_role_menu_idx_role_menu_menu" ON "yak_security_role_menu" ("app_name", "menu_id", "is_delete");

CREATE INDEX "yak_security_role_menu_idx_role_menu_role" ON "yak_security_role_menu" ("app_name", "role_id", "is_delete");

CREATE UNIQUE INDEX "yak_security_role_menu_uk_role_menu_active" ON "yak_security_role_menu" ("app_name", "role_id", "menu_id", "active_relation");

CREATE TRIGGER "yak_security_role_menu_touch" BEFORE UPDATE ON "yak_security_role_menu" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time', 'active_relation');
