-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE "yak_digital_screen" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "name" citext NOT NULL CHECK (length("name") <= 200),
  "description" citext CHECK (length("description") <= 2000),
  "template_id" citext NOT NULL CHECK (length("template_id") <= 128),
  "template_version" integer DEFAULT 1 NOT NULL,
  "status" citext DEFAULT 'DRAFT' NOT NULL CHECK (length("status") <= 32),
  "bindings_json" jsonb NOT NULL,
  "revision" bigint DEFAULT 1 NOT NULL,
  "published_revision" bigint,
  "published_version_id" bigint,
  "published_version_no" integer DEFAULT 0 NOT NULL,
  "published_time" timestamp(6) without time zone,
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_digital_screen_idx_yak_digital_screen_project_status_update" ON "yak_digital_screen" ("project_id", "status", "update_time", "id");

CREATE INDEX "yak_digital_screen_idx_yak_digital_screen_published_version" ON "yak_digital_screen" ("published_version_id");

CREATE INDEX "yak_digital_screen_idx_yak_digital_screen_status_update" ON "yak_digital_screen" ("status", "update_time");

CREATE INDEX "yak_digital_screen_idx_yak_digital_screen_template" ON "yak_digital_screen" ("template_id");

CREATE INDEX "yak_digital_screen_idx_yak_digital_screen_update" ON "yak_digital_screen" ("update_time");

CREATE TABLE "yak_digital_screen_version" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "screen_id" bigint NOT NULL,
  "version_no" integer NOT NULL,
  "source_revision" bigint NOT NULL,
  "name_snapshot" citext NOT NULL CHECK (length("name_snapshot") <= 200),
  "description_snapshot" citext CHECK (length("description_snapshot") <= 2000),
  "template_id_snapshot" citext NOT NULL CHECK (length("template_id_snapshot") <= 128),
  "template_version_snapshot" integer DEFAULT 1 NOT NULL,
  "bindings_json" jsonb NOT NULL,
  "published_time" timestamp(6) without time zone NOT NULL,
  "create_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_digital_screen_version_idx_yak_digital_screen_version_time" ON "yak_digital_screen_version" ("screen_id", "published_time");

CREATE UNIQUE INDEX "yak_digital_screen_version_uk_yak_digital_screen_version_no" ON "yak_digital_screen_version" ("screen_id", "version_no");
