-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE "yak_task_asset" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "source" citext NOT NULL CHECK (length("source") <= 32),
  "source_ref" citext NOT NULL CHECK (length("source_ref") <= 128),
  "project_id" bigint,
  "project_scope_id" bigint GENERATED ALWAYS AS (COALESCE(project_id, 0)) STORED,
  "name" citext NOT NULL CHECK (length("name") <= 200),
  "task_type" citext NOT NULL CHECK (length("task_type") <= 64),
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "current_revision_id" bigint NOT NULL,
  "current_revision_no" integer NOT NULL,
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_task_asset_idx_yak_task_asset_catalog" ON "yak_task_asset" ("status", "source", "task_type");

CREATE INDEX "yak_task_asset_idx_yak_task_asset_project" ON "yak_task_asset" ("project_id", "status");

CREATE INDEX "yak_task_asset_idx_yak_task_asset_project_catalog" ON "yak_task_asset" ("project_id", "status", "source", "task_type", "update_time");

CREATE INDEX "yak_task_asset_idx_yak_task_asset_update" ON "yak_task_asset" ("update_time");

CREATE UNIQUE INDEX "yak_task_asset_uk_yak_task_asset_project_source_ref" ON "yak_task_asset" ("project_scope_id", "source", "source_ref");
