-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_lc_policy" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "policy_code" citext NOT NULL CHECK (length("policy_code") <= 64),
  "policy_name" citext NOT NULL CHECK (length("policy_name") <= 128),
  "scope_type" citext NOT NULL CHECK (length("scope_type") <= 16),
  "layer_code" citext CHECK (length("layer_code") <= 32),
  "partition_granularity" citext DEFAULT 'DAY' NOT NULL CHECK (length("partition_granularity") <= 8),
  "hot_days" integer,
  "cold_days" integer,
  "destroy_days" integer,
  "builtin" smallint DEFAULT 0 NOT NULL,
  "status" citext DEFAULT 'ENABLED' NOT NULL CHECK (length("status") <= 16),
  "publish_state" citext DEFAULT 'DRAFT' NOT NULL CHECK (length("publish_state") <= 16),
  "draft_revision" integer DEFAULT 0 NOT NULL,
  "published_version_id" bigint,
  "latest_version_no" integer DEFAULT 0 NOT NULL,
  "remark" citext CHECK (length("remark") <= 512),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "updated_by" citext CHECK (length("updated_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_lc_policy_idx_yak_lc_policy_layer" ON "yak_lc_policy" ("project_id", "layer_code", "deleted");

CREATE UNIQUE INDEX "yak_lc_policy_uk_yak_lc_policy_code" ON "yak_lc_policy" ("project_id", "policy_code");

CREATE TRIGGER "yak_lc_policy_touch" BEFORE UPDATE ON "yak_lc_policy" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_lc_model_binding" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "model_id" bigint NOT NULL,
  "policy_id" bigint NOT NULL,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "updated_by" citext CHECK (length("updated_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_lc_model_binding_idx_yak_lc_binding_policy" ON "yak_lc_model_binding" ("project_id", "policy_id");

CREATE UNIQUE INDEX "yak_lc_model_binding_uk_yak_lc_binding_model" ON "yak_lc_model_binding" ("project_id", "model_id", "deleted");

CREATE TRIGGER "yak_lc_model_binding_touch" BEFORE UPDATE ON "yak_lc_model_binding" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_lc_dispatch_record" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "model_id" bigint NOT NULL,
  "policy_id" bigint NOT NULL,
  "policy_updated_at" timestamp(6) without time zone,
  "trigger_type" citext DEFAULT 'MANUAL' NOT NULL CHECK (length("trigger_type") <= 16),
  "datasource_id" bigint,
  "database_name" citext CHECK (length("database_name") <= 128),
  "table_name" citext CHECK (length("table_name") <= 128),
  "storage_type" citext CHECK (length("storage_type") <= 16),
  "statement" text,
  "status" citext NOT NULL CHECK (length("status") <= 16),
  "attempts" integer DEFAULT 1 NOT NULL,
  "next_retry_time" timestamp(6) without time zone,
  "error_message" text,
  "partition_hot" integer,
  "partition_cold" integer,
  "partition_deleted" integer,
  "operator" citext NOT NULL CHECK (length("operator") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "finish_time" timestamp(6) without time zone,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_lc_dispatch_record_idx_yak_lc_dispatch_model" ON "yak_lc_dispatch_record" ("project_id", "model_id", "id");

CREATE INDEX "yak_lc_dispatch_record_idx_yak_lc_dispatch_retry" ON "yak_lc_dispatch_record" ("status", "next_retry_time");

CREATE TABLE "yak_lc_storage_snapshot" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "snapshot_date" date NOT NULL,
  "layer_code" citext NOT NULL CHECK (length("layer_code") <= 32),
  "datasource_id" bigint NOT NULL,
  "database_name" citext NOT NULL CHECK (length("database_name") <= 128),
  "table_name" citext NOT NULL CHECK (length("table_name") <= 128),
  "size_bytes" bigint DEFAULT 0 NOT NULL,
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_lc_storage_snapshot_idx_yak_lc_snapshot_trend" ON "yak_lc_storage_snapshot" ("project_id", "snapshot_date", "layer_code");

CREATE UNIQUE INDEX "yak_lc_storage_snapshot_uk_yak_lc_snapshot" ON "yak_lc_storage_snapshot" ("project_id", "snapshot_date", "datasource_id", "table_name");

CREATE TABLE "yak_lc_setting" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "setting_key" citext NOT NULL CHECK (length("setting_key") <= 64),
  "setting_value" citext CHECK (length("setting_value") <= 256),
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_lc_setting_uk_yak_lc_setting" ON "yak_lc_setting" ("project_id", "setting_key");

CREATE TRIGGER "yak_lc_setting_touch" BEFORE UPDATE ON "yak_lc_setting" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_lc_policy_version" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "policy_id" bigint NOT NULL,
  "project_id" bigint NOT NULL,
  "version_no" integer NOT NULL,
  "payload_json" text NOT NULL,
  "checksum" citext NOT NULL CHECK (length("checksum") <= 64),
  "source_draft_revision" integer,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_lc_policy_version_uk_yak_lc_policy_version" ON "yak_lc_policy_version" ("policy_id", "version_no");
