-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE "yak_dev_directory" (
  "id" bigint NOT NULL,
  "project_id" bigint NOT NULL,
  "parent_id" bigint DEFAULT 0 NOT NULL,
  "name" citext NOT NULL CHECK (length("name") <= 128),
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dev_directory_idx_yak_dev_directory_parent" ON "yak_dev_directory" ("parent_id");

CREATE INDEX "yak_dev_directory_idx_yak_dev_directory_project_parent" ON "yak_dev_directory" ("project_id", "parent_id");

CREATE UNIQUE INDEX "yak_dev_directory_uk_yak_dev_directory_project_sibling" ON "yak_dev_directory" ("project_id", "parent_id", "name");

CREATE TABLE "yak_dev_node" (
  "id" bigint NOT NULL,
  "name" citext NOT NULL CHECK (length("name") <= 200),
  "type" citext NOT NULL CHECK (length("type") <= 32),
  "project_id" bigint NOT NULL,
  "directory_id" bigint DEFAULT 0 NOT NULL,
  "configured" smallint DEFAULT 0 NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  "updated_by" citext CHECK (length("updated_by") <= 128),
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dev_node_idx_yak_dev_node_directory" ON "yak_dev_node" ("directory_id", "name");

CREATE INDEX "yak_dev_node_idx_yak_dev_node_project" ON "yak_dev_node" ("project_id", "update_time");

CREATE INDEX "yak_dev_node_idx_yak_dev_node_project_directory" ON "yak_dev_node" ("project_id", "directory_id", "name");

CREATE INDEX "yak_dev_node_idx_yak_dev_node_type" ON "yak_dev_node" ("type", "update_time");

CREATE TABLE "yak_dev_task_draft" (
  "node_id" bigint NOT NULL,
  "task_type" citext NOT NULL CHECK (length("task_type") <= 32),
  "schema_version" integer NOT NULL,
  "content" text NOT NULL,
  "config_json" text NOT NULL,
  "draft_revision" bigint NOT NULL,
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("node_id")
);

CREATE INDEX "yak_dev_task_draft_idx_yak_dev_task_draft_update" ON "yak_dev_task_draft" ("update_time");

CREATE TABLE "yak_dev_task_revision" (
  "id" bigint NOT NULL,
  "node_id" bigint NOT NULL,
  "revision_no" integer NOT NULL,
  "source_draft_revision" bigint NOT NULL,
  "task_type" citext NOT NULL CHECK (length("task_type") <= 32),
  "schema_version" integer NOT NULL,
  "content" text NOT NULL,
  "config_json" text NOT NULL,
  "checksum" citext NOT NULL CHECK (length("checksum") <= 64),
  "create_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dev_task_revision_idx_yak_dev_task_revision_checksum" ON "yak_dev_task_revision" ("node_id", "checksum");

CREATE INDEX "yak_dev_task_revision_idx_yak_dev_task_revision_node_time" ON "yak_dev_task_revision" ("node_id", "create_time");

CREATE UNIQUE INDEX "yak_dev_task_revision_uk_yak_dev_task_revision_node_no" ON "yak_dev_task_revision" ("node_id", "revision_no");

CREATE TABLE "yak_dev_editor_setting" (
  "user_key" citext NOT NULL CHECK (length("user_key") <= 128),
  "setting_json" text NOT NULL,
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("user_key")
);

CREATE INDEX "yak_dev_editor_setting_idx_yak_dev_editor_setting_update" ON "yak_dev_editor_setting" ("update_time");

CREATE TABLE "yak_dev_task_execution" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "node_id" bigint NOT NULL,
  "task_name" citext NOT NULL CHECK (length("task_name") <= 200),
  "task_type" citext NOT NULL CHECK (length("task_type") <= 32),
  "schema_version" integer DEFAULT 1 NOT NULL,
  "trigger_type" citext DEFAULT 'MANUAL' NOT NULL CHECK (length("trigger_type") <= 32),
  "runtime_execution_id" citext CHECK (length("runtime_execution_id") <= 128),
  "retry_of_execution_id" bigint,
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "operator_name" citext CHECK (length("operator_name") <= 128),
  "duration_ms" bigint,
  "failure_reason" citext CHECK (length("failure_reason") <= 64),
  "error_message" citext CHECK (length("error_message") <= 1000),
  "content" text NOT NULL,
  "config_json" text NOT NULL,
  "output_json" text,
  "start_time" timestamp(6) without time zone NOT NULL,
  "end_time" timestamp(6) without time zone,
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dev_task_execution_idx_yak_dev_task_execution_node_time" ON "yak_dev_task_execution" ("node_id", "start_time");

CREATE INDEX "yak_dev_task_execution_idx_yak_dev_task_execution_operator_time" ON "yak_dev_task_execution" ("operator_name", "start_time");

CREATE INDEX "yak_dev_task_execution_idx_yak_dev_task_execution_proj_6f7070b0" ON "yak_dev_task_execution" ("project_id", "status", "start_time");

CREATE INDEX "yak_dev_task_execution_idx_yak_dev_task_execution_project_time" ON "yak_dev_task_execution" ("project_id", "start_time");

CREATE INDEX "yak_dev_task_execution_idx_yak_dev_task_execution_retry" ON "yak_dev_task_execution" ("retry_of_execution_id");

CREATE INDEX "yak_dev_task_execution_idx_yak_dev_task_execution_status_time" ON "yak_dev_task_execution" ("status", "start_time");

CREATE INDEX "yak_dev_task_execution_idx_yak_dev_task_execution_status_update" ON "yak_dev_task_execution" ("status", "update_time");

CREATE INDEX "yak_dev_task_execution_idx_yak_dev_task_execution_type_time" ON "yak_dev_task_execution" ("task_type", "start_time");

CREATE UNIQUE INDEX "yak_dev_task_execution_uk_yak_dev_task_execution_runtime" ON "yak_dev_task_execution" ("runtime_execution_id");

CREATE TABLE "yak_dev_data_service_draft" (
  "node_id" bigint NOT NULL,
  "definition_json" text NOT NULL,
  "draft_revision" bigint NOT NULL,
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("node_id")
);

CREATE INDEX "yak_dev_data_service_draft_idx_yak_dev_data_service_dr_c6a25d6b" ON "yak_dev_data_service_draft" ("update_time");

CREATE TABLE "yak_dev_data_service_revision" (
  "id" bigint NOT NULL,
  "node_id" bigint NOT NULL,
  "revision_no" integer NOT NULL,
  "source_draft_revision" bigint NOT NULL,
  "definition_json" text NOT NULL,
  "checksum" citext NOT NULL CHECK (length("checksum") <= 64),
  "create_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dev_data_service_revision_idx_yak_dev_data_service_a8c78b53" ON "yak_dev_data_service_revision" ("node_id", "checksum");

CREATE INDEX "yak_dev_data_service_revision_idx_yak_dev_data_service_a2c30816" ON "yak_dev_data_service_revision" ("node_id", "create_time");

CREATE UNIQUE INDEX "yak_dev_data_service_revision_uk_yak_dev_data_service__2a14354c" ON "yak_dev_data_service_revision" ("node_id", "revision_no");

CREATE TABLE "yak_dev_lineage_outbox" (
  "task_id" citext NOT NULL CHECK (length("task_id") <= 36),
  "project_id" bigint NOT NULL,
  "node_id" bigint NOT NULL,
  "revision_id" bigint NOT NULL,
  "status" citext NOT NULL CHECK (length("status") <= 16),
  "attempts" integer DEFAULT 0 NOT NULL,
  "next_attempt_time" timestamp(6) without time zone NOT NULL,
  "last_error" citext CHECK (length("last_error") <= 2000),
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("task_id")
);

CREATE INDEX "yak_dev_lineage_outbox_idx_yak_dev_lineage_outbox_due" ON "yak_dev_lineage_outbox" ("status", "next_attempt_time");

CREATE INDEX "yak_dev_lineage_outbox_idx_yak_dev_lineage_outbox_project_due" ON "yak_dev_lineage_outbox" ("project_id", "status", "next_attempt_time");

CREATE UNIQUE INDEX "yak_dev_lineage_outbox_uk_yak_dev_lineage_outbox_revision" ON "yak_dev_lineage_outbox" ("node_id", "revision_id");

CREATE TABLE "yak_system_env_var" (
  "var_key" citext NOT NULL CHECK (length("var_key") <= 128),
  "var_value" text NOT NULL,
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("var_key")
);
