-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_offline_job_definition" (
  "id" bigint NOT NULL,
  "project_id" bigint NOT NULL,
  "job_name" citext NOT NULL CHECK (length("job_name") <= 200),
  "job_desc" citext CHECK (length("job_desc") <= 1000),
  "mode" citext NOT NULL CHECK (length("mode") <= 32),
  "definition_json" text NOT NULL,
  "job_spec_json" text,
  "config_digest" citext CHECK (length("config_digest") <= 64),
  "release_state" citext DEFAULT 'OFFLINE' NOT NULL CHECK (length("release_state") <= 16),
  "source_type" citext CHECK (length("source_type") <= 64),
  "sink_type" citext CHECK (length("sink_type") <= 64),
  "source_datasource_id" bigint,
  "sink_datasource_id" bigint,
  "source_table" text,
  "sink_table" text,
  "schedule_json" text,
  "schedule_enabled" smallint DEFAULT 0 NOT NULL,
  "cron_expression" citext CHECK (length("cron_expression") <= 128),
  "retry_max_attempts" integer DEFAULT 1 NOT NULL,
  "retry_backoff_seconds" integer DEFAULT 60 NOT NULL,
  "schedule_last_fire_time" timestamp(3) without time zone,
  "schedule_next_fire_time" timestamp(3) without time zone,
  "version" integer DEFAULT 0 NOT NULL,
  "last_execution_id" bigint,
  "last_engine_job_id" citext CHECK (length("last_engine_job_id") <= 128),
  "last_job_status" citext CHECK (length("last_job_status") <= 32),
  "last_error_message" text,
  "last_duration_millis" bigint,
  "last_read_row_count" bigint,
  "last_qps" double precision,
  "last_sync_bytes" bigint,
  "last_start_time" timestamp(3) without time zone,
  "last_end_time" timestamp(3) without time zone,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "notification_config_json" text,
  "editor_meta_json" text,
  "published_revision_id" bigint,
  "latest_version_no" integer DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_offline_job_definition_idx_yak_offline_job_status" ON "yak_offline_job_definition" ("last_job_status");

CREATE INDEX "yak_offline_job_definition_idx_yak_offline_project_release" ON "yak_offline_job_definition" ("project_id", "release_state", "update_time");

CREATE INDEX "yak_offline_job_definition_idx_yak_offline_project_schedule" ON "yak_offline_job_definition" ("project_id", "schedule_enabled", "cron_expression");

CREATE INDEX "yak_offline_job_definition_idx_yak_offline_project_sch_f9102f7c" ON "yak_offline_job_definition" ("project_id", "schedule_enabled", "schedule_next_fire_time");

CREATE INDEX "yak_offline_job_definition_idx_yak_offline_release_state" ON "yak_offline_job_definition" ("release_state");

CREATE INDEX "yak_offline_job_definition_idx_yak_offline_schedule" ON "yak_offline_job_definition" ("schedule_enabled", "cron_expression");

CREATE INDEX "yak_offline_job_definition_idx_yak_offline_schedule_next" ON "yak_offline_job_definition" ("schedule_enabled", "schedule_next_fire_time");

CREATE INDEX "yak_offline_job_definition_idx_yak_offline_update_time" ON "yak_offline_job_definition" ("update_time");

CREATE UNIQUE INDEX "yak_offline_job_definition_uk_yak_offline_project_job_name" ON "yak_offline_job_definition" ("project_id", "job_name");

CREATE TRIGGER "yak_offline_job_definition_touch" BEFORE UPDATE ON "yak_offline_job_definition" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_offline_batch_execution" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "job_definition_id" bigint NOT NULL,
  "batch_key" citext NOT NULL CHECK (length("batch_key") <= 512),
  "trigger_type" citext NOT NULL CHECK (length("trigger_type") <= 32),
  "batch_scope_type" citext NOT NULL CHECK (length("batch_scope_type") <= 32),
  "batch_scope_value" text NOT NULL,
  "batch_scope_fingerprint" citext NOT NULL CHECK (length("batch_scope_fingerprint") <= 64),
  "definition_snapshot_json" text NOT NULL,
  "definition_revision" integer NOT NULL,
  "retry_max_attempts" integer NOT NULL,
  "retry_backoff_seconds" integer NOT NULL,
  "config_digest" citext NOT NULL CHECK (length("config_digest") <= 64),
  "logical_job_spec_json" text,
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "audit_carrier_json" text,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_offline_batch_execution_idx_yak_offline_batch_proj_058d0075" ON "yak_offline_batch_execution" ("project_id", "status", "update_time");

CREATE INDEX "yak_offline_batch_execution_idx_yak_offline_batch_project_task" ON "yak_offline_batch_execution" ("project_id", "job_definition_id", "id");

CREATE INDEX "yak_offline_batch_execution_idx_yak_offline_batch_scope" ON "yak_offline_batch_execution" ("batch_scope_fingerprint");

CREATE INDEX "yak_offline_batch_execution_idx_yak_offline_batch_task_status" ON "yak_offline_batch_execution" ("job_definition_id", "status", "id");

CREATE INDEX "yak_offline_batch_execution_idx_yak_offline_batch_trig_c04d7a4d" ON "yak_offline_batch_execution" ("trigger_type", "status", "id");

CREATE UNIQUE INDEX "yak_offline_batch_execution_uk_yak_offline_batch_task_key" ON "yak_offline_batch_execution" ("job_definition_id", "batch_key");

CREATE TRIGGER "yak_offline_batch_execution_touch" BEFORE UPDATE ON "yak_offline_batch_execution" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_offline_job_execution" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "job_definition_id" bigint NOT NULL,
  "batch_id" bigint,
  "definition_version" integer DEFAULT 1 NOT NULL,
  "engine_base_url" citext NOT NULL CHECK (length("engine_base_url") <= 500),
  "engine_job_id" citext CHECK (length("engine_job_id") <= 128),
  "external_execution_id" citext NOT NULL CHECK (length("external_execution_id") <= 128),
  "idempotency_key" citext NOT NULL CHECK (length("idempotency_key") <= 128),
  "worker_instance_id" citext CHECK (length("worker_instance_id") <= 128),
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "state_version" bigint DEFAULT 1 NOT NULL,
  "attempt_no" integer DEFAULT 1 NOT NULL,
  "trigger_type" citext DEFAULT 'MANUAL' NOT NULL CHECK (length("trigger_type") <= 16),
  "retry_from_execution_id" bigint,
  "cancellation_requested" smallint DEFAULT 0 NOT NULL,
  "retry_created" smallint DEFAULT 0 NOT NULL,
  "next_retry_time" timestamp(3) without time zone,
  "config_digest" citext CHECK (length("config_digest") <= 64),
  "definition_snapshot_json" text NOT NULL,
  "submitted_config" text NOT NULL,
  "engine_snapshot_json" text,
  "error_message" text,
  "source_record_count" bigint DEFAULT 0 NOT NULL,
  "sink_attempted_record_count" bigint DEFAULT 0 NOT NULL,
  "sink_success_record_count" bigint DEFAULT 0 NOT NULL,
  "sink_committed_record_count" bigint DEFAULT 0 NOT NULL,
  "source_read_bytes" bigint DEFAULT 0 NOT NULL,
  "sink_written_bytes" bigint DEFAULT 0 NOT NULL,
  "source_average_qps" double precision DEFAULT 0 NOT NULL,
  "sink_average_qps" double precision DEFAULT 0 NOT NULL,
  "failed_record_count" bigint DEFAULT 0 NOT NULL,
  "skipped_record_count" bigint DEFAULT 0 NOT NULL,
  "database_commit_millis" bigint DEFAULT 0 NOT NULL,
  "sql_execution_millis" bigint DEFAULT 0 NOT NULL,
  "qps" double precision DEFAULT 0 NOT NULL,
  "duration_millis" bigint DEFAULT 0 NOT NULL,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "start_time" timestamp(3) without time zone,
  "end_time" timestamp(3) without time zone,
  "last_sync_time" timestamp(3) without time zone,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_offline_job_execution_idx_yak_offline_execution_batch" ON "yak_offline_job_execution" ("batch_id", "attempt_no", "id");

CREATE INDEX "yak_offline_job_execution_idx_yak_offline_execution_created" ON "yak_offline_job_execution" ("create_time", "id");

CREATE INDEX "yak_offline_job_execution_idx_yak_offline_execution_definition" ON "yak_offline_job_execution" ("job_definition_id", "id");

CREATE INDEX "yak_offline_job_execution_idx_yak_offline_execution_pr_e45b89c7" ON "yak_offline_job_execution" ("project_id", "create_time", "id");

CREATE INDEX "yak_offline_job_execution_idx_yak_offline_execution_pr_5d05aa80" ON "yak_offline_job_execution" ("project_id", "status", "last_sync_time");

CREATE INDEX "yak_offline_job_execution_idx_yak_offline_execution_pr_f330c257" ON "yak_offline_job_execution" ("project_id", "job_definition_id", "id");

CREATE INDEX "yak_offline_job_execution_idx_yak_offline_execution_retry" ON "yak_offline_job_execution" ("retry_created", "next_retry_time");

CREATE INDEX "yak_offline_job_execution_idx_yak_offline_execution_status" ON "yak_offline_job_execution" ("status", "last_sync_time");

CREATE UNIQUE INDEX "yak_offline_job_execution_uk_yak_offline_external_execution" ON "yak_offline_job_execution" ("external_execution_id");

CREATE UNIQUE INDEX "yak_offline_job_execution_uk_yak_offline_idempotency" ON "yak_offline_job_execution" ("idempotency_key");

CREATE TRIGGER "yak_offline_job_execution_touch" BEFORE UPDATE ON "yak_offline_job_execution" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_offline_execution_event" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "execution_id" bigint NOT NULL,
  "state_version" bigint NOT NULL,
  "from_status" citext CHECK (length("from_status") <= 32),
  "to_status" citext CHECK (length("to_status") <= 32),
  "event_type" citext NOT NULL CHECK (length("event_type") <= 64),
  "message" text,
  "payload_json" text,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_offline_execution_event_idx_yak_offline_event_execution" ON "yak_offline_execution_event" ("execution_id", "id");

CREATE TABLE "yak_offline_sync_cursor" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "job_definition_id" bigint NOT NULL,
  "cursor_id" citext NOT NULL CHECK (length("cursor_id") <= 128),
  "source_column" citext NOT NULL CHECK (length("source_column") <= 256),
  "source_signature" citext CHECK (length("source_signature") <= 64),
  "position_value" citext NOT NULL CHECK (length("position_value") <= 1024),
  "last_succeeded_batch_id" bigint,
  "state_version" bigint DEFAULT 1 NOT NULL,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_offline_sync_cursor_idx_yak_offline_cursor_last_batch" ON "yak_offline_sync_cursor" ("last_succeeded_batch_id");

CREATE UNIQUE INDEX "yak_offline_sync_cursor_uk_yak_offline_cursor_task_id" ON "yak_offline_sync_cursor" ("job_definition_id", "cursor_id");

CREATE TRIGGER "yak_offline_sync_cursor_touch" BEFORE UPDATE ON "yak_offline_sync_cursor" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_offline_job_revision" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "job_definition_id" bigint NOT NULL,
  "version_no" integer NOT NULL,
  "definition_json" text NOT NULL,
  "job_spec_json" text NOT NULL,
  "config_digest" citext NOT NULL CHECK (length("config_digest") <= 64),
  "checksum" citext CHECK (length("checksum") <= 64),
  "source_version" integer,
  "created_by" citext CHECK (length("created_by") <= 64),
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_offline_job_revision_idx_yak_offline_revision_idem" ON "yak_offline_job_revision" ("job_definition_id", "checksum");

CREATE INDEX "yak_offline_job_revision_idx_yak_offline_revision_job" ON "yak_offline_job_revision" ("job_definition_id", "id");

CREATE INDEX "yak_offline_job_revision_idx_yak_offline_revision_project" ON "yak_offline_job_revision" ("project_id");

CREATE UNIQUE INDEX "yak_offline_job_revision_uk_yak_offline_revision_version" ON "yak_offline_job_revision" ("job_definition_id", "version_no");
