-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_approval_flow" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "flow_code" citext NOT NULL CHECK (length("flow_code") <= 64),
  "flow_name" citext NOT NULL CHECK (length("flow_name") <= 128),
  "description" citext CHECK (length("description") <= 512),
  "steps_json" text NOT NULL,
  "enabled" smallint DEFAULT 1 NOT NULL,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "updated_by" citext CHECK (length("updated_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_approval_flow_idx_approval_flow_list" ON "yak_approval_flow" ("project_id", "deleted", "id");

CREATE UNIQUE INDEX "yak_approval_flow_uk_approval_flow_code" ON "yak_approval_flow" ("project_id", "flow_code");

CREATE TRIGGER "yak_approval_flow_touch" BEFORE UPDATE ON "yak_approval_flow" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_approval_instance" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "flow_code" citext NOT NULL CHECK (length("flow_code") <= 64),
  "flow_name" citext NOT NULL CHECK (length("flow_name") <= 128),
  "biz_type" citext NOT NULL CHECK (length("biz_type") <= 64),
  "biz_id" citext NOT NULL CHECK (length("biz_id") <= 64),
  "title" citext NOT NULL CHECK (length("title") <= 256),
  "payload_json" text,
  "applicant" citext NOT NULL CHECK (length("applicant") <= 64),
  "status" citext DEFAULT 'PENDING' NOT NULL CHECK (length("status") <= 16),
  "current_level" smallint DEFAULT 1 NOT NULL,
  "active_flag" citext CHECK (length("active_flag") <= 1),
  "finish_time" timestamp(6) without time zone,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "updated_by" citext CHECK (length("updated_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_approval_instance_idx_approval_inst_applicant" ON "yak_approval_instance" ("project_id", "applicant", "status");

CREATE INDEX "yak_approval_instance_idx_approval_inst_biz" ON "yak_approval_instance" ("project_id", "biz_type", "biz_id", "id");

CREATE INDEX "yak_approval_instance_idx_approval_inst_status" ON "yak_approval_instance" ("project_id", "status", "deleted");

CREATE UNIQUE INDEX "yak_approval_instance_uk_approval_inflight" ON "yak_approval_instance" ("project_id", "flow_code", "biz_type", "biz_id", "active_flag");

CREATE TRIGGER "yak_approval_instance_touch" BEFORE UPDATE ON "yak_approval_instance" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_approval_step" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "instance_id" bigint NOT NULL,
  "level_no" smallint NOT NULL,
  "approver" citext NOT NULL CHECK (length("approver") <= 64),
  "status" citext DEFAULT 'WAITING' NOT NULL CHECK (length("status") <= 16),
  "comment" citext CHECK (length("comment") <= 512),
  "handled_time" timestamp(6) without time zone,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "updated_by" citext CHECK (length("updated_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_approval_step_idx_approval_step_instance" ON "yak_approval_step" ("instance_id", "level_no");

CREATE INDEX "yak_approval_step_idx_approval_step_pending" ON "yak_approval_step" ("project_id", "approver", "status", "id");

CREATE TRIGGER "yak_approval_step_touch" BEFORE UPDATE ON "yak_approval_step" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');
