-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_compute_environment" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" citext NOT NULL CHECK (length("name") <= 120),
  "engine_type" citext DEFAULT 'FLINK_CDC' NOT NULL CHECK (length("engine_type") <= 32),
  "deployment_mode" citext DEFAULT 'REMOTE' NOT NULL CHECK (length("deployment_mode") <= 32),
  "submitter_type" citext DEFAULT 'LOCAL' NOT NULL CHECK (length("submitter_type") <= 32),
  "config_json" text NOT NULL,
  "enabled" smallint DEFAULT 1 NOT NULL,
  "is_default" smallint DEFAULT 0 NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "last_check_status" citext CHECK (length("last_check_status") <= 16),
  "last_check_message" citext CHECK (length("last_check_message") <= 500),
  "last_check_time" timestamp(3) without time zone,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_compute_environment_idx_compute_environment_default" ON "yak_compute_environment" ("is_default", "enabled");

CREATE UNIQUE INDEX "yak_compute_environment_uk_compute_environment_name" ON "yak_compute_environment" ("name");

CREATE TRIGGER "yak_compute_environment_touch" BEFORE UPDATE ON "yak_compute_environment" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_realtime_job_definition" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "job_name" citext NOT NULL CHECK (length("job_name") <= 200),
  "description" citext CHECK (length("description") <= 1000),
  "runtime_environment_id" bigint NOT NULL,
  "spec_json" text,
  "release_state" citext DEFAULT 'DRAFT' NOT NULL CHECK (length("release_state") <= 16),
  "desired_state" citext DEFAULT 'STOPPED' NOT NULL CHECK (length("desired_state") <= 16),
  "observed_state" citext DEFAULT 'STOPPED' NOT NULL CHECK (length("observed_state") <= 32),
  "definition_version" integer DEFAULT 1 NOT NULL,
  "published_version" integer,
  "published_definition_version_id" bigint,
  "config_digest" citext CHECK (length("config_digest") <= 64),
  "last_error" text,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_realtime_job_definition_idx_realtime_definition_environment" ON "yak_realtime_job_definition" ("runtime_environment_id");

CREATE INDEX "yak_realtime_job_definition_idx_realtime_project_state" ON "yak_realtime_job_definition" ("project_id", "release_state", "update_time");

CREATE INDEX "yak_realtime_job_definition_idx_realtime_published_def_5eead944" ON "yak_realtime_job_definition" ("published_definition_version_id");

CREATE INDEX "yak_realtime_job_definition_idx_realtime_states" ON "yak_realtime_job_definition" ("desired_state", "observed_state");

CREATE UNIQUE INDEX "yak_realtime_job_definition_uk_realtime_project_name" ON "yak_realtime_job_definition" ("project_id", "job_name");

CREATE TRIGGER "yak_realtime_job_definition_touch" BEFORE UPDATE ON "yak_realtime_job_definition" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_realtime_definition_version" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "task_id" bigint NOT NULL,
  "version_no" integer NOT NULL,
  "source_draft_revision" integer NOT NULL,
  "runtime_environment_id" bigint NOT NULL,
  "definition_json" text NOT NULL,
  "definition_digest" citext CHECK (length("definition_digest") <= 64),
  "source_config_digest" citext NOT NULL CHECK (length("source_config_digest") <= 64),
  "domain_mapping_state" citext NOT NULL CHECK (length("domain_mapping_state") <= 32),
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_realtime_definition_version_idx_realtime_definitio_e9eba55d" ON "yak_realtime_definition_version" ("runtime_environment_id");

CREATE INDEX "yak_realtime_definition_version_idx_realtime_definitio_cfca38f5" ON "yak_realtime_definition_version" ("task_id", "source_draft_revision");

CREATE UNIQUE INDEX "yak_realtime_definition_version_uk_realtime_definition_74ac3fdf" ON "yak_realtime_definition_version" ("task_id", "source_config_digest");

CREATE UNIQUE INDEX "yak_realtime_definition_version_uk_realtime_definition_dcdc9b5f" ON "yak_realtime_definition_version" ("task_id", "version_no");

CREATE TABLE "yak_realtime_job_deployment" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "definition_id" bigint NOT NULL,
  "definition_version_id" bigint,
  "definition_version" integer NOT NULL,
  "runtime_environment_id" bigint NOT NULL,
  "runtime_environment_version" integer NOT NULL,
  "runtime_environment_snapshot_json" text NOT NULL,
  "spec_snapshot_json" text NOT NULL,
  "spec_summary" citext CHECK (length("spec_summary") <= 1000),
  "config_digest" citext NOT NULL CHECK (length("config_digest") <= 64),
  "idempotency_key" citext NOT NULL CHECK (length("idempotency_key") <= 128),
  "engine_type" citext DEFAULT 'FLINK_CDC' NOT NULL CHECK (length("engine_type") <= 32),
  "desired_state" citext DEFAULT 'RUNNING' NOT NULL CHECK (length("desired_state") <= 16),
  "observed_state" citext DEFAULT 'STARTING' NOT NULL CHECK (length("observed_state") <= 32),
  "runtime_job_name" citext CHECK (length("runtime_job_name") <= 128),
  "runtime_identity_state" citext DEFAULT 'REQUIRED' NOT NULL CHECK (length("runtime_identity_state") <= 16),
  "gateway_job_id" citext CHECK (length("gateway_job_id") <= 128),
  "runtime_version" citext CHECK (length("runtime_version") <= 64),
  "runtime_revision" citext CHECK (length("runtime_revision") <= 128),
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "result_uncertain" smallint DEFAULT 0 NOT NULL,
  "error_message" text,
  "replacement_command_type" citext CHECK (length("replacement_command_type") <= 32),
  "replacement_target_definition_version_id" bigint,
  "replacement_idempotency_key" citext CHECK (length("replacement_idempotency_key") <= 128),
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_realtime_job_deployment_idx_realtime_deployment_definition" ON "yak_realtime_job_deployment" ("definition_id", "id");

CREATE INDEX "yak_realtime_job_deployment_idx_realtime_deployment_de_eb401aaa" ON "yak_realtime_job_deployment" ("definition_version_id", "id");

CREATE INDEX "yak_realtime_job_deployment_idx_realtime_deployment_environment" ON "yak_realtime_job_deployment" ("runtime_environment_id");

CREATE INDEX "yak_realtime_job_deployment_idx_realtime_deployment_pr_f3d8ea44" ON "yak_realtime_job_deployment" ("project_id", "definition_id", "id");

CREATE INDEX "yak_realtime_job_deployment_idx_realtime_deployment_pr_d5d536df" ON "yak_realtime_job_deployment" ("project_id", "observed_state", "update_time");

CREATE INDEX "yak_realtime_job_deployment_idx_realtime_execution_state" ON "yak_realtime_job_deployment" ("definition_id", "observed_state", "id");

CREATE INDEX "yak_realtime_job_deployment_idx_realtime_replacement_pending" ON "yak_realtime_job_deployment" ("definition_id", "replacement_idempotency_key", "id");

CREATE UNIQUE INDEX "yak_realtime_job_deployment_uk_realtime_project_idempotency" ON "yak_realtime_job_deployment" ("project_id", "idempotency_key");

CREATE UNIQUE INDEX "yak_realtime_job_deployment_uk_realtime_runtime_job_name" ON "yak_realtime_job_deployment" ("runtime_job_name");

CREATE TRIGGER "yak_realtime_job_deployment_touch" BEFORE UPDATE ON "yak_realtime_job_deployment" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_realtime_job_event" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "definition_id" bigint NOT NULL,
  "deployment_id" bigint,
  "event_type" citext NOT NULL CHECK (length("event_type") <= 64),
  "from_state" citext CHECK (length("from_state") <= 32),
  "to_state" citext CHECK (length("to_state") <= 32),
  "message" text,
  "payload_json" text,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_realtime_job_event_idx_realtime_event_definition" ON "yak_realtime_job_event" ("definition_id", "id");

CREATE TABLE "yak_realtime_runtime_lease" (
  "id" smallint NOT NULL,
  "lease_owner" citext CHECK (length("lease_owner") <= 128),
  "lease_until" timestamp(3) without time zone,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TRIGGER "yak_realtime_runtime_lease_touch" BEFORE UPDATE ON "yak_realtime_runtime_lease" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

INSERT INTO "yak_realtime_runtime_lease" ("id", "lease_owner", "lease_until") VALUES ('1', NULL, '1970-01-01 00:00:00');
