-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_dsec_security_level" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "level_code" citext NOT NULL CHECK (length("level_code") <= 32),
  "level_name" citext NOT NULL CHECK (length("level_name") <= 64),
  "rank_no" integer DEFAULT 0 NOT NULL,
  "std_security_id" bigint,
  "description" citext CHECK (length("description") <= 512),
  "status" citext DEFAULT 'DRAFT' NOT NULL CHECK (length("status") <= 16),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dsec_security_level_idx_dsec_level_rank" ON "yak_dsec_security_level" ("project_id", "rank_no");

CREATE UNIQUE INDEX "yak_dsec_security_level_uk_dsec_level" ON "yak_dsec_security_level" ("project_id", "level_code");

CREATE TRIGGER "yak_dsec_security_level_touch" BEFORE UPDATE ON "yak_dsec_security_level" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_dsec_data_category" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "category_code" citext NOT NULL CHECK (length("category_code") <= 64),
  "category_name" citext NOT NULL CHECK (length("category_name") <= 128),
  "parent_code" citext CHECK (length("parent_code") <= 64),
  "sort_order" integer DEFAULT 0 NOT NULL,
  "description" citext CHECK (length("description") <= 512),
  "status" citext DEFAULT 'ACTIVE' NOT NULL CHECK (length("status") <= 16),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_dsec_data_category_uk_dsec_category" ON "yak_dsec_data_category" ("project_id", "category_code");

CREATE TRIGGER "yak_dsec_data_category_touch" BEFORE UPDATE ON "yak_dsec_data_category" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_dsec_classification" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "object_type" citext NOT NULL CHECK (length("object_type") <= 16),
  "object_key" citext NOT NULL CHECK (length("object_key") <= 512),
  "datasource_id" bigint,
  "db_name" citext CHECK (length("db_name") <= 128),
  "table_name" citext CHECK (length("table_name") <= 128),
  "column_name" citext CHECK (length("column_name") <= 128),
  "object_name" citext CHECK (length("object_name") <= 256),
  "level_id" bigint NOT NULL,
  "category_id" bigint,
  "source" citext DEFAULT 'MANUAL' NOT NULL CHECK (length("source") <= 16),
  "confidence" integer DEFAULT 100 NOT NULL,
  "discovery_rule_id" bigint,
  "status" citext DEFAULT 'ACTIVE' NOT NULL CHECK (length("status") <= 16),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dsec_classification_idx_dsec_classification_level" ON "yak_dsec_classification" ("project_id", "level_id");

CREATE UNIQUE INDEX "yak_dsec_classification_uk_dsec_classification" ON "yak_dsec_classification" ("project_id", "object_key");

CREATE TRIGGER "yak_dsec_classification_touch" BEFORE UPDATE ON "yak_dsec_classification" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_dsec_discovery_rule" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "rule_code" citext NOT NULL CHECK (length("rule_code") <= 64),
  "rule_name" citext NOT NULL CHECK (length("rule_name") <= 128),
  "match_type" citext NOT NULL CHECK (length("match_type") <= 16),
  "pattern" citext NOT NULL CHECK (length("pattern") <= 512),
  "level_id" bigint NOT NULL,
  "category_id" bigint,
  "enabled" smallint DEFAULT 1 NOT NULL,
  "description" citext CHECK (length("description") <= 512),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_dsec_discovery_rule_uk_dsec_discovery_rule" ON "yak_dsec_discovery_rule" ("project_id", "rule_code");

CREATE TRIGGER "yak_dsec_discovery_rule_touch" BEFORE UPDATE ON "yak_dsec_discovery_rule" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_dsec_access_policy" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "policy_name" citext NOT NULL CHECK (length("policy_name") <= 128),
  "subject_type" citext NOT NULL CHECK (length("subject_type") <= 16),
  "subject_key" citext NOT NULL CHECK (length("subject_key") <= 128),
  "scope_type" citext NOT NULL CHECK (length("scope_type") <= 16),
  "datasource_id" bigint,
  "db_name" citext CHECK (length("db_name") <= 128),
  "table_name" citext CHECK (length("table_name") <= 128),
  "column_name" citext CHECK (length("column_name") <= 128),
  "level_id" bigint,
  "access_type" citext DEFAULT 'READ' NOT NULL CHECK (length("access_type") <= 16),
  "effect" citext DEFAULT 'ALLOW' NOT NULL CHECK (length("effect") <= 16),
  "priority" integer DEFAULT 0 NOT NULL,
  "valid_from" timestamp(6) without time zone,
  "valid_to" timestamp(6) without time zone,
  "status" citext DEFAULT 'PENDING' NOT NULL CHECK (length("status") <= 16),
  "applicant" citext CHECK (length("applicant") <= 64),
  "approver" citext CHECK (length("approver") <= 64),
  "reason" citext CHECK (length("reason") <= 512),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dsec_access_policy_idx_dsec_policy_status" ON "yak_dsec_access_policy" ("project_id", "status");

CREATE INDEX "yak_dsec_access_policy_idx_dsec_policy_subject" ON "yak_dsec_access_policy" ("project_id", "subject_type", "subject_key");

CREATE TRIGGER "yak_dsec_access_policy_touch" BEFORE UPDATE ON "yak_dsec_access_policy" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_dsec_masking_algorithm" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "algo_code" citext NOT NULL CHECK (length("algo_code") <= 32),
  "algo_name" citext NOT NULL CHECK (length("algo_name") <= 64),
  "params" citext CHECK (length("params") <= 1024),
  "builtin" smallint DEFAULT 0 NOT NULL,
  "description" citext CHECK (length("description") <= 512),
  "status" citext DEFAULT 'ACTIVE' NOT NULL CHECK (length("status") <= 16),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_dsec_masking_algorithm_uk_dsec_algo" ON "yak_dsec_masking_algorithm" ("project_id", "algo_code");

CREATE TRIGGER "yak_dsec_masking_algorithm_touch" BEFORE UPDATE ON "yak_dsec_masking_algorithm" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_dsec_masking_policy" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "policy_name" citext NOT NULL CHECK (length("policy_name") <= 128),
  "level_id" bigint,
  "category_id" bigint,
  "column_pattern" citext CHECK (length("column_pattern") <= 128),
  "algo_id" bigint NOT NULL,
  "priority" integer DEFAULT 0 NOT NULL,
  "enabled" smallint DEFAULT 1 NOT NULL,
  "description" citext CHECK (length("description") <= 512),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dsec_masking_policy_idx_dsec_masking_policy" ON "yak_dsec_masking_policy" ("project_id", "enabled");

CREATE TRIGGER "yak_dsec_masking_policy_touch" BEFORE UPDATE ON "yak_dsec_masking_policy" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_dsec_access_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "access_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "actor" citext NOT NULL CHECK (length("actor") <= 64),
  "resource_type" citext NOT NULL CHECK (length("resource_type") <= 16),
  "resource_key" citext NOT NULL CHECK (length("resource_key") <= 512),
  "resource_name" citext CHECK (length("resource_name") <= 256),
  "action" citext NOT NULL CHECK (length("action") <= 16),
  "level_code" citext CHECK (length("level_code") <= 32),
  "decision" citext NOT NULL CHECK (length("decision") <= 16),
  "masked" smallint DEFAULT 0 NOT NULL,
  "algo_code" citext CHECK (length("algo_code") <= 32),
  "source" citext CHECK (length("source") <= 32),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dsec_access_log_idx_dsec_log_actor" ON "yak_dsec_access_log" ("project_id", "actor");

CREATE INDEX "yak_dsec_access_log_idx_dsec_log_decision" ON "yak_dsec_access_log" ("project_id", "decision");

CREATE INDEX "yak_dsec_access_log_idx_dsec_log_time" ON "yak_dsec_access_log" ("project_id", "access_time");

CREATE TABLE "yak_dsec_compliance_rule" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "rule_code" citext NOT NULL CHECK (length("rule_code") <= 64),
  "rule_name" citext NOT NULL CHECK (length("rule_name") <= 128),
  "rule_type" citext NOT NULL CHECK (length("rule_type") <= 32),
  "params" citext CHECK (length("params") <= 1024),
  "severity" citext DEFAULT 'MEDIUM' NOT NULL CHECK (length("severity") <= 16),
  "enabled" smallint DEFAULT 1 NOT NULL,
  "description" citext CHECK (length("description") <= 512),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_dsec_compliance_rule_uk_dsec_compliance_rule" ON "yak_dsec_compliance_rule" ("project_id", "rule_code");

CREATE TRIGGER "yak_dsec_compliance_rule_touch" BEFORE UPDATE ON "yak_dsec_compliance_rule" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_dsec_compliance_finding" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "batch_id" citext NOT NULL CHECK (length("batch_id") <= 64),
  "rule_id" bigint NOT NULL,
  "rule_type" citext NOT NULL CHECK (length("rule_type") <= 32),
  "target_key" citext CHECK (length("target_key") <= 512),
  "target_name" citext CHECK (length("target_name") <= 256),
  "passed" smallint DEFAULT 1 NOT NULL,
  "finding" citext CHECK (length("finding") <= 512),
  "severity" citext DEFAULT 'MEDIUM' NOT NULL CHECK (length("severity") <= 16),
  "checked_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_dsec_compliance_finding_idx_dsec_finding_batch" ON "yak_dsec_compliance_finding" ("project_id", "batch_id");

CREATE INDEX "yak_dsec_compliance_finding_idx_dsec_finding_passed" ON "yak_dsec_compliance_finding" ("project_id", "passed");
