-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_mdm_entity" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "entity_code" citext NOT NULL CHECK (length("entity_code") <= 64),
  "entity_name" citext NOT NULL CHECK (length("entity_name") <= 128),
  "status" citext DEFAULT 'DRAFT' NOT NULL CHECK (length("status") <= 16),
  "owner" citext CHECK (length("owner") <= 64),
  "description" citext CHECK (length("description") <= 512),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_mdm_entity_idx_yak_mdm_entity_status" ON "yak_mdm_entity" ("project_id", "status");

CREATE UNIQUE INDEX "yak_mdm_entity_uk_yak_mdm_entity" ON "yak_mdm_entity" ("project_id", "entity_code");

CREATE TRIGGER "yak_mdm_entity_touch" BEFORE UPDATE ON "yak_mdm_entity" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_mdm_attribute" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "entity_id" bigint NOT NULL,
  "attr_code" citext NOT NULL CHECK (length("attr_code") <= 64),
  "attr_name" citext NOT NULL CHECK (length("attr_name") <= 128),
  "attr_type" citext NOT NULL CHECK (length("attr_type") <= 16),
  "data_type" citext CHECK (length("data_type") <= 64),
  "std_type_id" bigint,
  "std_unit_id" bigint,
  "std_code_set_code" citext CHECK (length("std_code_set_code") <= 64),
  "std_security_id" bigint,
  "is_required" smallint DEFAULT 0 NOT NULL,
  "business_desc" citext CHECK (length("business_desc") <= 512),
  "sort_order" integer DEFAULT 0 NOT NULL,
  "status" citext DEFAULT 'ENABLED' NOT NULL CHECK (length("status") <= 16),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_mdm_attribute_idx_yak_mdm_attribute_entity" ON "yak_mdm_attribute" ("project_id", "entity_id");

CREATE UNIQUE INDEX "yak_mdm_attribute_uk_yak_mdm_attribute" ON "yak_mdm_attribute" ("project_id", "entity_id", "attr_code");

CREATE TRIGGER "yak_mdm_attribute_touch" BEFORE UPDATE ON "yak_mdm_attribute" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_mdm_source" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "entity_id" bigint NOT NULL,
  "datasource_id" bigint NOT NULL,
  "source_database" citext CHECK (length("source_database") <= 128),
  "source_schema" citext CHECK (length("source_schema") <= 128),
  "source_table" citext NOT NULL CHECK (length("source_table") <= 128),
  "field_mapping" jsonb,
  "source_role" citext DEFAULT 'MAIN' NOT NULL CHECK (length("source_role") <= 16),
  "status" citext DEFAULT 'ENABLED' NOT NULL CHECK (length("status") <= 16),
  "sort_order" integer DEFAULT 0 NOT NULL,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_mdm_source_idx_yak_mdm_source_entity" ON "yak_mdm_source" ("project_id", "entity_id");

CREATE UNIQUE INDEX "yak_mdm_source_uk_yak_mdm_source" ON "yak_mdm_source" ("project_id", "entity_id", "datasource_id", "source_database", "source_schema", "source_table");

CREATE TRIGGER "yak_mdm_source_touch" BEFORE UPDATE ON "yak_mdm_source" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_mdm_record" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "entity_id" bigint NOT NULL,
  "master_id" citext NOT NULL CHECK (length("master_id") <= 64),
  "attributes" jsonb NOT NULL,
  "source_ids" jsonb NOT NULL,
  "status" citext DEFAULT 'ACTIVE' NOT NULL CHECK (length("status") <= 16),
  "version" integer DEFAULT 1 NOT NULL,
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "attribute_overrides" jsonb,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_mdm_record_idx_yak_mdm_record_entity" ON "yak_mdm_record" ("project_id", "entity_id");

CREATE INDEX "yak_mdm_record_idx_yak_mdm_record_status" ON "yak_mdm_record" ("project_id", "status");

CREATE UNIQUE INDEX "yak_mdm_record_uk_yak_mdm_record" ON "yak_mdm_record" ("project_id", "entity_id", "master_id");

CREATE TRIGGER "yak_mdm_record_touch" BEFORE UPDATE ON "yak_mdm_record" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_mdm_clean_rule" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "entity_id" bigint NOT NULL,
  "rule_type" citext DEFAULT 'DEDUP' NOT NULL CHECK (length("rule_type") <= 16),
  "rule_name" citext NOT NULL CHECK (length("rule_name") <= 128),
  "rule_expr" jsonb NOT NULL,
  "enabled" smallint DEFAULT 1 NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  "created_by" citext CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_mdm_clean_rule_idx_yak_mdm_clean_rule_entity" ON "yak_mdm_clean_rule" ("project_id", "entity_id");

CREATE INDEX "yak_mdm_clean_rule_idx_yak_mdm_clean_rule_type" ON "yak_mdm_clean_rule" ("project_id", "rule_type");

CREATE UNIQUE INDEX "yak_mdm_clean_rule_uk_yak_mdm_clean_rule_name" ON "yak_mdm_clean_rule" ("project_id", "entity_id", "rule_name");

CREATE TRIGGER "yak_mdm_clean_rule_touch" BEFORE UPDATE ON "yak_mdm_clean_rule" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_mdm_merge_log" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "entity_id" bigint NOT NULL,
  "rule_id" bigint,
  "master_record_id" bigint NOT NULL,
  "merged_record_ids" jsonb NOT NULL,
  "result" citext NOT NULL CHECK (length("result") <= 512),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_mdm_merge_log_idx_yak_mdm_merge_log_entity" ON "yak_mdm_merge_log" ("project_id", "entity_id");

CREATE INDEX "yak_mdm_merge_log_idx_yak_mdm_merge_log_master" ON "yak_mdm_merge_log" ("project_id", "master_record_id");

CREATE TABLE "yak_mdm_distribution" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "entity_id" bigint NOT NULL,
  "target_system" citext NOT NULL CHECK (length("target_system") <= 64),
  "target_name" citext DEFAULT '' NOT NULL CHECK (length("target_name") <= 128),
  "distribute_mode" citext NOT NULL CHECK (length("distribute_mode") <= 16),
  "distribute_freq" citext DEFAULT 'MANUAL' NOT NULL CHECK (length("distribute_freq") <= 32),
  "distribute_scope" citext DEFAULT 'FULL' NOT NULL CHECK (length("distribute_scope") <= 32),
  "status" citext DEFAULT 'DRAFT' NOT NULL CHECK (length("status") <= 16),
  "last_distribute_time" timestamp(0) without time zone,
  "last_distribute_count" integer DEFAULT 0,
  "last_distribute_fail" integer DEFAULT 0,
  "created_by" citext CHECK (length("created_by") <= 64),
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_mdm_distribution_idx_mdm_dist_entity" ON "yak_mdm_distribution" ("project_id", "entity_id");

CREATE UNIQUE INDEX "yak_mdm_distribution_uk_mdm_dist_target" ON "yak_mdm_distribution" ("project_id", "entity_id", "target_system", "distribute_mode");

CREATE TRIGGER "yak_mdm_distribution_touch" BEFORE UPDATE ON "yak_mdm_distribution" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_mdm_subscription" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "entity_id" bigint NOT NULL,
  "subscriber_code" citext NOT NULL CHECK (length("subscriber_code") <= 64),
  "subscriber_name" citext DEFAULT '' NOT NULL CHECK (length("subscriber_name") <= 128),
  "notify_mode" citext DEFAULT 'EVENT' NOT NULL CHECK (length("notify_mode") <= 16),
  "status" citext DEFAULT 'ACTIVE' NOT NULL CHECK (length("status") <= 16),
  "created_by" citext CHECK (length("created_by") <= 64),
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_mdm_subscription_idx_mdm_sub_entity" ON "yak_mdm_subscription" ("project_id", "entity_id");

CREATE UNIQUE INDEX "yak_mdm_subscription_uk_mdm_sub_subscriber" ON "yak_mdm_subscription" ("project_id", "entity_id", "subscriber_code");

CREATE TRIGGER "yak_mdm_subscription_touch" BEFORE UPDATE ON "yak_mdm_subscription" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_mdm_change" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "entity_id" bigint NOT NULL,
  "master_id" citext NOT NULL CHECK (length("master_id") <= 128),
  "change_type" citext NOT NULL CHECK (length("change_type") <= 16),
  "change_content" text NOT NULL,
  "approval_level" integer DEFAULT 1 NOT NULL,
  "approval_status" citext DEFAULT 'PENDING' NOT NULL CHECK (length("approval_status") <= 16),
  "applicant" citext CHECK (length("applicant") <= 64),
  "approver" citext CHECK (length("approver") <= 64),
  "approval_comment" text,
  "approval_time" timestamp(0) without time zone,
  "instance_id" bigint,
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "update_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_mdm_change_idx_mdm_change_applicant" ON "yak_mdm_change" ("project_id", "applicant");

CREATE INDEX "yak_mdm_change_idx_mdm_change_entity" ON "yak_mdm_change" ("project_id", "entity_id");

CREATE INDEX "yak_mdm_change_idx_mdm_change_master" ON "yak_mdm_change" ("project_id", "entity_id", "master_id");

CREATE INDEX "yak_mdm_change_idx_mdm_change_status" ON "yak_mdm_change" ("approval_status");

CREATE TRIGGER "yak_mdm_change_touch" BEFORE UPDATE ON "yak_mdm_change" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_mdm_collect_link" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "entity_id" bigint NOT NULL,
  "source_id" bigint NOT NULL,
  "datasource_id" bigint NOT NULL,
  "landing_table" citext NOT NULL CHECK (length("landing_table") <= 128),
  "job_definition_id" bigint NOT NULL,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_mdm_collect_link_idx_yak_mdm_collect_link_entity" ON "yak_mdm_collect_link" ("project_id", "entity_id");

CREATE UNIQUE INDEX "yak_mdm_collect_link_uk_yak_mdm_collect_link_source" ON "yak_mdm_collect_link" ("project_id", "source_id");

CREATE TRIGGER "yak_mdm_collect_link_touch" BEFORE UPDATE ON "yak_mdm_collect_link" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_mdm_record_version" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "entity_id" bigint NOT NULL,
  "master_id" citext NOT NULL CHECK (length("master_id") <= 128),
  "version" integer NOT NULL,
  "attributes" text NOT NULL,
  "status" citext NOT NULL CHECK (length("status") <= 16),
  "change_id" bigint,
  "operator" citext CHECK (length("operator") <= 64),
  "create_time" timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_mdm_record_version_idx_mdm_version_master" ON "yak_mdm_record_version" ("project_id", "entity_id", "master_id");

CREATE UNIQUE INDEX "yak_mdm_record_version_uk_mdm_version" ON "yak_mdm_record_version" ("project_id", "entity_id", "master_id", "version");

CREATE TABLE "yak_mdm_dedup_ignore" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "entity_id" bigint NOT NULL,
  "rule_id" bigint NOT NULL,
  "match_key" varchar(512) NOT NULL,
  "match_basis" citext CHECK (length("match_basis") <= 512),
  "reason" citext CHECK (length("reason") <= 255),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_mdm_dedup_ignore_idx_yak_mdm_dedup_ignore_entity" ON "yak_mdm_dedup_ignore" ("project_id", "entity_id", "rule_id");

CREATE UNIQUE INDEX "yak_mdm_dedup_ignore_uk_yak_mdm_dedup_ignore" ON "yak_mdm_dedup_ignore" ("project_id", "rule_id", "match_key");
