-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE "yak_audit_operation" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "operation_id" citext NOT NULL CHECK (length("operation_id") <= 64),
  "operation_type" citext NOT NULL CHECK (length("operation_type") <= 64),
  "operation_name" citext NOT NULL CHECK (length("operation_name") <= 128),
  "actor_id" citext CHECK (length("actor_id") <= 128),
  "actor_name" citext CHECK (length("actor_name") <= 128),
  "project_id" bigint,
  "project_name" citext CHECK (length("project_name") <= 255),
  "resource_type" citext CHECK (length("resource_type") <= 64),
  "resource_id" citext CHECK (length("resource_id") <= 128),
  "resource_name" citext CHECK (length("resource_name") <= 255),
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "source" citext NOT NULL CHECK (length("source") <= 32),
  "started_at" timestamp(3) without time zone NOT NULL,
  "finished_at" timestamp(3) without time zone,
  "root_trace_id" citext CHECK (length("root_trace_id") <= 128),
  "error_code" citext CHECK (length("error_code") <= 128),
  "summary" citext CHECK (length("summary") <= 1024),
  "metadata_json" text,
  "schema_version" integer DEFAULT 1 NOT NULL,
  "created_at" timestamp(3) without time zone NOT NULL,
  "updated_at" timestamp(3) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_audit_operation_idx_yak_audit_operation_actor" ON "yak_audit_operation" ("actor_id", "started_at");

CREATE INDEX "yak_audit_operation_idx_yak_audit_operation_project" ON "yak_audit_operation" ("project_id", "started_at");

CREATE INDEX "yak_audit_operation_idx_yak_audit_operation_resource" ON "yak_audit_operation" ("resource_type", "resource_id", "started_at");

CREATE INDEX "yak_audit_operation_idx_yak_audit_operation_status" ON "yak_audit_operation" ("status", "started_at");

CREATE UNIQUE INDEX "yak_audit_operation_uk_yak_audit_operation_id" ON "yak_audit_operation" ("operation_id");

CREATE TABLE "yak_audit_event" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "operation_id" citext NOT NULL CHECK (length("operation_id") <= 64),
  "event_type" citext NOT NULL CHECK (length("event_type") <= 64),
  "event_category" citext NOT NULL CHECK (length("event_category") <= 32),
  "event_status" citext NOT NULL CHECK (length("event_status") <= 32),
  "occurred_at" timestamp(3) without time zone NOT NULL,
  "actor_id" citext CHECK (length("actor_id") <= 128),
  "resource_type" citext CHECK (length("resource_type") <= 64),
  "resource_id" citext CHECK (length("resource_id") <= 128),
  "trace_id" citext CHECK (length("trace_id") <= 128),
  "span_id" citext CHECK (length("span_id") <= 128),
  "parent_event_id" bigint,
  "reason_code" citext CHECK (length("reason_code") <= 128),
  "event_key" citext CHECK (length("event_key") <= 160),
  "message" citext CHECK (length("message") <= 1024),
  "payload_json" text,
  "schema_version" integer DEFAULT 1 NOT NULL,
  "created_at" timestamp(3) without time zone NOT NULL,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("operation_id") REFERENCES "yak_audit_operation" ("operation_id") ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX "yak_audit_event_idx_yak_audit_event_operation" ON "yak_audit_event" ("operation_id", "occurred_at", "id");

CREATE INDEX "yak_audit_event_idx_yak_audit_event_resource" ON "yak_audit_event" ("resource_type", "resource_id", "occurred_at");

CREATE INDEX "yak_audit_event_idx_yak_audit_event_trace" ON "yak_audit_event" ("trace_id");

CREATE UNIQUE INDEX "yak_audit_event_uk_yak_audit_event_key" ON "yak_audit_event" ("operation_id", "event_key");
