-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_ops_data_source" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "name" citext NOT NULL CHECK (length("name") <= 128),
  "db_type" citext NOT NULL CHECK (length("db_type") <= 32),
  "jdbc_url" citext NOT NULL CHECK (length("jdbc_url") <= 1024),
  "environment" citext DEFAULT 'DEVELOP' NOT NULL CHECK (length("environment") <= 32),
  "conn_status" citext DEFAULT 'UNKNOWN' NOT NULL CHECK (length("conn_status") <= 32),
  "remark" citext CHECK (length("remark") <= 500),
  "connection_params" text NOT NULL,
  "original_json" text NOT NULL,
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_ops_data_source_idx_yak_ops_data_source_environment" ON "yak_ops_data_source" ("environment");

CREATE INDEX "yak_ops_data_source_idx_yak_ops_data_source_project_status" ON "yak_ops_data_source" ("project_id", "conn_status");

CREATE INDEX "yak_ops_data_source_idx_yak_ops_data_source_project_update" ON "yak_ops_data_source" ("project_id", "update_time");

CREATE INDEX "yak_ops_data_source_idx_yak_ops_data_source_status" ON "yak_ops_data_source" ("conn_status");

CREATE INDEX "yak_ops_data_source_idx_yak_ops_data_source_type" ON "yak_ops_data_source" ("db_type");

CREATE INDEX "yak_ops_data_source_idx_yak_ops_data_source_update_time" ON "yak_ops_data_source" ("update_time");

CREATE UNIQUE INDEX "yak_ops_data_source_uk_yak_ops_data_source_project_name" ON "yak_ops_data_source" ("project_id", "name");

CREATE TRIGGER "yak_ops_data_source_touch" BEFORE UPDATE ON "yak_ops_data_source" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_ops_sql_execution" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "execution_id" citext NOT NULL CHECK (length("execution_id") <= 96),
  "data_source_id" citext NOT NULL CHECK (length("data_source_id") <= 128),
  "caller" citext NOT NULL CHECK (length("caller") <= 32),
  "caller_reference" citext CHECK (length("caller_reference") <= 255),
  "operator_name" citext CHECK (length("operator_name") <= 128),
  "transaction_mode" citext NOT NULL CHECK (length("transaction_mode") <= 32),
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "statement_count" integer DEFAULT 0 NOT NULL,
  "succeeded_statement_count" integer DEFAULT 0 NOT NULL,
  "returned_rows" bigint DEFAULT 0 NOT NULL,
  "affected_rows" bigint DEFAULT 0 NOT NULL,
  "started_at" timestamp(3) without time zone NOT NULL,
  "finished_at" timestamp(3) without time zone NOT NULL,
  "duration_ms" bigint DEFAULT 0 NOT NULL,
  "error_message" citext CHECK (length("error_message") <= 1000),
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_ops_sql_execution_idx_yak_ops_sql_execution_caller_started" ON "yak_ops_sql_execution" ("caller", "started_at");

CREATE INDEX "yak_ops_sql_execution_idx_yak_ops_sql_execution_dataso_12302aa8" ON "yak_ops_sql_execution" ("data_source_id", "started_at");

CREATE INDEX "yak_ops_sql_execution_idx_yak_ops_sql_execution_duration" ON "yak_ops_sql_execution" ("duration_ms");

CREATE INDEX "yak_ops_sql_execution_idx_yak_ops_sql_execution_project_started" ON "yak_ops_sql_execution" ("project_id", "started_at");

CREATE INDEX "yak_ops_sql_execution_idx_yak_ops_sql_execution_projec_af674e81" ON "yak_ops_sql_execution" ("project_id", "status", "started_at");

CREATE INDEX "yak_ops_sql_execution_idx_yak_ops_sql_execution_started_at" ON "yak_ops_sql_execution" ("started_at");

CREATE INDEX "yak_ops_sql_execution_idx_yak_ops_sql_execution_status_started" ON "yak_ops_sql_execution" ("status", "started_at");

CREATE UNIQUE INDEX "yak_ops_sql_execution_uk_yak_ops_sql_execution_execution_id" ON "yak_ops_sql_execution" ("execution_id");

CREATE TABLE "yak_ops_sql_statement_execution" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "execution_id" citext NOT NULL CHECK (length("execution_id") <= 96),
  "statement_id" citext NOT NULL CHECK (length("statement_id") <= 128),
  "statement_index" integer NOT NULL,
  "statement_type" citext NOT NULL CHECK (length("statement_type") <= 32),
  "sql_fingerprint" citext NOT NULL CHECK (length("sql_fingerprint") <= 64),
  "sql_preview" citext NOT NULL CHECK (length("sql_preview") <= 2048),
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "result_type" citext CHECK (length("result_type") <= 32),
  "returned_rows" bigint DEFAULT 0 NOT NULL,
  "affected_rows" bigint DEFAULT 0 NOT NULL,
  "truncated" smallint DEFAULT 0 NOT NULL,
  "started_at" timestamp(3) without time zone,
  "finished_at" timestamp(3) without time zone NOT NULL,
  "duration_ms" bigint DEFAULT 0 NOT NULL,
  "error_message" citext CHECK (length("error_message") <= 1000),
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_ops_sql_statement_execution_idx_yak_ops_sql_statem_21387abe" ON "yak_ops_sql_statement_execution" ("duration_ms");

CREATE INDEX "yak_ops_sql_statement_execution_idx_yak_ops_sql_statem_70a55ae0" ON "yak_ops_sql_statement_execution" ("execution_id", "statement_index");

CREATE INDEX "yak_ops_sql_statement_execution_idx_yak_ops_sql_statem_e65bf030" ON "yak_ops_sql_statement_execution" ("sql_fingerprint");

CREATE INDEX "yak_ops_sql_statement_execution_idx_yak_ops_sql_statem_d036ef3f" ON "yak_ops_sql_statement_execution" ("statement_type", "status");

CREATE UNIQUE INDEX "yak_ops_sql_statement_execution_uk_yak_ops_sql_stateme_097ea8e9" ON "yak_ops_sql_statement_execution" ("statement_id");
