-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE "yak_analysis" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "name" citext NOT NULL CHECK (length("name") <= 200),
  "description" citext CHECK (length("description") <= 2000),
  "dataset_id" bigint NOT NULL,
  "chart_type" citext NOT NULL CHECK (length("chart_type") <= 32),
  "query_spec_json" jsonb NOT NULL,
  "visual_config_json" jsonb NOT NULL,
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_analysis_idx_yak_analysis_chart_type" ON "yak_analysis" ("chart_type");

CREATE INDEX "yak_analysis_idx_yak_analysis_dataset_update" ON "yak_analysis" ("dataset_id", "update_time");

CREATE INDEX "yak_analysis_idx_yak_analysis_project_dataset" ON "yak_analysis" ("project_id", "dataset_id");

CREATE INDEX "yak_analysis_idx_yak_analysis_project_update" ON "yak_analysis" ("project_id", "update_time", "id");
