-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_ops_consumption_subscription" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "product_key" citext NOT NULL CHECK (length("product_key") <= 255),
  "consumer_type" citext NOT NULL CHECK (length("consumer_type") <= 32),
  "source_domain" citext NOT NULL CHECK (length("source_domain") <= 64),
  "source_identity" citext NOT NULL CHECK (length("source_identity") <= 255),
  "display_hint" citext CHECK (length("display_hint") <= 255),
  "consumption_mode" citext NOT NULL CHECK (length("consumption_mode") <= 32),
  "status" citext DEFAULT 'ACTIVE' NOT NULL CHECK (length("status") <= 16),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 128),
  "created_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "updated_by" citext NOT NULL CHECK (length("updated_by") <= 128),
  "updated_at" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_ops_consumption_subscription_idx_yak_consumption_s_e0b8d665" ON "yak_ops_consumption_subscription" ("project_id", "consumer_type", "source_domain", "source_identity", "status", "updated_at", "id");

CREATE INDEX "yak_ops_consumption_subscription_idx_yak_consumption_s_5199c179" ON "yak_ops_consumption_subscription" ("project_id", "product_key", "status", "updated_at", "id");

CREATE UNIQUE INDEX "yak_ops_consumption_subscription_uk_yak_consumption_su_0f9440db" ON "yak_ops_consumption_subscription" ("project_id", "product_key", "consumer_type", "source_domain", "source_identity", "consumption_mode");

CREATE TRIGGER "yak_ops_consumption_subscription_touch" BEFORE UPDATE ON "yak_ops_consumption_subscription" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('updated_at');

CREATE TABLE "yak_ops_consumption_usage_evidence" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "product_key" citext NOT NULL CHECK (length("product_key") <= 255),
  "source_version_identity" citext NOT NULL CHECK (length("source_version_identity") <= 255),
  "source_display_version" citext CHECK (length("source_display_version") <= 255),
  "consumer_type" citext NOT NULL CHECK (length("consumer_type") <= 64),
  "source_domain" citext NOT NULL CHECK (length("source_domain") <= 128),
  "source_identity" citext NOT NULL CHECK (length("source_identity") <= 255),
  "display_hint" citext CHECK (length("display_hint") <= 255),
  "observed_at" timestamp(6) without time zone NOT NULL,
  "consumption_mode" citext NOT NULL CHECK (length("consumption_mode") <= 64),
  "outcome" citext NOT NULL CHECK (length("outcome") <= 32),
  "provider" citext NOT NULL CHECK (length("provider") <= 128),
  "provider_evidence_ref" citext NOT NULL CHECK (length("provider_evidence_ref") <= 255),
  "deduplication_id" citext NOT NULL CHECK (length("deduplication_id") <= 255),
  "normalized_at" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_ops_consumption_usage_evidence_idx_consumption_usa_f27ed0aa" ON "yak_ops_consumption_usage_evidence" ("project_id", "consumer_type", "source_domain", "source_identity", "observed_at");

CREATE INDEX "yak_ops_consumption_usage_evidence_idx_consumption_usa_1072412f" ON "yak_ops_consumption_usage_evidence" ("project_id", "product_key", "observed_at");

CREATE UNIQUE INDEX "yak_ops_consumption_usage_evidence_uk_consumption_usage_dedup" ON "yak_ops_consumption_usage_evidence" ("project_id", "deduplication_id");
