-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_ops_alert_channel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "channel_type" citext NOT NULL CHECK (length("channel_type") <= 64),
  "config_json" text NOT NULL,
  "enabled" smallint DEFAULT 1 NOT NULL,
  "conn_status" citext DEFAULT 'UNKNOWN' NOT NULL CHECK (length("conn_status") <= 32),
  "create_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "update_time" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_ops_alert_channel_uk_alert_channel_type" ON "yak_ops_alert_channel" ("channel_type");

CREATE TRIGGER "yak_ops_alert_channel_touch" BEFORE UPDATE ON "yak_ops_alert_channel" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');
