-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_md_asset_extension" (
  "asset_id" bigint NOT NULL,
  "extension" citext NOT NULL CHECK (length("extension") <= 128),
  "json_schema" citext CHECK (length("json_schema") <= 256),
  "json" jsonb NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("asset_id", "extension")
);

CREATE INDEX "yak_md_asset_extension_idx_yak_md_ext_name" ON "yak_md_asset_extension" ("extension");

CREATE TRIGGER "yak_md_asset_extension_touch" BEFORE UPDATE ON "yak_md_asset_extension" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_md_collect_job" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "job_code" citext NOT NULL CHECK (length("job_code") <= 64),
  "job_name" citext NOT NULL CHECK (length("job_name") <= 128),
  "provider_type" citext NOT NULL CHECK (length("provider_type") <= 16),
  "type_name" citext CHECK (length("type_name") <= 64),
  "data_source_id" bigint,
  "database_name" citext CHECK (length("database_name") <= 128),
  "schema_name" citext CHECK (length("schema_name") <= 128),
  "table_pattern" citext CHECK (length("table_pattern") <= 255),
  "collect_columns" smallint DEFAULT 1 NOT NULL,
  "cron_expression" citext NOT NULL CHECK (length("cron_expression") <= 64),
  "enabled" smallint DEFAULT 0 NOT NULL,
  "dry_run_passed" smallint DEFAULT 0 NOT NULL,
  "collapse_threshold_pct" integer DEFAULT 30 NOT NULL,
  "missing_rounds" integer DEFAULT 2 NOT NULL,
  "last_run_id" bigint,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "updated_by" citext CHECK (length("updated_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_md_collect_job_idx_yak_md_job_enabled" ON "yak_md_collect_job" ("project_id", "enabled", "provider_type", "deleted");

CREATE INDEX "yak_md_collect_job_idx_yak_md_job_source" ON "yak_md_collect_job" ("data_source_id", "database_name");

CREATE UNIQUE INDEX "yak_md_collect_job_uk_yak_md_job_code" ON "yak_md_collect_job" ("project_id", "job_code");

CREATE TRIGGER "yak_md_collect_job_touch" BEFORE UPDATE ON "yak_md_collect_job" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_md_collect_run" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "job_id" bigint NOT NULL,
  "provider_type" citext NOT NULL CHECK (length("provider_type") <= 16),
  "trigger_type" citext NOT NULL CHECK (length("trigger_type") <= 16),
  "dry_run" smallint DEFAULT 0 NOT NULL,
  "status" citext DEFAULT 'RUNNING' NOT NULL CHECK (length("status") <= 16),
  "cnt_total" integer DEFAULT 0 NOT NULL,
  "cnt_new" integer DEFAULT 0 NOT NULL,
  "cnt_changed" integer DEFAULT 0 NOT NULL,
  "cnt_unchanged" integer DEFAULT 0 NOT NULL,
  "cnt_gone" integer DEFAULT 0 NOT NULL,
  "cnt_partial_failed" integer DEFAULT 0 NOT NULL,
  "cursor_watermark" citext CHECK (length("cursor_watermark") <= 255),
  "scope_snapshot" jsonb,
  "error_message" citext CHECK (length("error_message") <= 2000),
  "started_at" timestamp(6) without time zone NOT NULL,
  "finished_at" timestamp(6) without time zone,
  "duration_ms" bigint,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_md_collect_run_idx_yak_md_run_job" ON "yak_md_collect_run" ("project_id", "job_id", "started_at");

CREATE INDEX "yak_md_collect_run_idx_yak_md_run_status" ON "yak_md_collect_run" ("project_id", "status", "started_at");

CREATE TABLE "yak_md_register_retry" (
  "task_id" citext NOT NULL CHECK (length("task_id") <= 36),
  "project_id" bigint NOT NULL,
  "type_name" citext NOT NULL CHECK (length("type_name") <= 64),
  "asset_key" citext NOT NULL CHECK (length("asset_key") <= 512),
  "source_id" citext NOT NULL CHECK (length("source_id") <= 200),
  "operation" citext NOT NULL CHECK (length("operation") <= 16),
  "status" citext NOT NULL CHECK (length("status") <= 16),
  "attempts" integer DEFAULT 0 NOT NULL,
  "next_attempt_time" timestamp(6) without time zone NOT NULL,
  "last_error" citext CHECK (length("last_error") <= 2000),
  "payload" jsonb,
  "source_updated_at" timestamp(6) without time zone NOT NULL,
  "create_time" timestamp(6) without time zone NOT NULL,
  "update_time" timestamp(6) without time zone NOT NULL,
  PRIMARY KEY ("task_id")
);

CREATE INDEX "yak_md_register_retry_idx_yak_md_retry_due" ON "yak_md_register_retry" ("status", "next_attempt_time");

CREATE INDEX "yak_md_register_retry_idx_yak_md_retry_project_due" ON "yak_md_register_retry" ("project_id", "status", "next_attempt_time");

CREATE UNIQUE INDEX "yak_md_register_retry_uk_yak_md_retry_change" ON "yak_md_register_retry" ("project_id", "type_name", "asset_key", "source_updated_at");

CREATE TABLE "yak_md_change" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "asset_id" bigint NOT NULL,
  "asset_key" citext NOT NULL CHECK (length("asset_key") <= 512),
  "type_name" citext NOT NULL CHECK (length("type_name") <= 64),
  "provider_type" citext NOT NULL CHECK (length("provider_type") <= 16),
  "change_type" citext NOT NULL CHECK (length("change_type") <= 24),
  "field_name" citext CHECK (length("field_name") <= 64),
  "before_value" citext CHECK (length("before_value") <= 1024),
  "after_value" citext CHECK (length("after_value") <= 1024),
  "detail" jsonb,
  "source_updated_at" timestamp(6) without time zone,
  "collect_run_id" bigint,
  "changed_by" citext NOT NULL CHECK (length("changed_by") <= 64),
  "changed_at" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_md_change_idx_yak_md_change_asset" ON "yak_md_change" ("project_id", "asset_id", "changed_at");

CREATE INDEX "yak_md_change_idx_yak_md_change_run" ON "yak_md_change" ("collect_run_id");

CREATE INDEX "yak_md_change_idx_yak_md_change_time" ON "yak_md_change" ("changed_at");

CREATE TABLE "yak_md_label" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "asset_id" bigint NOT NULL,
  "label_code" citext NOT NULL CHECK (length("label_code") <= 64),
  "label_type" citext NOT NULL CHECK (length("label_type") <= 16),
  "state" citext DEFAULT 'CONFIRMED' NOT NULL CHECK (length("state") <= 16),
  "applied_by" citext NOT NULL CHECK (length("applied_by") <= 64),
  "applied_at" timestamp(6) without time zone NOT NULL,
  "reason" citext CHECK (length("reason") <= 512),
  "derived_from" bigint,
  "expires_at" timestamp(6) without time zone,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_md_label_idx_yak_md_label_asset" ON "yak_md_label" ("asset_id");

CREATE INDEX "yak_md_label_idx_yak_md_label_expiry" ON "yak_md_label" ("expires_at");

CREATE INDEX "yak_md_label_idx_yak_md_label_state" ON "yak_md_label" ("project_id", "state", "label_type");

CREATE UNIQUE INDEX "yak_md_label_uk_yak_md_label" ON "yak_md_label" ("project_id", "asset_id", "label_code");

CREATE TABLE "yak_md_task" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "task_type" citext NOT NULL CHECK (length("task_type") <= 32),
  "asset_id" bigint NOT NULL,
  "entity_status" citext DEFAULT 'Unprocessed' NOT NULL CHECK (length("entity_status") <= 24),
  "assignee" citext CHECK (length("assignee") <= 64),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "due_date" date,
  "resolved_at" timestamp(6) without time zone,
  "resolve_note" citext CHECK (length("resolve_note") <= 512),
  "open_marker" bigint DEFAULT 0 NOT NULL,
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_md_task_idx_yak_md_task_assignee" ON "yak_md_task" ("assignee", "entity_status", "due_date");

CREATE INDEX "yak_md_task_idx_yak_md_task_project" ON "yak_md_task" ("project_id", "entity_status");

CREATE UNIQUE INDEX "yak_md_task_uk_yak_md_task_open" ON "yak_md_task" ("project_id", "task_type", "asset_id", "open_marker");

CREATE TRIGGER "yak_md_task_touch" BEFORE UPDATE ON "yak_md_task" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_md_type_def" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type_name" citext NOT NULL CHECK (length("type_name") <= 64),
  "category" citext NOT NULL CHECK (length("category") <= 16),
  "name_space" citext DEFAULT 'custom' NOT NULL CHECK (length("name_space") <= 64),
  "display_name" citext NOT NULL CHECK (length("display_name") <= 128),
  "parent_types" citext CHECK (length("parent_types") <= 256),
  "fqn_pattern" citext CHECK (length("fqn_pattern") <= 256),
  "key_separator" citext DEFAULT '.' NOT NULL CHECK (length("key_separator") <= 8),
  "schema_def" jsonb,
  "provider_bean" citext CHECK (length("provider_bean") <= 128),
  "lineage_asset_type" citext CHECK (length("lineage_asset_type") <= 32),
  "key_prefix" citext CHECK (length("key_prefix") <= 64),
  "collectible" smallint DEFAULT 0 NOT NULL,
  "search_default_weight" real DEFAULT 1 NOT NULL,
  "search_include_by_default" smallint DEFAULT 1 NOT NULL,
  "icon_url" citext CHECK (length("icon_url") <= 256),
  "color" citext CHECK (length("color") <= 24),
  "status" citext DEFAULT 'ACTIVE' NOT NULL CHECK (length("status") <= 16),
  "version" integer DEFAULT 1 NOT NULL,
  "description" citext CHECK (length("description") <= 512),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_md_type_def_idx_yak_md_type_category" ON "yak_md_type_def" ("category", "status");

CREATE INDEX "yak_md_type_def_idx_yak_md_type_collect" ON "yak_md_type_def" ("collectible", "status");

CREATE UNIQUE INDEX "yak_md_type_def_uk_yak_md_type_name" ON "yak_md_type_def" ("type_name");

CREATE TRIGGER "yak_md_type_def_touch" BEFORE UPDATE ON "yak_md_type_def" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('1', 'STRING', 'FIELD', 'platform', '字符串', NULL, NULL, '.', NULL, NULL, NULL, NULL, '0', '1.0', '1', NULL, NULL, 'ACTIVE', '1', NULL);

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('2', 'INTEGER', 'FIELD', 'platform', '整数', NULL, NULL, '.', NULL, NULL, NULL, NULL, '0', '1.0', '1', NULL, NULL, 'ACTIVE', '1', NULL);

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('3', 'NUMBER', 'FIELD', 'platform', '数值', NULL, NULL, '.', NULL, NULL, NULL, NULL, '0', '1.0', '1', NULL, NULL, 'ACTIVE', '1', NULL);

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('4', 'BOOLEAN', 'FIELD', 'platform', '布尔', NULL, NULL, '.', NULL, NULL, NULL, NULL, '0', '1.0', '1', NULL, NULL, 'ACTIVE', '1', NULL);

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('5', 'DATE', 'FIELD', 'platform', '日期', NULL, NULL, '.', NULL, NULL, NULL, NULL, '0', '1.0', '1', NULL, NULL, 'ACTIVE', '1', NULL);

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('6', 'DATETIME', 'FIELD', 'platform', '日期时间', NULL, NULL, '.', NULL, NULL, NULL, NULL, '0', '1.0', '1', NULL, NULL, 'ACTIVE', '1', NULL);

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('7', 'ENTITY_REFERENCE', 'FIELD', 'platform', '实体引用', NULL, NULL, '.', NULL, NULL, NULL, NULL, '0', '1.0', '1', NULL, NULL, 'ACTIVE', '1', '指向目录内另一实体，按类型名校验');

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('8', 'JSON', 'FIELD', 'platform', '结构化', NULL, NULL, '.', NULL, NULL, NULL, NULL, '0', '1.0', '1', NULL, NULL, 'ACTIVE', '1', '稀有大字段应落 yak_md_asset_extension，不进主表属性袋');

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('9', 'ARRAY', 'FIELD', 'platform', '数组', NULL, NULL, '.', NULL, NULL, NULL, NULL, '0', '1.0', '1', NULL, NULL, 'ACTIVE', '1', NULL);

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('10', 'databaseService', 'ENTITY', 'platform', '数据源服务', NULL, '{dataSourceName}', '.', NULL, NULL, 'DATABASE_SERVICE', 'datasource:', '1', '1.0', '1', NULL, '#5B8FF9', 'ACTIVE', '1', '一个被采集的数据源；键 datasource:{dataSourceId}');

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('11', 'database', 'ENTITY', 'platform', '数据库', 'databaseService', '{dataSourceName}.{databaseName}', '.', NULL, NULL, 'DATABASE', 'database:', '1', '1.0', '1', NULL, '#5AD8A6', 'ACTIVE', '1', '键 database:{dataSourceId}:{db}');

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('12', 'table', 'ENTITY', 'platform', '物理表', 'database', '{databaseName}.{schemaName}.{tableName}', '.', NULL, NULL, 'TABLE', 'table:', '1', '2.0', '1', NULL, '#5B8FF9', 'ACTIVE', '1', '键 table:[unresolved:]{dsId}:{db}.{schema}.{tbl}，与 TableIdentityResolver 逐字同源（ticket 134）');

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('13', 'tableColumn', 'ENTITY', 'platform', '物理列', 'table', '{databaseName}.{schemaName}.{tableName}.{columnName}', '.', NULL, NULL, 'COLUMN', 'column:', '1', '0.2', '0', NULL, '#9270CA', 'ACTIVE', '1', '列约为表 12.6 倍，默认不进检索面，以"命中 N 列"聚合露出（plan §4.6）');

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('14', 'dataModel', 'ENTITY', 'platform', '数据模型', NULL, '{layerCode}.{modelCode}', '.', NULL, 'modelEntityProvider', 'TABLE', 'modeling:model:', '0', '1.5', '1', NULL, '#F6BD16', 'ACTIVE', '1', 'modeling own，目录只存投影；键 modeling:model:{modelId} 由源域交出（现网 11 行认领）');

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('15', 'standardField', 'ENTITY', 'platform', '标准字段', 'domain', '{fieldCode}', '.', NULL, 'standardFieldEntityProvider', 'COLUMN', 'semantic:field:', '0', '1.0', '1', NULL, '#5AD8A6', 'ACTIVE', '1', 'semantic own；键 semantic:field:{fieldId}（现网 8 行认领，另有 148 条未进过图）');

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('16', 'domain', 'ENTITY', 'platform', '业务域', NULL, '{domainCode}', '.', NULL, 'domainEntityProvider', 'DOMAIN', 'semantic:domain:', '0', '1.0', '1', NULL, '#5B8FF9', 'ACTIVE', '1', 'semantic own；键 semantic:domain:{domainId}');

INSERT INTO "yak_md_type_def" ("id", "type_name", "category", "name_space", "display_name", "parent_types", "fqn_pattern", "key_separator", "schema_def", "provider_bean", "lineage_asset_type", "key_prefix", "collectible", "search_default_weight", "search_include_by_default", "icon_url", "color", "status", "version", "description") VALUES ('17', 'metric', 'ENTITY', 'platform', '指标', 'domain', '{metricCode}', '.', NULL, 'metricEntityProvider', 'METRIC', 'metric:', '0', '1.2', '1', NULL, '#F6BD16', 'ACTIVE', '1', 'metric own；键 metric:{metricId}（现网 4 行认领）');

SELECT setval(pg_get_serial_sequence('yak_md_type_def', 'id'), (SELECT MAX("id") FROM "yak_md_type_def"));

CREATE TABLE "yak_md_field_def" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type_id" bigint NOT NULL,
  "field_name" citext NOT NULL CHECK (length("field_name") <= 64),
  "field_type" citext NOT NULL CHECK (length("field_type") <= 64),
  "display_name" citext NOT NULL CHECK (length("display_name") <= 128),
  "description" citext CHECK (length("description") <= 512),
  "required" smallint DEFAULT 0 NOT NULL,
  "is_null" smallint DEFAULT 1 NOT NULL,
  "base_type" citext NOT NULL CHECK (length("base_type") <= 24),
  "entity_type_ref" citext CHECK (length("entity_type_ref") <= 64),
  "constraint_def" jsonb,
  "default_value" citext CHECK (length("default_value") <= 256),
  "searchable" smallint DEFAULT 0 NOT NULL,
  "match_type" citext DEFAULT 'text' NOT NULL CHECK (length("match_type") <= 16),
  "boost" real DEFAULT 1 NOT NULL,
  "facetable" smallint DEFAULT 0 NOT NULL,
  "storage_slot" citext CHECK (length("storage_slot") <= 32),
  "ordinal" integer DEFAULT 0 NOT NULL,
  "show_in_list" smallint DEFAULT 0 NOT NULL,
  "deprecated" smallint DEFAULT 0 NOT NULL,
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_md_field_def_idx_yak_md_field_search" ON "yak_md_field_def" ("searchable", "type_id");

CREATE INDEX "yak_md_field_def_idx_yak_md_field_slot" ON "yak_md_field_def" ("storage_slot");

CREATE UNIQUE INDEX "yak_md_field_def_uk_yak_md_field" ON "yak_md_field_def" ("type_id", "field_name");

CREATE TRIGGER "yak_md_field_def_touch" BEFORE UPDATE ON "yak_md_field_def" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('1', '10', 'dataSourceName', 'STRING', '数据源名称', NULL, '1', '1', 'STRING', NULL, NULL, NULL, '0', 'text', '1.0', '0', NULL, '10', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('2', '11', 'databaseName', 'STRING', '库名', NULL, '1', '1', 'STRING', NULL, NULL, NULL, '0', 'text', '1.0', '0', NULL, '10', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('3', '11', 'characterSet', 'STRING', '字符集', NULL, '0', '1', 'STRING', NULL, NULL, NULL, '0', 'exact', '1.0', '0', NULL, '20', '0', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('4', '12', 'databaseName', 'STRING', '所属库', NULL, '1', '1', 'STRING', NULL, NULL, NULL, '1', 'text', '1.0', '1', 's_str_2', '10', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('5', '12', 'schemaName', 'STRING', '所属 schema', NULL, '0', '1', 'STRING', NULL, NULL, NULL, '0', 'exact', '1.0', '0', NULL, '20', '0', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('6', '12', 'tableName', 'STRING', '表名', NULL, '1', '1', 'STRING', NULL, NULL, NULL, '0', 'text', '1.0', '0', NULL, '30', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('7', '12', 'tableType', 'STRING', '表类型', NULL, '0', '1', 'STRING', NULL, NULL, NULL, '0', 'exact', '1.0', '0', NULL, '40', '0', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('8', '12', 'tableComment', 'STRING', '表注释', NULL, '0', '1', 'STRING', NULL, NULL, NULL, '0', 'text', '0.8', '0', NULL, '50', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('9', '12', 'columnCount', 'INTEGER', '列数', NULL, '0', '1', 'INTEGER', NULL, NULL, NULL, '0', 'range', '1.0', '0', 's_num_1', '60', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('10', '12', 'rowCountApprox', 'INTEGER', '行数(近似)', NULL, '0', '1', 'INTEGER', NULL, NULL, NULL, '0', 'range', '1.0', '0', 's_num_2', '70', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('11', '12', 'partitioned', 'BOOLEAN', '是否分区表', NULL, '0', '1', 'BOOLEAN', NULL, NULL, NULL, '0', 'exact', '1.0', '1', 's_bool_1', '80', '0', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('12', '12', 'lastDdlTime', 'DATETIME', '最后 DDL 时间', NULL, '0', '1', 'DATETIME', NULL, NULL, NULL, '0', 'range', '1.0', '0', 's_date_1', '90', '0', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('13', '13', 'columnName', 'STRING', '列名', NULL, '1', '1', 'STRING', NULL, NULL, NULL, '0', 'text', '1.0', '0', NULL, '10', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('14', '13', 'dataType', 'STRING', '数据类型', NULL, '1', '1', 'STRING', NULL, NULL, NULL, '1', 'exact', '1.0', '1', 's_str_1', '20', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('15', '13', 'columnSize', 'INTEGER', '长度', NULL, '0', '1', 'INTEGER', NULL, NULL, NULL, '0', 'range', '1.0', '0', NULL, '30', '0', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('16', '13', 'decimalDigits', 'INTEGER', '小数位', NULL, '0', '1', 'INTEGER', NULL, NULL, NULL, '0', 'range', '1.0', '0', NULL, '40', '0', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('17', '13', 'nullable', 'BOOLEAN', '可空', NULL, '0', '1', 'BOOLEAN', NULL, NULL, NULL, '0', 'exact', '1.0', '0', NULL, '50', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('18', '13', 'ordinalPosition', 'INTEGER', '列序', NULL, '0', '1', 'INTEGER', NULL, NULL, NULL, '0', 'range', '1.0', '0', NULL, '60', '0', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('19', '13', 'primaryKey', 'BOOLEAN', '主键', NULL, '0', '1', 'BOOLEAN', NULL, NULL, NULL, '0', 'exact', '1.0', '0', NULL, '70', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('20', '13', 'columnComment', 'STRING', '列注释', NULL, '0', '1', 'STRING', NULL, NULL, NULL, '0', 'text', '0.8', '0', NULL, '80', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('21', '14', 'modelCode', 'STRING', '模型编码', NULL, '1', '1', 'STRING', NULL, NULL, NULL, '0', 'text', '1.0', '0', NULL, '10', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('22', '14', 'layerCode', 'STRING', '分层', NULL, '0', '1', 'STRING', NULL, NULL, NULL, '0', 'exact', '1.0', '1', NULL, '20', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('23', '14', 'publishState', 'STRING', '发布状态(源域)', NULL, '0', '1', 'STRING', NULL, NULL, NULL, '0', 'exact', '1.0', '0', NULL, '30', '0', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('24', '15', 'fieldCode', 'STRING', '标准编码', NULL, '1', '1', 'STRING', NULL, NULL, NULL, '0', 'text', '1.0', '0', NULL, '10', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('25', '15', 'dataType', 'STRING', '标准类型', NULL, '0', '1', 'STRING', NULL, NULL, NULL, '1', 'exact', '1.0', '1', 's_str_1', '20', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('26', '16', 'domainCode', 'STRING', '域编码', NULL, '1', '1', 'STRING', NULL, NULL, NULL, '0', 'text', '1.0', '0', NULL, '10', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('27', '17', 'metricCode', 'STRING', '指标编码', NULL, '1', '1', 'STRING', NULL, NULL, NULL, '0', 'text', '1.0', '0', NULL, '10', '1', '0');

INSERT INTO "yak_md_field_def" ("id", "type_id", "field_name", "field_type", "display_name", "description", "required", "is_null", "base_type", "entity_type_ref", "constraint_def", "default_value", "searchable", "match_type", "boost", "facetable", "storage_slot", "ordinal", "show_in_list", "deprecated") VALUES ('28', '17', 'unit', 'STRING', '单位', NULL, '0', '1', 'STRING', NULL, NULL, NULL, '0', 'exact', '1.0', '0', NULL, '20', '0', '0');

SELECT setval(pg_get_serial_sequence('yak_md_field_def', 'id'), (SELECT MAX("id") FROM "yak_md_field_def"));

ALTER TABLE yak_md_task ADD CHECK ((open_marker = 0) = (resolved_at IS NULL));
