-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_modeling_model" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "model_code" citext NOT NULL CHECK (length("model_code") <= 128),
  "model_name" citext NOT NULL CHECK (length("model_name") <= 128),
  "dialect" citext NOT NULL CHECK (length("dialect") <= 64),
  "description" citext CHECK (length("description") <= 512),
  "status" citext DEFAULT 'DRAFT' NOT NULL CHECK (length("status") <= 32),
  "directory_id" bigint DEFAULT 0 NOT NULL,
  "created_by" citext CHECK (length("created_by") <= 128),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  "deleted_by" citext CHECK (length("deleted_by") <= 128),
  "deleted_time" timestamp(6) without time zone,
  "table_name" citext CHECK (length("table_name") <= 128),
  "table_comment" citext CHECK (length("table_comment") <= 512),
  "original_code" citext CHECK (length("original_code") <= 128),
  "pk_columns" citext CHECK (length("pk_columns") <= 1024),
  "partition_type" citext CHECK (length("partition_type") <= 64),
  "partition_columns" citext CHECK (length("partition_columns") <= 1024),
  "partition_expr" citext CHECK (length("partition_expr") <= 512),
  "table_properties" citext CHECK (length("table_properties") <= 2048),
  "process_id" bigint,
  "layer_code" citext CHECK (length("layer_code") <= 32),
  "source_datasource_id" bigint,
  "source_database" citext CHECK (length("source_database") <= 128),
  "source_table" citext CHECK (length("source_table") <= 128),
  "stat_period" citext CHECK (length("stat_period") <= 8),
  "app_code" citext CHECK (length("app_code") <= 64),
  "app_name" citext CHECK (length("app_name") <= 128),
  "import_mode" citext CHECK (length("import_mode") <= 32),
  "source_model_id" bigint,
  "published_version_id" bigint,
  "latest_version_no" integer DEFAULT 0 NOT NULL,
  "domain_id" bigint,
  "updated_by" citext CHECK (length("updated_by") <= 128),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_model_idx_yak_modeling_model_code" ON "yak_modeling_model" ("project_id", "model_code");

CREATE INDEX "yak_modeling_model_idx_yak_modeling_model_deleted" ON "yak_modeling_model" ("project_id", "deleted");

CREATE INDEX "yak_modeling_model_idx_yak_modeling_model_directory" ON "yak_modeling_model" ("project_id", "directory_id");

CREATE INDEX "yak_modeling_model_idx_yak_modeling_model_domain" ON "yak_modeling_model" ("domain_id");

CREATE INDEX "yak_modeling_model_idx_yak_modeling_model_process" ON "yak_modeling_model" ("process_id");

CREATE INDEX "yak_modeling_model_idx_yak_modeling_model_project" ON "yak_modeling_model" ("project_id");

CREATE INDEX "yak_modeling_model_idx_yak_modeling_model_source" ON "yak_modeling_model" ("project_id", "source_datasource_id", "source_table");

CREATE INDEX "yak_modeling_model_idx_yak_modeling_model_source_model" ON "yak_modeling_model" ("source_model_id");

CREATE UNIQUE INDEX "yak_modeling_model_uk_yak_modeling_model_project_code" ON "yak_modeling_model" ("project_id", "model_code");

CREATE TRIGGER "yak_modeling_model_touch" BEFORE UPDATE ON "yak_modeling_model" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_modeling_directory" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "parent_id" bigint DEFAULT 0 NOT NULL,
  "name" citext NOT NULL CHECK (length("name") <= 128),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "domain_id" bigint,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_directory_idx_yak_modeling_directory_domain" ON "yak_modeling_directory" ("project_id", "domain_id");

CREATE INDEX "yak_modeling_directory_idx_yak_modeling_directory_parent" ON "yak_modeling_directory" ("project_id", "parent_id");

CREATE UNIQUE INDEX "yak_modeling_directory_uk_yak_modeling_directory_sibling" ON "yak_modeling_directory" ("project_id", "parent_id", "name");

CREATE TRIGGER "yak_modeling_directory_touch" BEFORE UPDATE ON "yak_modeling_directory" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_modeling_tag" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "name" citext NOT NULL CHECK (length("name") <= 128),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_modeling_tag_uk_yak_modeling_tag_name" ON "yak_modeling_tag" ("project_id", "name");

CREATE TABLE "yak_modeling_model_tag_rel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "model_id" bigint NOT NULL,
  "tag_id" bigint NOT NULL,
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_model_tag_rel_idx_yak_modeling_model_tag_tag" ON "yak_modeling_model_tag_rel" ("project_id", "tag_id");

CREATE UNIQUE INDEX "yak_modeling_model_tag_rel_uk_yak_modeling_model_tag" ON "yak_modeling_model_tag_rel" ("model_id", "tag_id");

CREATE TABLE "yak_modeling_model_column" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "model_id" bigint NOT NULL,
  "column_name" citext NOT NULL CHECK (length("column_name") <= 128),
  "data_type" citext NOT NULL CHECK (length("data_type") <= 64),
  "length" integer,
  "scale" integer,
  "nullable" smallint DEFAULT 1 NOT NULL,
  "default_value" citext CHECK (length("default_value") <= 256),
  "column_comment" citext CHECK (length("column_comment") <= 512),
  "business_description" citext CHECK (length("business_description") <= 512),
  "sort_order" integer DEFAULT 0 NOT NULL,
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "std_type_id" bigint,
  "std_naming_id" bigint,
  "std_code_set_code" citext CHECK (length("std_code_set_code") <= 64),
  "std_unit_id" bigint,
  "std_caliber_id" bigint,
  "std_security_id" bigint,
  "std_field_id" bigint,
  "field_role" citext CHECK (length("field_role") <= 16),
  "aggregate_func" citext CHECK (length("aggregate_func") <= 16),
  "transform_expr" citext CHECK (length("transform_expr") <= 1024),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_model_column_idx_yak_modeling_model_column_model" ON "yak_modeling_model_column" ("project_id", "model_id");

CREATE INDEX "yak_modeling_model_column_idx_yak_modeling_model_column_std" ON "yak_modeling_model_column" ("project_id", "std_field_id");

CREATE INDEX "yak_modeling_model_column_idx_yak_modeling_model_colum_9be558c5" ON "yak_modeling_model_column" ("std_type_id");

CREATE UNIQUE INDEX "yak_modeling_model_column_uk_yak_modeling_model_column" ON "yak_modeling_model_column" ("model_id", "column_name");

CREATE TRIGGER "yak_modeling_model_column_touch" BEFORE UPDATE ON "yak_modeling_model_column" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_modeling_model_index" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "model_id" bigint NOT NULL,
  "index_name" citext NOT NULL CHECK (length("index_name") <= 128),
  "unique_index" smallint DEFAULT 0 NOT NULL,
  "index_type" citext CHECK (length("index_type") <= 64),
  "column_names" citext NOT NULL CHECK (length("column_names") <= 1024),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_model_index_idx_yak_modeling_model_index_model" ON "yak_modeling_model_index" ("project_id", "model_id");

CREATE UNIQUE INDEX "yak_modeling_model_index_uk_yak_modeling_model_index" ON "yak_modeling_model_index" ("model_id", "index_name");

CREATE TRIGGER "yak_modeling_model_index_touch" BEFORE UPDATE ON "yak_modeling_model_index" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_modeling_column_mapping" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "model_id" bigint NOT NULL,
  "target_column" citext NOT NULL CHECK (length("target_column") <= 128),
  "source_datasource_id" bigint,
  "source_database" citext CHECK (length("source_database") <= 128),
  "source_table" citext CHECK (length("source_table") <= 128),
  "source_column" citext CHECK (length("source_column") <= 128),
  "transform_expr" citext CHECK (length("transform_expr") <= 1024),
  "std_process_field_id" bigint,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_column_mapping_idx_yak_modeling_column_ma_ac4c44a7" ON "yak_modeling_column_mapping" ("project_id", "model_id");

CREATE UNIQUE INDEX "yak_modeling_column_mapping_uk_yak_modeling_column_mapping" ON "yak_modeling_column_mapping" ("project_id", "model_id", "target_column");

CREATE TRIGGER "yak_modeling_column_mapping_touch" BEFORE UPDATE ON "yak_modeling_column_mapping" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_modeling_layer_field_mapping" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "model_id" bigint NOT NULL,
  "process_field_id" bigint,
  "layer_id" bigint NOT NULL,
  "layer_field_name" citext NOT NULL CHECK (length("layer_field_name") <= 128),
  "layer_data_type" citext CHECK (length("layer_data_type") <= 64),
  "source_field" citext CHECK (length("source_field") <= 256),
  "transform_expr" citext CHECK (length("transform_expr") <= 1024),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "field_role" citext CHECK (length("field_role") <= 16),
  "aggregate_func" citext CHECK (length("aggregate_func") <= 16),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_layer_field_mapping_idx_yak_modeling_lfm_field" ON "yak_modeling_layer_field_mapping" ("project_id", "process_field_id");

CREATE INDEX "yak_modeling_layer_field_mapping_idx_yak_modeling_lfm_layer" ON "yak_modeling_layer_field_mapping" ("project_id", "layer_id");

CREATE UNIQUE INDEX "yak_modeling_layer_field_mapping_uk_yak_modeling_lfm" ON "yak_modeling_layer_field_mapping" ("project_id", "model_id", "process_field_id", "layer_id", "layer_field_name");

CREATE TRIGGER "yak_modeling_layer_field_mapping_touch" BEFORE UPDATE ON "yak_modeling_layer_field_mapping" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_modeling_model_version" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "model_id" bigint NOT NULL,
  "version_no" integer NOT NULL,
  "structure_json" text NOT NULL,
  "column_count" integer DEFAULT 0 NOT NULL,
  "checksum" citext NOT NULL CHECK (length("checksum") <= 64),
  "published_by" citext CHECK (length("published_by") <= 128),
  "publish_time" timestamp(6) without time zone NOT NULL,
  "meta_json" text,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_model_version_idx_modeling_version_model_time" ON "yak_modeling_model_version" ("model_id", "publish_time");

CREATE UNIQUE INDEX "yak_modeling_model_version_uk_modeling_version_model_no" ON "yak_modeling_model_version" ("model_id", "version_no");

CREATE TABLE "yak_modeling_lifecycle_record" (
  "id" bigint NOT NULL,
  "object_type" citext NOT NULL CHECK (length("object_type") <= 64),
  "object_id" bigint NOT NULL,
  "from_status" citext CHECK (length("from_status") <= 32),
  "to_status" citext NOT NULL CHECK (length("to_status") <= 32),
  "operator" citext CHECK (length("operator") <= 64),
  "reason" citext CHECK (length("reason") <= 512),
  "create_time" timestamp(0) without time zone,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_lifecycle_record_idx_lifecycle_object" ON "yak_modeling_lifecycle_record" ("object_type", "object_id");

CREATE TABLE "yak_modeling_impact_record" (
  "id" bigint NOT NULL,
  "source_object_type" citext NOT NULL CHECK (length("source_object_type") <= 64),
  "source_object_id" bigint NOT NULL,
  "target_object_type" citext NOT NULL CHECK (length("target_object_type") <= 64),
  "target_object_id" bigint NOT NULL,
  "impact_type" citext NOT NULL CHECK (length("impact_type") <= 32),
  "description" citext CHECK (length("description") <= 512),
  "create_time" timestamp(0) without time zone NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "yak_modeling_logical_model" (
  "id" bigint NOT NULL,
  "code" citext NOT NULL CHECK (length("code") <= 128),
  "name" citext NOT NULL CHECK (length("name") <= 256),
  "description" citext CHECK (length("description") <= 1024),
  "domain_id" bigint,
  "owner" citext CHECK (length("owner") <= 128),
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "create_time" timestamp(0) without time zone,
  "update_time" timestamp(0) without time zone,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_logical_model_idx_logical_model_domain_id" ON "yak_modeling_logical_model" ("domain_id");

CREATE TABLE "yak_modeling_logical_entity" (
  "id" bigint NOT NULL,
  "logical_model_id" bigint NOT NULL,
  "code" citext NOT NULL CHECK (length("code") <= 128),
  "name" citext NOT NULL CHECK (length("name") <= 256),
  "business_name" citext CHECK (length("business_name") <= 256),
  "description" citext CHECK (length("description") <= 1024),
  "owner" citext CHECK (length("owner") <= 128),
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "create_time" timestamp(0) without time zone,
  "update_time" timestamp(0) without time zone,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_logical_entity_idx_logical_entity_model_id" ON "yak_modeling_logical_entity" ("logical_model_id");

CREATE TABLE "yak_modeling_logical_attribute" (
  "id" bigint NOT NULL,
  "entity_id" bigint NOT NULL,
  "code" citext NOT NULL CHECK (length("code") <= 128),
  "name" citext NOT NULL CHECK (length("name") <= 256),
  "logical_type" citext CHECK (length("logical_type") <= 128),
  "description" citext CHECK (length("description") <= 1024),
  "primary_flag" smallint DEFAULT 0,
  "nullable" smallint DEFAULT 1,
  "sort" integer DEFAULT 0,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_logical_attribute_idx_logical_attribute_entity_id" ON "yak_modeling_logical_attribute" ("entity_id");

CREATE TABLE "yak_modeling_entity_relation" (
  "id" bigint NOT NULL,
  "source_entity_id" bigint NOT NULL,
  "target_entity_id" bigint NOT NULL,
  "relation_type" citext CHECK (length("relation_type") <= 64),
  "cardinality" citext CHECK (length("cardinality") <= 64),
  "description" citext CHECK (length("description") <= 1024),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_entity_relation_idx_entity_relation_source" ON "yak_modeling_entity_relation" ("source_entity_id");

CREATE INDEX "yak_modeling_entity_relation_idx_entity_relation_target" ON "yak_modeling_entity_relation" ("target_entity_id");

CREATE TABLE "yak_modeling_logical_entity_mapping" (
  "id" bigint NOT NULL,
  "logical_entity_id" bigint NOT NULL,
  "physical_table_id" bigint NOT NULL,
  "mapping_type" citext CHECK (length("mapping_type") <= 64),
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "description" citext CHECK (length("description") <= 512),
  "create_time" timestamp(0) without time zone,
  "update_time" timestamp(0) without time zone,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_logical_entity_mapping_idx_logical_entity_e39ecdae" ON "yak_modeling_logical_entity_mapping" ("logical_entity_id");

CREATE TABLE "yak_modeling_logical_attribute_mapping" (
  "id" bigint NOT NULL,
  "logical_attribute_id" bigint NOT NULL,
  "physical_column_id" bigint NOT NULL,
  "mapping_expression" citext CHECK (length("mapping_expression") <= 512),
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "create_time" timestamp(0) without time zone,
  "update_time" timestamp(0) without time zone,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_logical_attribute_mapping_idx_logical_att_fb60f62e" ON "yak_modeling_logical_attribute_mapping" ("logical_attribute_id");

CREATE TABLE "yak_modeling_logical_model_version" (
  "id" bigint NOT NULL,
  "model_id" bigint NOT NULL,
  "version_no" integer NOT NULL,
  "status" citext NOT NULL CHECK (length("status") <= 32),
  "snapshot" text,
  "created_by" citext CHECK (length("created_by") <= 64),
  "create_time" timestamp(0) without time zone,
  "update_time" timestamp(0) without time zone,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_modeling_logical_model_version_idx_model_version_model_id" ON "yak_modeling_logical_model_version" ("model_id");
