-- PostgreSQL fresh-deployment baseline. Existing MySQL migration checksums are unchanged.

-- Mirrors the consolidated MySQL domain baseline; forward changes require migrations for both vendors.

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION yak_touch_update_timestamp() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (to_jsonb(NEW) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      IS DISTINCT FROM (to_jsonb(OLD) - COALESCE(TG_ARGV[1:array_upper(TG_ARGV, 1)], ARRAY[]::text[]))
      AND (to_jsonb(NEW)->TG_ARGV[0]) IS NOT DISTINCT FROM (to_jsonb(OLD)->TG_ARGV[0]) THEN
    NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], CURRENT_TIMESTAMP));
  END IF;
  RETURN NEW;
END $$;

CREATE TABLE "yak_asset_item" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "asset_key" citext NOT NULL CHECK (length("asset_key") <= 256),
  "source_type" citext NOT NULL CHECK (length("source_type") <= 16),
  "source_id" citext NOT NULL CHECK (length("source_id") <= 64),
  "asset_type" citext NOT NULL CHECK (length("asset_type") <= 16),
  "name" citext NOT NULL CHECK (length("name") <= 128),
  "description" citext CHECK (length("description") <= 1024),
  "layer_code" citext CHECK (length("layer_code") <= 32),
  "domain_code" citext CHECK (length("domain_code") <= 32),
  "directory_id" bigint,
  "owner" citext CHECK (length("owner") <= 64),
  "status" citext DEFAULT 'PENDING' NOT NULL CHECK (length("status") <= 16),
  "content_hash" citext CHECK (length("content_hash") <= 64),
  "source_updated_at" timestamp(6) without time zone,
  "security_level_code" citext CHECK (length("security_level_code") <= 32),
  "health_score" integer,
  "health_grade" citext CHECK (length("health_grade") <= 2),
  "health_detail" text,
  "view_count_30d" integer DEFAULT 0 NOT NULL,
  "access_uri" citext CHECK (length("access_uri") <= 512),
  "first_listed_at" timestamp(6) without time zone,
  "last_listed_at" timestamp(6) without time zone,
  "last_offline_at" timestamp(6) without time zone,
  "last_offline_reason" citext CHECK (length("last_offline_reason") <= 512),
  "reconciled_at" timestamp(6) without time zone,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "updated_by" citext CHECK (length("updated_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_asset_item_idx_asset_item_dir" ON "yak_asset_item" ("project_id", "directory_id");

CREATE INDEX "yak_asset_item_idx_asset_item_name" ON "yak_asset_item" ("project_id", "name");

CREATE INDEX "yak_asset_item_idx_asset_item_owner" ON "yak_asset_item" ("project_id", "owner");

CREATE INDEX "yak_asset_item_idx_asset_item_status" ON "yak_asset_item" ("project_id", "status", "deleted");

CREATE INDEX "yak_asset_item_idx_asset_item_type" ON "yak_asset_item" ("project_id", "asset_type", "deleted");

CREATE UNIQUE INDEX "yak_asset_item_uk_asset_item_key" ON "yak_asset_item" ("project_id", "asset_key");

CREATE TRIGGER "yak_asset_item_touch" BEFORE UPDATE ON "yak_asset_item" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_asset_directory" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "dir_code" citext NOT NULL CHECK (length("dir_code") <= 64),
  "dir_name" citext NOT NULL CHECK (length("dir_name") <= 128),
  "parent_id" bigint DEFAULT 0 NOT NULL,
  "path" citext NOT NULL CHECK (length("path") <= 512),
  "sort_order" integer DEFAULT 0 NOT NULL,
  "icon_key" citext CHECK (length("icon_key") <= 64),
  "description" citext CHECK (length("description") <= 512),
  "builtin" smallint DEFAULT 0 NOT NULL,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "updated_by" citext CHECK (length("updated_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_asset_directory_idx_asset_dir_parent" ON "yak_asset_directory" ("project_id", "parent_id", "sort_order");

CREATE UNIQUE INDEX "yak_asset_directory_uk_asset_dir_code" ON "yak_asset_directory" ("project_id", "dir_code");

CREATE TRIGGER "yak_asset_directory_touch" BEFORE UPDATE ON "yak_asset_directory" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_asset_tag" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "tag_code" citext NOT NULL CHECK (length("tag_code") <= 64),
  "tag_name" citext NOT NULL CHECK (length("tag_name") <= 128),
  "color" citext CHECK (length("color") <= 32),
  "description" citext CHECK (length("description") <= 512),
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "updated_by" citext CHECK (length("updated_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_asset_tag_uk_asset_tag_code" ON "yak_asset_tag" ("project_id", "tag_code");

CREATE TRIGGER "yak_asset_tag_touch" BEFORE UPDATE ON "yak_asset_tag" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_asset_tag_rel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "asset_id" bigint NOT NULL,
  "tag_id" bigint NOT NULL,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_asset_tag_rel_idx_asset_tag_rel_tag" ON "yak_asset_tag_rel" ("project_id", "tag_id");

CREATE UNIQUE INDEX "yak_asset_tag_rel_uk_asset_tag_rel" ON "yak_asset_tag_rel" ("project_id", "asset_id", "tag_id");

CREATE TABLE "yak_asset_assign_rule" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "rule_name" citext NOT NULL CHECK (length("rule_name") <= 128),
  "rule_type" citext NOT NULL CHECK (length("rule_type") <= 16),
  "conditions" text NOT NULL,
  "target_directory_id" bigint,
  "target_tag_id" bigint,
  "priority" integer DEFAULT 100 NOT NULL,
  "enabled" smallint DEFAULT 0 NOT NULL,
  "last_apply_hit" integer,
  "created_by" citext NOT NULL CHECK (length("created_by") <= 64),
  "updated_by" citext CHECK (length("updated_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_asset_assign_rule_idx_asset_rule_type" ON "yak_asset_assign_rule" ("project_id", "rule_type", "enabled", "priority");

CREATE TRIGGER "yak_asset_assign_rule_touch" BEFORE UPDATE ON "yak_asset_assign_rule" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_asset_change_record" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "asset_id" bigint NOT NULL,
  "change_type" citext NOT NULL CHECK (length("change_type") <= 16),
  "diff" text,
  "handle_status" citext DEFAULT 'OPEN' NOT NULL CHECK (length("handle_status") <= 16),
  "snapshot_new" text,
  "handled_by" citext CHECK (length("handled_by") <= 64),
  "handled_at" timestamp(6) without time zone,
  "created_by" citext DEFAULT 'system' NOT NULL CHECK (length("created_by") <= 64),
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  "deleted" smallint DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_asset_change_record_idx_asset_change_asset" ON "yak_asset_change_record" ("project_id", "asset_id", "id");

CREATE INDEX "yak_asset_change_record_idx_asset_change_handle" ON "yak_asset_change_record" ("project_id", "handle_status", "change_type");

CREATE TRIGGER "yak_asset_change_record_touch" BEFORE UPDATE ON "yak_asset_change_record" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');

CREATE TABLE "yak_asset_view_record" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "asset_id" bigint NOT NULL,
  "viewer" citext NOT NULL CHECK (length("viewer") <= 64),
  "view_time" timestamp(6) without time zone NOT NULL,
  "entry" citext CHECK (length("entry") <= 64),
  PRIMARY KEY ("id")
);

CREATE INDEX "yak_asset_view_record_idx_asset_view_asset" ON "yak_asset_view_record" ("project_id", "asset_id", "view_time");

CREATE INDEX "yak_asset_view_record_idx_asset_view_time" ON "yak_asset_view_record" ("project_id", "view_time");

CREATE TABLE "yak_asset_health_snapshot" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "snapshot_date" date NOT NULL,
  "layer_code" citext NOT NULL CHECK (length("layer_code") <= 32),
  "grade_a_count" integer DEFAULT 0 NOT NULL,
  "grade_b_count" integer DEFAULT 0 NOT NULL,
  "grade_c_count" integer DEFAULT 0 NOT NULL,
  "grade_d_count" integer DEFAULT 0 NOT NULL,
  "published_count" integer DEFAULT 0 NOT NULL,
  "create_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_asset_health_snapshot_uk_asset_health_snapshot" ON "yak_asset_health_snapshot" ("project_id", "snapshot_date", "layer_code");

CREATE TABLE "yak_asset_setting" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_id" bigint NOT NULL,
  "setting_key" citext NOT NULL CHECK (length("setting_key") <= 64),
  "setting_value" citext CHECK (length("setting_value") <= 256),
  "update_time" timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "yak_asset_setting_uk_asset_setting" ON "yak_asset_setting" ("project_id", "setting_key");

CREATE TRIGGER "yak_asset_setting_touch" BEFORE UPDATE ON "yak_asset_setting" FOR EACH ROW EXECUTE FUNCTION yak_touch_update_timestamp('update_time');
